FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /tiny-controller ./cmd/controller && CGO_ENABLED=0 go build -o /tiny-cli ./cmd/tiny
FROM gcr.io/distroless/static:nonroot
COPY --from=build /tiny-controller /tiny-controller
COPY --from=build /tiny-cli /tiny-cli
ENTRYPOINT ["/tiny-controller"]
