// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file access-item.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.AccessItem
 */
export class AccessItem extends Message<AccessItem> {
  /**
   * @generated from field: map<string, bool> Access = 1;
   */
  Access: { [key: string]: boolean } = {};

  constructor(data?: PartialMessage<AccessItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.AccessItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Access", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 8 /* ScalarType.BOOL */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccessItem {
    return new AccessItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccessItem {
    return new AccessItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccessItem {
    return new AccessItem().fromJsonString(jsonString, options);
  }

  static equals(a: AccessItem | PlainMessage<AccessItem> | undefined, b: AccessItem | PlainMessage<AccessItem> | undefined): boolean {
    return proto3.util.equals(AccessItem, a, b);
  }
}

