// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file auth.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { User } from "./user_pb.js";
import { WorkspaceRole } from "./workspace_pb.js";

/**
 * @generated from message platform.SignInRequest
 */
export class SignInRequest extends Message<SignInRequest> {
  /**
   * @generated from field: string Email = 1;
   */
  Email = "";

  /**
   * @generated from field: string Password = 2;
   */
  Password = "";

  constructor(data?: PartialMessage<SignInRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SignInRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignInRequest {
    return new SignInRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignInRequest {
    return new SignInRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignInRequest {
    return new SignInRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SignInRequest | PlainMessage<SignInRequest> | undefined, b: SignInRequest | PlainMessage<SignInRequest> | undefined): boolean {
    return proto3.util.equals(SignInRequest, a, b);
  }
}

/**
 * @generated from message platform.SignInResponse
 */
export class SignInResponse extends Message<SignInResponse> {
  /**
   * @generated from field: platform.User Account = 1;
   */
  Account?: User;

  /**
   * @generated from field: platform.WorkspaceRole Workspace = 2;
   */
  Workspace?: WorkspaceRole;

  /**
   * @generated from field: repeated platform.WorkspaceRole Workspaces = 3;
   */
  Workspaces: WorkspaceRole[] = [];

  /**
   * @generated from field: string SessionID = 4;
   */
  SessionID = "";

  /**
   * @generated from field: bool IsPlatformAdmin = 5;
   */
  IsPlatformAdmin = false;

  constructor(data?: PartialMessage<SignInResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SignInResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Account", kind: "message", T: User },
    { no: 2, name: "Workspace", kind: "message", T: WorkspaceRole },
    { no: 3, name: "Workspaces", kind: "message", T: WorkspaceRole, repeated: true },
    { no: 4, name: "SessionID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "IsPlatformAdmin", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignInResponse {
    return new SignInResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignInResponse {
    return new SignInResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignInResponse {
    return new SignInResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SignInResponse | PlainMessage<SignInResponse> | undefined, b: SignInResponse | PlainMessage<SignInResponse> | undefined): boolean {
    return proto3.util.equals(SignInResponse, a, b);
  }
}

/**
 * @generated from message platform.SignUpRequest
 */
export class SignUpRequest extends Message<SignUpRequest> {
  /**
   * @generated from field: string Email = 1;
   */
  Email = "";

  /**
   * @generated from field: string Username = 2;
   */
  Username = "";

  /**
   * @generated from field: string FirstName = 3;
   */
  FirstName = "";

  /**
   * @generated from field: string LastName = 4;
   */
  LastName = "";

  constructor(data?: PartialMessage<SignUpRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SignUpRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "FirstName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "LastName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignUpRequest {
    return new SignUpRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignUpRequest {
    return new SignUpRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignUpRequest {
    return new SignUpRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SignUpRequest | PlainMessage<SignUpRequest> | undefined, b: SignUpRequest | PlainMessage<SignUpRequest> | undefined): boolean {
    return proto3.util.equals(SignUpRequest, a, b);
  }
}

/**
 * @generated from message platform.CurrentUserResponse
 */
export class CurrentUserResponse extends Message<CurrentUserResponse> {
  /**
   * @generated from field: platform.User User = 1;
   */
  User?: User;

  /**
   * @generated from field: platform.WorkspaceRole Workspace = 2;
   */
  Workspace?: WorkspaceRole;

  /**
   * @generated from field: repeated platform.WorkspaceRole Workspaces = 3;
   */
  Workspaces: WorkspaceRole[] = [];

  /**
   * @generated from field: map<string, string> Features = 4;
   */
  Features: { [key: string]: string } = {};

  /**
   * @generated from field: string TariffPlanName = 5;
   */
  TariffPlanName = "";

  constructor(data?: PartialMessage<CurrentUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CurrentUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "User", kind: "message", T: User },
    { no: 2, name: "Workspace", kind: "message", T: WorkspaceRole },
    { no: 3, name: "Workspaces", kind: "message", T: WorkspaceRole, repeated: true },
    { no: 4, name: "Features", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 5, name: "TariffPlanName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CurrentUserResponse {
    return new CurrentUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CurrentUserResponse {
    return new CurrentUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CurrentUserResponse {
    return new CurrentUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CurrentUserResponse | PlainMessage<CurrentUserResponse> | undefined, b: CurrentUserResponse | PlainMessage<CurrentUserResponse> | undefined): boolean {
    return proto3.util.equals(CurrentUserResponse, a, b);
  }
}

/**
 * @generated from message platform.ResetPasswordRequest
 */
export class ResetPasswordRequest extends Message<ResetPasswordRequest> {
  /**
   * @generated from field: string Email = 1;
   */
  Email = "";

  constructor(data?: PartialMessage<ResetPasswordRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ResetPasswordRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetPasswordRequest {
    return new ResetPasswordRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetPasswordRequest {
    return new ResetPasswordRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetPasswordRequest {
    return new ResetPasswordRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResetPasswordRequest | PlainMessage<ResetPasswordRequest> | undefined, b: ResetPasswordRequest | PlainMessage<ResetPasswordRequest> | undefined): boolean {
    return proto3.util.equals(ResetPasswordRequest, a, b);
  }
}

/**
 * @generated from message platform.OAuthURLRequest
 */
export class OAuthURLRequest extends Message<OAuthURLRequest> {
  /**
   * @generated from field: string provider = 1;
   */
  provider = "";

  /**
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri = "";

  constructor(data?: PartialMessage<OAuthURLRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.OAuthURLRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "redirect_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OAuthURLRequest {
    return new OAuthURLRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OAuthURLRequest {
    return new OAuthURLRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OAuthURLRequest {
    return new OAuthURLRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OAuthURLRequest | PlainMessage<OAuthURLRequest> | undefined, b: OAuthURLRequest | PlainMessage<OAuthURLRequest> | undefined): boolean {
    return proto3.util.equals(OAuthURLRequest, a, b);
  }
}

/**
 * @generated from message platform.OAuthURLResponse
 */
export class OAuthURLResponse extends Message<OAuthURLResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  constructor(data?: PartialMessage<OAuthURLResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.OAuthURLResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OAuthURLResponse {
    return new OAuthURLResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OAuthURLResponse {
    return new OAuthURLResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OAuthURLResponse {
    return new OAuthURLResponse().fromJsonString(jsonString, options);
  }

  static equals(a: OAuthURLResponse | PlainMessage<OAuthURLResponse> | undefined, b: OAuthURLResponse | PlainMessage<OAuthURLResponse> | undefined): boolean {
    return proto3.util.equals(OAuthURLResponse, a, b);
  }
}

/**
 * @generated from message platform.OAuthCallbackRequest
 */
export class OAuthCallbackRequest extends Message<OAuthCallbackRequest> {
  /**
   * @generated from field: string code = 1;
   */
  code = "";

  /**
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri = "";

  /**
   * @generated from field: string state = 3;
   */
  state = "";

  constructor(data?: PartialMessage<OAuthCallbackRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.OAuthCallbackRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "redirect_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OAuthCallbackRequest {
    return new OAuthCallbackRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OAuthCallbackRequest {
    return new OAuthCallbackRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OAuthCallbackRequest {
    return new OAuthCallbackRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OAuthCallbackRequest | PlainMessage<OAuthCallbackRequest> | undefined, b: OAuthCallbackRequest | PlainMessage<OAuthCallbackRequest> | undefined): boolean {
    return proto3.util.equals(OAuthCallbackRequest, a, b);
  }
}

