// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file auth.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CurrentUserResponse, OAuthCallbackRequest, OAuthURLRequest, OAuthURLResponse, ResetPasswordRequest, SignInRequest, SignInResponse, SignUpRequest } from "./auth.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Nil } from "./nil_pb.js";

/**
 * @generated from service platform.AuthService
 */
export const AuthService = {
  typeName: "platform.AuthService",
  methods: {
    /**
     * @generated from rpc platform.AuthService.SignIn
     */
    signIn: {
      name: "SignIn",
      I: SignInRequest,
      O: SignInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.AuthService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.AuthService.SignOut
     */
    signOut: {
      name: "SignOut",
      I: Nil,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.AuthService.CurrentUserInfo
     */
    currentUserInfo: {
      name: "CurrentUserInfo",
      I: Nil,
      O: CurrentUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.AuthService.ResetPassword
     */
    resetPassword: {
      name: "ResetPassword",
      I: ResetPasswordRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.AuthService.GetOAuthURL
     */
    getOAuthURL: {
      name: "GetOAuthURL",
      I: OAuthURLRequest,
      O: OAuthURLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.AuthService.OAuthCallback
     */
    oAuthCallback: {
      name: "OAuthCallback",
      I: OAuthCallbackRequest,
      O: SignInResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

