// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file billing.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * SubscriptionStatus represents the subscription status
 *
 * @generated from enum platform.SubscriptionStatus
 */
export enum SubscriptionStatus {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_ACTIVE = 1;
   */
  STATUS_ACTIVE = 1,

  /**
   * @generated from enum value: STATUS_CANCELED = 2;
   */
  STATUS_CANCELED = 2,

  /**
   * @generated from enum value: STATUS_PAST_DUE = 3;
   */
  STATUS_PAST_DUE = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(SubscriptionStatus)
proto3.util.setEnumType(SubscriptionStatus, "platform.SubscriptionStatus", [
  { no: 0, name: "STATUS_UNSPECIFIED" },
  { no: 1, name: "STATUS_ACTIVE" },
  { no: 2, name: "STATUS_CANCELED" },
  { no: 3, name: "STATUS_PAST_DUE" },
]);

/**
 * BillingInterval represents the billing interval
 *
 * @generated from enum platform.BillingInterval
 */
export enum BillingInterval {
  /**
   * @generated from enum value: INTERVAL_UNSPECIFIED = 0;
   */
  INTERVAL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: INTERVAL_MONTHLY = 1;
   */
  INTERVAL_MONTHLY = 1,

  /**
   * @generated from enum value: INTERVAL_YEARLY = 2;
   */
  INTERVAL_YEARLY = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(BillingInterval)
proto3.util.setEnumType(BillingInterval, "platform.BillingInterval", [
  { no: 0, name: "INTERVAL_UNSPECIFIED" },
  { no: 1, name: "INTERVAL_MONTHLY" },
  { no: 2, name: "INTERVAL_YEARLY" },
]);

/**
 * TariffPlan represents a subscription tier/plan
 *
 * @generated from message platform.TariffPlan
 */
export class TariffPlan extends Message<TariffPlan> {
  /**
   * @generated from field: int32 ID = 1;
   */
  ID = 0;

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: string DisplayName = 3;
   */
  DisplayName = "";

  /**
   * @generated from field: string Description = 4;
   */
  Description = "";

  /**
   * @generated from field: bool IsDefault = 5;
   */
  IsDefault = false;

  constructor(data?: PartialMessage<TariffPlan>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.TariffPlan";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "IsDefault", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TariffPlan {
    return new TariffPlan().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TariffPlan {
    return new TariffPlan().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TariffPlan {
    return new TariffPlan().fromJsonString(jsonString, options);
  }

  static equals(a: TariffPlan | PlainMessage<TariffPlan> | undefined, b: TariffPlan | PlainMessage<TariffPlan> | undefined): boolean {
    return proto3.util.equals(TariffPlan, a, b);
  }
}

/**
 * Subscription represents a workspace subscription
 *
 * @generated from message platform.Subscription
 */
export class Subscription extends Message<Subscription> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string TariffPlanName = 2;
   */
  TariffPlanName = "";

  /**
   * @generated from field: platform.SubscriptionStatus Status = 3;
   */
  Status = SubscriptionStatus.STATUS_UNSPECIFIED;

  /**
   * @generated from field: platform.BillingInterval BillingInterval = 4;
   */
  BillingInterval = BillingInterval.INTERVAL_UNSPECIFIED;

  /**
   * @generated from field: string CurrentPeriodStart = 5;
   */
  CurrentPeriodStart = "";

  /**
   * @generated from field: string CurrentPeriodEnd = 6;
   */
  CurrentPeriodEnd = "";

  /**
   * @generated from field: bool CancelAtPeriodEnd = 7;
   */
  CancelAtPeriodEnd = false;

  /**
   * @generated from field: string CreatedAt = 8;
   */
  CreatedAt = "";

  /**
   * @generated from field: string UpdatedAt = 9;
   */
  UpdatedAt = "";

  /**
   * @generated from field: platform.TariffPlan TariffPlan = 10;
   */
  TariffPlan?: TariffPlan;

  constructor(data?: PartialMessage<Subscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Subscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "TariffPlanName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Status", kind: "enum", T: proto3.getEnumType(SubscriptionStatus) },
    { no: 4, name: "BillingInterval", kind: "enum", T: proto3.getEnumType(BillingInterval) },
    { no: 5, name: "CurrentPeriodStart", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "CurrentPeriodEnd", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "CancelAtPeriodEnd", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "CreatedAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "UpdatedAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "TariffPlan", kind: "message", T: TariffPlan },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Subscription {
    return new Subscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Subscription {
    return new Subscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Subscription {
    return new Subscription().fromJsonString(jsonString, options);
  }

  static equals(a: Subscription | PlainMessage<Subscription> | undefined, b: Subscription | PlainMessage<Subscription> | undefined): boolean {
    return proto3.util.equals(Subscription, a, b);
  }
}

/**
 * PricingInfo contains pricing details
 *
 * @generated from message platform.PricingInfo
 */
export class PricingInfo extends Message<PricingInfo> {
  /**
   * @generated from field: int64 MonthlyAmountCents = 1;
   */
  MonthlyAmountCents = protoInt64.zero;

  /**
   * @generated from field: int64 YearlyAmountCents = 2;
   */
  YearlyAmountCents = protoInt64.zero;

  /**
   * @generated from field: string Currency = 3;
   */
  Currency = "";

  constructor(data?: PartialMessage<PricingInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PricingInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "MonthlyAmountCents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "YearlyAmountCents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "Currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PricingInfo {
    return new PricingInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PricingInfo {
    return new PricingInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PricingInfo {
    return new PricingInfo().fromJsonString(jsonString, options);
  }

  static equals(a: PricingInfo | PlainMessage<PricingInfo> | undefined, b: PricingInfo | PlainMessage<PricingInfo> | undefined): boolean {
    return proto3.util.equals(PricingInfo, a, b);
  }
}

/**
 * TariffPlanPricing contains pricing for a specific tariff plan
 *
 * @generated from message platform.TariffPlanPricing
 */
export class TariffPlanPricing extends Message<TariffPlanPricing> {
  /**
   * @generated from field: int32 TariffPlanID = 1;
   */
  TariffPlanID = 0;

  /**
   * @generated from field: string TariffPlanName = 2;
   */
  TariffPlanName = "";

  /**
   * @generated from field: string DisplayName = 3;
   */
  DisplayName = "";

  /**
   * @generated from field: int64 PricePerMonthCents = 4;
   */
  PricePerMonthCents = protoInt64.zero;

  /**
   * @generated from field: int32 PricePerMonthDiscount = 5;
   */
  PricePerMonthDiscount = 0;

  /**
   * @generated from field: int64 AnnualPriceCents = 6;
   */
  AnnualPriceCents = protoInt64.zero;

  /**
   * @generated from field: int32 AnnualPriceDiscount = 7;
   */
  AnnualPriceDiscount = 0;

  /**
   * @generated from field: int64 EffectiveMonthlyPriceCents = 8;
   */
  EffectiveMonthlyPriceCents = protoInt64.zero;

  /**
   * @generated from field: int64 EffectiveAnnualPriceCents = 9;
   */
  EffectiveAnnualPriceCents = protoInt64.zero;

  /**
   * @generated from field: string Currency = 10;
   */
  Currency = "";

  constructor(data?: PartialMessage<TariffPlanPricing>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.TariffPlanPricing";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "TariffPlanID", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "TariffPlanName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "PricePerMonthCents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "PricePerMonthDiscount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "AnnualPriceCents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "AnnualPriceDiscount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "EffectiveMonthlyPriceCents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "EffectiveAnnualPriceCents", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "Currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TariffPlanPricing {
    return new TariffPlanPricing().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TariffPlanPricing {
    return new TariffPlanPricing().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TariffPlanPricing {
    return new TariffPlanPricing().fromJsonString(jsonString, options);
  }

  static equals(a: TariffPlanPricing | PlainMessage<TariffPlanPricing> | undefined, b: TariffPlanPricing | PlainMessage<TariffPlanPricing> | undefined): boolean {
    return proto3.util.equals(TariffPlanPricing, a, b);
  }
}

