// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file billing.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelSubscriptionRequest, CancelSubscriptionResponse, CreateCheckoutSessionRequest, CreateCheckoutSessionResponse, CreatePortalSessionRequest, CreatePortalSessionResponse, GetPricingRequest, GetPricingResponse, GetSubscriptionRequest, GetSubscriptionResponse, ReactivateSubscriptionRequest, ReactivateSubscriptionResponse } from "./billing.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * BillingService handles subscription and billing operations
 *
 * @generated from service platform.BillingService
 */
export const BillingService = {
  typeName: "platform.BillingService",
  methods: {
    /**
     * GetPricing returns the current pricing information (public)
     *
     * @generated from rpc platform.BillingService.GetPricing
     */
    getPricing: {
      name: "GetPricing",
      I: GetPricingRequest,
      O: GetPricingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetSubscription returns the current workspace subscription
     *
     * @generated from rpc platform.BillingService.GetSubscription
     */
    getSubscription: {
      name: "GetSubscription",
      I: GetSubscriptionRequest,
      O: GetSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreateCheckoutSession creates a Stripe Checkout session for subscribing
     *
     * @generated from rpc platform.BillingService.CreateCheckoutSession
     */
    createCheckoutSession: {
      name: "CreateCheckoutSession",
      I: CreateCheckoutSessionRequest,
      O: CreateCheckoutSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreatePortalSession creates a Stripe Customer Portal session for managing subscription
     *
     * @generated from rpc platform.BillingService.CreatePortalSession
     */
    createPortalSession: {
      name: "CreatePortalSession",
      I: CreatePortalSessionRequest,
      O: CreatePortalSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CancelSubscription cancels the subscription at the end of the billing period
     *
     * @generated from rpc platform.BillingService.CancelSubscription
     */
    cancelSubscription: {
      name: "CancelSubscription",
      I: CancelSubscriptionRequest,
      O: CancelSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ReactivateSubscription reactivates a subscription that was scheduled for cancellation
     *
     * @generated from rpc platform.BillingService.ReactivateSubscription
     */
    reactivateSubscription: {
      name: "ReactivateSubscription",
      I: ReactivateSubscriptionRequest,
      O: ReactivateSubscriptionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

