// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file cluster.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Cluster
 */
export class Cluster extends Message<Cluster> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: string Region = 3;
   */
  Region = "";

  /**
   * @generated from field: google.protobuf.Timestamp CreatedAt = 4;
   */
  CreatedAt?: Timestamp;

  /**
   * @generated from field: bool IsPublic = 6;
   */
  IsPublic = false;

  /**
   * @generated from field: bool Allocatable = 7;
   */
  Allocatable = false;

  /**
   * @generated from field: string Agreement = 8;
   */
  Agreement = "";

  /**
   * @generated from field: bool Insecure = 9;
   */
  Insecure = false;

  /**
   * @generated from field: bool HttpFeaturesAvailable = 10;
   */
  HttpFeaturesAvailable = false;

  /**
   * @generated from field: string IngressControllerIpAddress = 11;
   */
  IngressControllerIpAddress = "";

  constructor(data?: PartialMessage<Cluster>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Cluster";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Region", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "CreatedAt", kind: "message", T: Timestamp },
    { no: 6, name: "IsPublic", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "Allocatable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "Agreement", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "Insecure", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "HttpFeaturesAvailable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "IngressControllerIpAddress", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Cluster {
    return new Cluster().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Cluster {
    return new Cluster().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Cluster {
    return new Cluster().fromJsonString(jsonString, options);
  }

  static equals(a: Cluster | PlainMessage<Cluster> | undefined, b: Cluster | PlainMessage<Cluster> | undefined): boolean {
    return proto3.util.equals(Cluster, a, b);
  }
}

/**
 * @generated from message platform.ClusterStatus
 */
export class ClusterStatus extends Message<ClusterStatus> {
  /**
   * @generated from field: bool Connected = 1;
   */
  Connected = false;

  /**
   * @generated from field: bool Healthy = 2;
   */
  Healthy = false;

  /**
   * @generated from field: string Status = 3;
   */
  Status = "";

  /**
   * @generated from field: string StatusCode = 4;
   */
  StatusCode = "";

  /**
   * @generated from field: bool ShowButton = 5;
   */
  ShowButton = false;

  /**
   * @generated from field: string ButtonText = 6;
   */
  ButtonText = "";

  /**
   * @generated from field: string ButtonColor = 7;
   */
  ButtonColor = "";

  /**
   * @generated from field: string KubernetesVersion = 8;
   */
  KubernetesVersion = "";

  /**
   * @generated from field: string CRDVersion = 9;
   */
  CRDVersion = "";

  /**
   * @generated from field: google.protobuf.Timestamp LastUpdate = 10;
   */
  LastUpdate?: Timestamp;

  constructor(data?: PartialMessage<ClusterStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Connected", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "Healthy", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "StatusCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "ShowButton", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "ButtonText", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "ButtonColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "KubernetesVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "CRDVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "LastUpdate", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterStatus {
    return new ClusterStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterStatus {
    return new ClusterStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterStatus {
    return new ClusterStatus().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterStatus | PlainMessage<ClusterStatus> | undefined, b: ClusterStatus | PlainMessage<ClusterStatus> | undefined): boolean {
    return proto3.util.equals(ClusterStatus, a, b);
  }
}

/**
 * @generated from message platform.ClusterInfo
 */
export class ClusterInfo extends Message<ClusterInfo> {
  constructor(data?: PartialMessage<ClusterInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterInfo {
    return new ClusterInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterInfo {
    return new ClusterInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterInfo {
    return new ClusterInfo().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterInfo | PlainMessage<ClusterInfo> | undefined, b: ClusterInfo | PlainMessage<ClusterInfo> | undefined): boolean {
    return proto3.util.equals(ClusterInfo, a, b);
  }
}

/**
 * @generated from message platform.ClusterWorkspaceUsage
 */
export class ClusterWorkspaceUsage extends Message<ClusterWorkspaceUsage> {
  constructor(data?: PartialMessage<ClusterWorkspaceUsage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterWorkspaceUsage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterWorkspaceUsage {
    return new ClusterWorkspaceUsage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterWorkspaceUsage {
    return new ClusterWorkspaceUsage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterWorkspaceUsage {
    return new ClusterWorkspaceUsage().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterWorkspaceUsage | PlainMessage<ClusterWorkspaceUsage> | undefined, b: ClusterWorkspaceUsage | PlainMessage<ClusterWorkspaceUsage> | undefined): boolean {
    return proto3.util.equals(ClusterWorkspaceUsage, a, b);
  }
}

