// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file cluster.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Pagination, PaginationRequest } from "./pagination_pb.js";
import { Deployment } from "./deployment_pb.js";
import { Module, ModuleVersion } from "./module_pb.js";
import { Server } from "./server_pb.js";
import { Cluster, ClusterInfo, ClusterStatus, ClusterWorkspaceUsage } from "./cluster_pb.js";
import { Workspace } from "./workspace_pb.js";
import { AccessItem } from "./access-item_pb.js";
import { Configuration } from "./configuration_pb.js";

/**
 * @generated from message platform.ClusterListRequest
 */
export class ClusterListRequest extends Message<ClusterListRequest> {
  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 1;
   */
  PaginationRequest?: PaginationRequest;

  /**
   * @generated from field: bool IncludePublic = 3;
   */
  IncludePublic = false;

  constructor(data?: PartialMessage<ClusterListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PaginationRequest", kind: "message", T: PaginationRequest },
    { no: 3, name: "IncludePublic", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterListRequest {
    return new ClusterListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterListRequest {
    return new ClusterListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterListRequest {
    return new ClusterListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterListRequest | PlainMessage<ClusterListRequest> | undefined, b: ClusterListRequest | PlainMessage<ClusterListRequest> | undefined): boolean {
    return proto3.util.equals(ClusterListRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentExtended
 */
export class DeploymentExtended extends Message<DeploymentExtended> {
  /**
   * @generated from field: platform.Deployment Deployment = 1;
   */
  Deployment?: Deployment;

  /**
   * @generated from field: platform.ModuleVersion Version = 2;
   */
  Version?: ModuleVersion;

  /**
   * @generated from field: platform.Module Module = 3;
   */
  Module?: Module;

  /**
   * @generated from field: platform.Server Server = 4;
   */
  Server?: Server;

  /**
   * @generated from field: platform.Cluster Cluster = 8;
   */
  Cluster?: Cluster;

  constructor(data?: PartialMessage<DeploymentExtended>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentExtended";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Deployment", kind: "message", T: Deployment },
    { no: 2, name: "Version", kind: "message", T: ModuleVersion },
    { no: 3, name: "Module", kind: "message", T: Module },
    { no: 4, name: "Server", kind: "message", T: Server },
    { no: 8, name: "Cluster", kind: "message", T: Cluster },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentExtended {
    return new DeploymentExtended().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentExtended {
    return new DeploymentExtended().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentExtended {
    return new DeploymentExtended().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentExtended | PlainMessage<DeploymentExtended> | undefined, b: DeploymentExtended | PlainMessage<DeploymentExtended> | undefined): boolean {
    return proto3.util.equals(DeploymentExtended, a, b);
  }
}

/**
 * @generated from message platform.ClusterListItem
 */
export class ClusterListItem extends Message<ClusterListItem> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: platform.Cluster Cluster = 2;
   */
  Cluster?: Cluster;

  /**
   * @generated from field: platform.Server Server = 3;
   */
  Server?: Server;

  /**
   * @generated from field: platform.Workspace Workspace = 4;
   */
  Workspace?: Workspace;

  /**
   * @generated from field: bool CanConfigure = 5;
   */
  CanConfigure = false;

  /**
   * @generated from field: platform.ClusterStatus Status = 6;
   */
  Status?: ClusterStatus;

  /**
   * @generated from field: platform.AccessItem Access = 7;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<ClusterListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Cluster", kind: "message", T: Cluster },
    { no: 3, name: "Server", kind: "message", T: Server },
    { no: 4, name: "Workspace", kind: "message", T: Workspace },
    { no: 5, name: "CanConfigure", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "Status", kind: "message", T: ClusterStatus },
    { no: 7, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterListItem {
    return new ClusterListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterListItem {
    return new ClusterListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterListItem {
    return new ClusterListItem().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterListItem | PlainMessage<ClusterListItem> | undefined, b: ClusterListItem | PlainMessage<ClusterListItem> | undefined): boolean {
    return proto3.util.equals(ClusterListItem, a, b);
  }
}

/**
 * @generated from message platform.ClusterListResponse
 */
export class ClusterListResponse extends Message<ClusterListResponse> {
  /**
   * @generated from field: repeated platform.ClusterListItem Clusters = 1;
   */
  Clusters: ClusterListItem[] = [];

  /**
   * @generated from field: platform.Pagination Pagination = 2;
   */
  Pagination?: Pagination;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Configuration NewClusterForm = 4;
   */
  NewClusterForm?: Configuration;

  constructor(data?: PartialMessage<ClusterListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Clusters", kind: "message", T: ClusterListItem, repeated: true },
    { no: 2, name: "Pagination", kind: "message", T: Pagination },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
    { no: 4, name: "NewClusterForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterListResponse {
    return new ClusterListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterListResponse {
    return new ClusterListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterListResponse {
    return new ClusterListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterListResponse | PlainMessage<ClusterListResponse> | undefined, b: ClusterListResponse | PlainMessage<ClusterListResponse> | undefined): boolean {
    return proto3.util.equals(ClusterListResponse, a, b);
  }
}

/**
 * @generated from message platform.ClusterAddRequest
 */
export class ClusterAddRequest extends Message<ClusterAddRequest> {
  /**
   * @generated from field: platform.Configuration NewClusterForm = 2;
   */
  NewClusterForm?: Configuration;

  constructor(data?: PartialMessage<ClusterAddRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterAddRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "NewClusterForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterAddRequest {
    return new ClusterAddRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterAddRequest {
    return new ClusterAddRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterAddRequest {
    return new ClusterAddRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterAddRequest | PlainMessage<ClusterAddRequest> | undefined, b: ClusterAddRequest | PlainMessage<ClusterAddRequest> | undefined): boolean {
    return proto3.util.equals(ClusterAddRequest, a, b);
  }
}

/**
 * @generated from message platform.ClusterProcessResponse
 */
export class ClusterProcessResponse extends Message<ClusterProcessResponse> {
  /**
   * @generated from field: platform.ClusterAddResponseStatus Status = 1;
   */
  Status?: ClusterAddResponseStatus;

  /**
   * @generated from field: platform.Cluster Cluster = 2;
   */
  Cluster?: Cluster;

  constructor(data?: PartialMessage<ClusterProcessResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterProcessResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Status", kind: "message", T: ClusterAddResponseStatus },
    { no: 2, name: "Cluster", kind: "message", T: Cluster },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterProcessResponse {
    return new ClusterProcessResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterProcessResponse {
    return new ClusterProcessResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterProcessResponse {
    return new ClusterProcessResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterProcessResponse | PlainMessage<ClusterProcessResponse> | undefined, b: ClusterProcessResponse | PlainMessage<ClusterProcessResponse> | undefined): boolean {
    return proto3.util.equals(ClusterProcessResponse, a, b);
  }
}

/**
 * @generated from message platform.ClusterAddResponseStatus
 */
export class ClusterAddResponseStatus extends Message<ClusterAddResponseStatus> {
  /**
   * @generated from field: platform.ClusterAddResponseStatus.StatusCode Code = 1;
   */
  Code = ClusterAddResponseStatus_StatusCode.PROCESSING;

  /**
   * @generated from field: string Message = 2;
   */
  Message = "";

  constructor(data?: PartialMessage<ClusterAddResponseStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterAddResponseStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Code", kind: "enum", T: proto3.getEnumType(ClusterAddResponseStatus_StatusCode) },
    { no: 2, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterAddResponseStatus {
    return new ClusterAddResponseStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterAddResponseStatus {
    return new ClusterAddResponseStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterAddResponseStatus {
    return new ClusterAddResponseStatus().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterAddResponseStatus | PlainMessage<ClusterAddResponseStatus> | undefined, b: ClusterAddResponseStatus | PlainMessage<ClusterAddResponseStatus> | undefined): boolean {
    return proto3.util.equals(ClusterAddResponseStatus, a, b);
  }
}

/**
 * @generated from enum platform.ClusterAddResponseStatus.StatusCode
 */
export enum ClusterAddResponseStatus_StatusCode {
  /**
   * @generated from enum value: PROCESSING = 0;
   */
  PROCESSING = 0,

  /**
   * @generated from enum value: ERROR = 1;
   */
  ERROR = 1,

  /**
   * @generated from enum value: SUCCESS = 2;
   */
  SUCCESS = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ClusterAddResponseStatus_StatusCode)
proto3.util.setEnumType(ClusterAddResponseStatus_StatusCode, "platform.ClusterAddResponseStatus.StatusCode", [
  { no: 0, name: "PROCESSING" },
  { no: 1, name: "ERROR" },
  { no: 2, name: "SUCCESS" },
]);

/**
 * @generated from message platform.ClusterGetRequest
 */
export class ClusterGetRequest extends Message<ClusterGetRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  constructor(data?: PartialMessage<ClusterGetRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterGetRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterGetRequest {
    return new ClusterGetRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterGetRequest {
    return new ClusterGetRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterGetRequest {
    return new ClusterGetRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterGetRequest | PlainMessage<ClusterGetRequest> | undefined, b: ClusterGetRequest | PlainMessage<ClusterGetRequest> | undefined): boolean {
    return proto3.util.equals(ClusterGetRequest, a, b);
  }
}

/**
 * @generated from message platform.ServerListRequest
 */
export class ServerListRequest extends Message<ServerListRequest> {
  /**
   * @generated from field: string ClusterID = 2;
   */
  ClusterID = "";

  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 3;
   */
  PaginationRequest?: PaginationRequest;

  constructor(data?: PartialMessage<ServerListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "ClusterID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "PaginationRequest", kind: "message", T: PaginationRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerListRequest {
    return new ServerListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerListRequest {
    return new ServerListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerListRequest {
    return new ServerListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ServerListRequest | PlainMessage<ServerListRequest> | undefined, b: ServerListRequest | PlainMessage<ServerListRequest> | undefined): boolean {
    return proto3.util.equals(ServerListRequest, a, b);
  }
}

/**
 * @generated from message platform.ServerModuleListRequest
 */
export class ServerModuleListRequest extends Message<ServerModuleListRequest> {
  /**
   * @generated from field: string CheckModuleVersionId = 1;
   */
  CheckModuleVersionId = "";

  constructor(data?: PartialMessage<ServerModuleListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerModuleListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "CheckModuleVersionId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerModuleListRequest {
    return new ServerModuleListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerModuleListRequest {
    return new ServerModuleListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerModuleListRequest {
    return new ServerModuleListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ServerModuleListRequest | PlainMessage<ServerModuleListRequest> | undefined, b: ServerModuleListRequest | PlainMessage<ServerModuleListRequest> | undefined): boolean {
    return proto3.util.equals(ServerModuleListRequest, a, b);
  }
}

/**
 * @generated from message platform.ServerModuleListResponse
 */
export class ServerModuleListResponse extends Message<ServerModuleListResponse> {
  /**
   * @generated from field: repeated platform.ServerModuleListItem Servers = 1;
   */
  Servers: ServerModuleListItem[] = [];

  constructor(data?: PartialMessage<ServerModuleListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerModuleListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Servers", kind: "message", T: ServerModuleListItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerModuleListResponse {
    return new ServerModuleListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerModuleListResponse {
    return new ServerModuleListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerModuleListResponse {
    return new ServerModuleListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ServerModuleListResponse | PlainMessage<ServerModuleListResponse> | undefined, b: ServerModuleListResponse | PlainMessage<ServerModuleListResponse> | undefined): boolean {
    return proto3.util.equals(ServerModuleListResponse, a, b);
  }
}

/**
 * @generated from message platform.ServerListItem
 */
export class ServerListItem extends Message<ServerListItem> {
  /**
   * @generated from field: platform.Server Server = 1;
   */
  Server?: Server;

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<ServerListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Server", kind: "message", T: Server },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerListItem {
    return new ServerListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerListItem {
    return new ServerListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerListItem {
    return new ServerListItem().fromJsonString(jsonString, options);
  }

  static equals(a: ServerListItem | PlainMessage<ServerListItem> | undefined, b: ServerListItem | PlainMessage<ServerListItem> | undefined): boolean {
    return proto3.util.equals(ServerListItem, a, b);
  }
}

/**
 * @generated from message platform.ServerModuleListItem
 */
export class ServerModuleListItem extends Message<ServerModuleListItem> {
  /**
   * @generated from field: platform.Server Server = 1;
   */
  Server?: Server;

  /**
   * @generated from field: repeated platform.DeploymentExtended CheckModuleDeployments = 2;
   */
  CheckModuleDeployments: DeploymentExtended[] = [];

  /**
   * @generated from field: platform.ServerModuleListItem.CheckModuleVersionStatus ModuleVersionStatus = 3;
   */
  ModuleVersionStatus = ServerModuleListItem_CheckModuleVersionStatus.UNKNOWN;

  /**
   * @generated from field: platform.AccessItem Access = 4;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<ServerModuleListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerModuleListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Server", kind: "message", T: Server },
    { no: 2, name: "CheckModuleDeployments", kind: "message", T: DeploymentExtended, repeated: true },
    { no: 3, name: "ModuleVersionStatus", kind: "enum", T: proto3.getEnumType(ServerModuleListItem_CheckModuleVersionStatus) },
    { no: 4, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerModuleListItem {
    return new ServerModuleListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerModuleListItem {
    return new ServerModuleListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerModuleListItem {
    return new ServerModuleListItem().fromJsonString(jsonString, options);
  }

  static equals(a: ServerModuleListItem | PlainMessage<ServerModuleListItem> | undefined, b: ServerModuleListItem | PlainMessage<ServerModuleListItem> | undefined): boolean {
    return proto3.util.equals(ServerModuleListItem, a, b);
  }
}

/**
 * @generated from enum platform.ServerModuleListItem.CheckModuleVersionStatus
 */
export enum ServerModuleListItem_CheckModuleVersionStatus {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: NOTFOUND = 1;
   */
  NOTFOUND = 1,

  /**
   * @generated from enum value: LOWER = 2;
   */
  LOWER = 2,

  /**
   * @generated from enum value: GREATER = 3;
   */
  GREATER = 3,

  /**
   * @generated from enum value: EQUAL = 4;
   */
  EQUAL = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ServerModuleListItem_CheckModuleVersionStatus)
proto3.util.setEnumType(ServerModuleListItem_CheckModuleVersionStatus, "platform.ServerModuleListItem.CheckModuleVersionStatus", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "NOTFOUND" },
  { no: 2, name: "LOWER" },
  { no: 3, name: "GREATER" },
  { no: 4, name: "EQUAL" },
]);

/**
 * @generated from message platform.ServerListResponse
 */
export class ServerListResponse extends Message<ServerListResponse> {
  /**
   * @generated from field: repeated platform.ServerListItem Servers = 1;
   */
  Servers: ServerListItem[] = [];

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Pagination Pagination = 3;
   */
  Pagination?: Pagination;

  constructor(data?: PartialMessage<ServerListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Servers", kind: "message", T: ServerListItem, repeated: true },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
    { no: 3, name: "Pagination", kind: "message", T: Pagination },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerListResponse {
    return new ServerListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerListResponse {
    return new ServerListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerListResponse {
    return new ServerListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ServerListResponse | PlainMessage<ServerListResponse> | undefined, b: ServerListResponse | PlainMessage<ServerListResponse> | undefined): boolean {
    return proto3.util.equals(ServerListResponse, a, b);
  }
}

/**
 * @generated from message platform.CreateServerRequest
 */
export class CreateServerRequest extends Message<CreateServerRequest> {
  /**
   * @generated from field: string ClusterID = 2;
   */
  ClusterID = "";

  constructor(data?: PartialMessage<CreateServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "ClusterID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateServerRequest {
    return new CreateServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateServerRequest {
    return new CreateServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateServerRequest {
    return new CreateServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateServerRequest | PlainMessage<CreateServerRequest> | undefined, b: CreateServerRequest | PlainMessage<CreateServerRequest> | undefined): boolean {
    return proto3.util.equals(CreateServerRequest, a, b);
  }
}

/**
 * @generated from message platform.GetServerRequest
 */
export class GetServerRequest extends Message<GetServerRequest> {
  /**
   * @generated from field: string ServerID = 1;
   */
  ServerID = "";

  constructor(data?: PartialMessage<GetServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerRequest {
    return new GetServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerRequest {
    return new GetServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerRequest {
    return new GetServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerRequest | PlainMessage<GetServerRequest> | undefined, b: GetServerRequest | PlainMessage<GetServerRequest> | undefined): boolean {
    return proto3.util.equals(GetServerRequest, a, b);
  }
}

/**
 * @generated from message platform.GetServerResponse
 */
export class GetServerResponse extends Message<GetServerResponse> {
  /**
   * @generated from field: platform.Server Server = 1;
   */
  Server?: Server;

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Cluster Cluster = 3;
   */
  Cluster?: Cluster;

  /**
   * @generated from field: platform.ClusterStatus ClusterStatus = 4;
   */
  ClusterStatus?: ClusterStatus;

  /**
   * @generated from field: int32 DeploymentsCount = 5;
   */
  DeploymentsCount = 0;

  /**
   * @generated from field: int32 ProjectsCount = 6;
   */
  ProjectsCount = 0;

  /**
   * @generated from field: platform.ServerClusterInfo ServerClusterInfo = 7;
   */
  ServerClusterInfo?: ServerClusterInfo;

  constructor(data?: PartialMessage<GetServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Server", kind: "message", T: Server },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
    { no: 3, name: "Cluster", kind: "message", T: Cluster },
    { no: 4, name: "ClusterStatus", kind: "message", T: ClusterStatus },
    { no: 5, name: "DeploymentsCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "ProjectsCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "ServerClusterInfo", kind: "message", T: ServerClusterInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerResponse {
    return new GetServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerResponse {
    return new GetServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerResponse {
    return new GetServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerResponse | PlainMessage<GetServerResponse> | undefined, b: GetServerResponse | PlainMessage<GetServerResponse> | undefined): boolean {
    return proto3.util.equals(GetServerResponse, a, b);
  }
}

/**
 * @generated from message platform.ServerClusterInfo
 */
export class ServerClusterInfo extends Message<ServerClusterInfo> {
  constructor(data?: PartialMessage<ServerClusterInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ServerClusterInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerClusterInfo {
    return new ServerClusterInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerClusterInfo {
    return new ServerClusterInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerClusterInfo {
    return new ServerClusterInfo().fromJsonString(jsonString, options);
  }

  static equals(a: ServerClusterInfo | PlainMessage<ServerClusterInfo> | undefined, b: ServerClusterInfo | PlainMessage<ServerClusterInfo> | undefined): boolean {
    return proto3.util.equals(ServerClusterInfo, a, b);
  }
}

/**
 * @generated from message platform.ClusterGetResponse
 */
export class ClusterGetResponse extends Message<ClusterGetResponse> {
  /**
   * @generated from field: platform.Cluster Cluster = 1;
   */
  Cluster?: Cluster;

  /**
   * @generated from field: platform.Server Server = 2;
   */
  Server?: Server;

  /**
   * @generated from field: platform.ClusterStatus Status = 3;
   */
  Status?: ClusterStatus;

  /**
   * @generated from field: platform.Workspace Workspace = 4;
   */
  Workspace?: Workspace;

  /**
   * @generated from field: platform.ClusterInfo Info = 5;
   */
  Info?: ClusterInfo;

  /**
   * @generated from field: platform.ClusterWorkspaceUsage Usage = 6;
   */
  Usage?: ClusterWorkspaceUsage;

  /**
   * @generated from field: platform.AccessItem ClusterAccess = 7;
   */
  ClusterAccess?: AccessItem;

  /**
   * @generated from field: platform.AccessItem ServerAccess = 8;
   */
  ServerAccess?: AccessItem;

  /**
   * @generated from field: platform.Configuration KubeConfigForm = 9;
   */
  KubeConfigForm?: Configuration;

  /**
   * @generated from field: platform.Configuration RenameForm = 10;
   */
  RenameForm?: Configuration;

  /**
   * @generated from field: platform.Configuration HttpSettingsForm = 11;
   */
  HttpSettingsForm?: Configuration;

  /**
   * @generated from field: platform.Configuration ResourcesForm = 12;
   */
  ResourcesForm?: Configuration;

  /**
   * @generated from field: platform.Configuration PublishForm = 13;
   */
  PublishForm?: Configuration;

  constructor(data?: PartialMessage<ClusterGetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterGetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Cluster", kind: "message", T: Cluster },
    { no: 2, name: "Server", kind: "message", T: Server },
    { no: 3, name: "Status", kind: "message", T: ClusterStatus },
    { no: 4, name: "Workspace", kind: "message", T: Workspace },
    { no: 5, name: "Info", kind: "message", T: ClusterInfo },
    { no: 6, name: "Usage", kind: "message", T: ClusterWorkspaceUsage },
    { no: 7, name: "ClusterAccess", kind: "message", T: AccessItem },
    { no: 8, name: "ServerAccess", kind: "message", T: AccessItem },
    { no: 9, name: "KubeConfigForm", kind: "message", T: Configuration },
    { no: 10, name: "RenameForm", kind: "message", T: Configuration },
    { no: 11, name: "HttpSettingsForm", kind: "message", T: Configuration },
    { no: 12, name: "ResourcesForm", kind: "message", T: Configuration },
    { no: 13, name: "PublishForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterGetResponse {
    return new ClusterGetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterGetResponse {
    return new ClusterGetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterGetResponse {
    return new ClusterGetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterGetResponse | PlainMessage<ClusterGetResponse> | undefined, b: ClusterGetResponse | PlainMessage<ClusterGetResponse> | undefined): boolean {
    return proto3.util.equals(ClusterGetResponse, a, b);
  }
}

/**
 * @generated from message platform.DeleteServerRequest
 */
export class DeleteServerRequest extends Message<DeleteServerRequest> {
  /**
   * @generated from field: string ID = 2;
   */
  ID = "";

  constructor(data?: PartialMessage<DeleteServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeleteServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteServerRequest {
    return new DeleteServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteServerRequest {
    return new DeleteServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteServerRequest {
    return new DeleteServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteServerRequest | PlainMessage<DeleteServerRequest> | undefined, b: DeleteServerRequest | PlainMessage<DeleteServerRequest> | undefined): boolean {
    return proto3.util.equals(DeleteServerRequest, a, b);
  }
}

/**
 * @generated from message platform.UpdateClusterSettingsRequest
 */
export class UpdateClusterSettingsRequest extends Message<UpdateClusterSettingsRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: platform.Configuration ConfigurationForm = 2;
   */
  ConfigurationForm?: Configuration;

  constructor(data?: PartialMessage<UpdateClusterSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.UpdateClusterSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ConfigurationForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateClusterSettingsRequest {
    return new UpdateClusterSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateClusterSettingsRequest {
    return new UpdateClusterSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateClusterSettingsRequest {
    return new UpdateClusterSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateClusterSettingsRequest | PlainMessage<UpdateClusterSettingsRequest> | undefined, b: UpdateClusterSettingsRequest | PlainMessage<UpdateClusterSettingsRequest> | undefined): boolean {
    return proto3.util.equals(UpdateClusterSettingsRequest, a, b);
  }
}

/**
 * @generated from message platform.ShareClusterRequest
 */
export class ShareClusterRequest extends Message<ShareClusterRequest> {
  /**
   * @generated from field: string ClusterUUID = 1;
   */
  ClusterUUID = "";

  /**
   * Slug of the workspace to grant access to. Must match an existing
   * workspace; the grant is rejected when the slug doesn't resolve.
   *
   * @generated from field: string WorkspaceSlug = 2;
   */
  WorkspaceSlug = "";

  constructor(data?: PartialMessage<ShareClusterRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ShareClusterRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ClusterUUID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "WorkspaceSlug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ShareClusterRequest {
    return new ShareClusterRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ShareClusterRequest {
    return new ShareClusterRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ShareClusterRequest {
    return new ShareClusterRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ShareClusterRequest | PlainMessage<ShareClusterRequest> | undefined, b: ShareClusterRequest | PlainMessage<ShareClusterRequest> | undefined): boolean {
    return proto3.util.equals(ShareClusterRequest, a, b);
  }
}

/**
 * @generated from message platform.UnshareClusterRequest
 */
export class UnshareClusterRequest extends Message<UnshareClusterRequest> {
  /**
   * @generated from field: string ClusterUUID = 1;
   */
  ClusterUUID = "";

  /**
   * @generated from field: string WorkspaceSlug = 2;
   */
  WorkspaceSlug = "";

  constructor(data?: PartialMessage<UnshareClusterRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.UnshareClusterRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ClusterUUID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "WorkspaceSlug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnshareClusterRequest {
    return new UnshareClusterRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnshareClusterRequest {
    return new UnshareClusterRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnshareClusterRequest {
    return new UnshareClusterRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnshareClusterRequest | PlainMessage<UnshareClusterRequest> | undefined, b: UnshareClusterRequest | PlainMessage<UnshareClusterRequest> | undefined): boolean {
    return proto3.util.equals(UnshareClusterRequest, a, b);
  }
}

/**
 * @generated from message platform.ListClusterSharesRequest
 */
export class ListClusterSharesRequest extends Message<ListClusterSharesRequest> {
  /**
   * @generated from field: string ClusterUUID = 1;
   */
  ClusterUUID = "";

  constructor(data?: PartialMessage<ListClusterSharesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListClusterSharesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ClusterUUID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListClusterSharesRequest {
    return new ListClusterSharesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListClusterSharesRequest {
    return new ListClusterSharesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListClusterSharesRequest {
    return new ListClusterSharesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListClusterSharesRequest | PlainMessage<ListClusterSharesRequest> | undefined, b: ListClusterSharesRequest | PlainMessage<ListClusterSharesRequest> | undefined): boolean {
    return proto3.util.equals(ListClusterSharesRequest, a, b);
  }
}

/**
 * @generated from message platform.ListClusterSharesResponse
 */
export class ListClusterSharesResponse extends Message<ListClusterSharesResponse> {
  /**
   * @generated from field: repeated platform.ClusterShare Shares = 1;
   */
  Shares: ClusterShare[] = [];

  constructor(data?: PartialMessage<ListClusterSharesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListClusterSharesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Shares", kind: "message", T: ClusterShare, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListClusterSharesResponse {
    return new ListClusterSharesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListClusterSharesResponse {
    return new ListClusterSharesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListClusterSharesResponse {
    return new ListClusterSharesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListClusterSharesResponse | PlainMessage<ListClusterSharesResponse> | undefined, b: ListClusterSharesResponse | PlainMessage<ListClusterSharesResponse> | undefined): boolean {
    return proto3.util.equals(ListClusterSharesResponse, a, b);
  }
}

/**
 * @generated from message platform.ClusterShare
 */
export class ClusterShare extends Message<ClusterShare> {
  /**
   * @generated from field: string WorkspaceSlug = 1;
   */
  WorkspaceSlug = "";

  /**
   * @generated from field: string WorkspaceName = 2;
   */
  WorkspaceName = "";

  /**
   * @generated from field: string CreatedAt = 3;
   */
  CreatedAt = "";

  constructor(data?: PartialMessage<ClusterShare>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ClusterShare";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "WorkspaceSlug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "WorkspaceName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "CreatedAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterShare {
    return new ClusterShare().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterShare {
    return new ClusterShare().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterShare {
    return new ClusterShare().fromJsonString(jsonString, options);
  }

  static equals(a: ClusterShare | PlainMessage<ClusterShare> | undefined, b: ClusterShare | PlainMessage<ClusterShare> | undefined): boolean {
    return proto3.util.equals(ClusterShare, a, b);
  }
}

