// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file deployment.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Deployment } from "./deployment_pb.js";
import { Module, ModuleVersion } from "./module_pb.js";
import { Server } from "./server_pb.js";
import { Chart, Release } from "./release_pb.js";
import { Cluster } from "./cluster_pb.js";
import { AccessItem } from "./access-item_pb.js";
import { MessageType } from "./message_pb.js";
import { Pagination, PaginationRequest } from "./pagination_pb.js";

/**
 * @generated from message platform.GetDeploymentRequest
 */
export class GetDeploymentRequest extends Message<GetDeploymentRequest> {
  /**
   * @generated from field: string DeploymentID = 1;
   */
  DeploymentID = "";

  constructor(data?: PartialMessage<GetDeploymentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetDeploymentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeploymentID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDeploymentRequest {
    return new GetDeploymentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDeploymentRequest {
    return new GetDeploymentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDeploymentRequest {
    return new GetDeploymentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetDeploymentRequest | PlainMessage<GetDeploymentRequest> | undefined, b: GetDeploymentRequest | PlainMessage<GetDeploymentRequest> | undefined): boolean {
    return proto3.util.equals(GetDeploymentRequest, a, b);
  }
}

/**
 * @generated from message platform.GetDeploymentResponse
 */
export class GetDeploymentResponse extends Message<GetDeploymentResponse> {
  /**
   * @generated from field: platform.Deployment Deployment = 1;
   */
  Deployment?: Deployment;

  /**
   * @generated from field: platform.ModuleVersion Version = 2;
   */
  Version?: ModuleVersion;

  /**
   * @generated from field: platform.Module Module = 3;
   */
  Module?: Module;

  /**
   * @generated from field: platform.Server Server = 4;
   */
  Server?: Server;

  /**
   * @generated from field: platform.Release Release = 5;
   */
  Release?: Release;

  /**
   * @generated from field: platform.Chart Chart = 6;
   */
  Chart?: Chart;

  /**
   * @generated from field: platform.Cluster Cluster = 8;
   */
  Cluster?: Cluster;

  /**
   * @generated from field: platform.AccessItem Access = 9;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<GetDeploymentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetDeploymentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Deployment", kind: "message", T: Deployment },
    { no: 2, name: "Version", kind: "message", T: ModuleVersion },
    { no: 3, name: "Module", kind: "message", T: Module },
    { no: 4, name: "Server", kind: "message", T: Server },
    { no: 5, name: "Release", kind: "message", T: Release },
    { no: 6, name: "Chart", kind: "message", T: Chart },
    { no: 8, name: "Cluster", kind: "message", T: Cluster },
    { no: 9, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDeploymentResponse {
    return new GetDeploymentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDeploymentResponse {
    return new GetDeploymentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDeploymentResponse {
    return new GetDeploymentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetDeploymentResponse | PlainMessage<GetDeploymentResponse> | undefined, b: GetDeploymentResponse | PlainMessage<GetDeploymentResponse> | undefined): boolean {
    return proto3.util.equals(GetDeploymentResponse, a, b);
  }
}

/**
 * @generated from message platform.DeploymentInstallRequest
 */
export class DeploymentInstallRequest extends Message<DeploymentInstallRequest> {
  /**
   * @generated from field: string ServerID = 1;
   */
  ServerID = "";

  /**
   * @generated from field: string ModuleVersionID = 2;
   */
  ModuleVersionID = "";

  constructor(data?: PartialMessage<DeploymentInstallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentInstallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ModuleVersionID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentInstallRequest {
    return new DeploymentInstallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentInstallRequest {
    return new DeploymentInstallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentInstallRequest {
    return new DeploymentInstallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentInstallRequest | PlainMessage<DeploymentInstallRequest> | undefined, b: DeploymentInstallRequest | PlainMessage<DeploymentInstallRequest> | undefined): boolean {
    return proto3.util.equals(DeploymentInstallRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentProcessResponse
 */
export class DeploymentProcessResponse extends Message<DeploymentProcessResponse> {
  /**
   * @generated from field: string Message = 1;
   */
  Message = "";

  /**
   * @generated from field: platform.MessageType Type = 2;
   */
  Type = MessageType.Info;

  constructor(data?: PartialMessage<DeploymentProcessResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentProcessResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "enum", T: proto3.getEnumType(MessageType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentProcessResponse {
    return new DeploymentProcessResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentProcessResponse {
    return new DeploymentProcessResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentProcessResponse {
    return new DeploymentProcessResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentProcessResponse | PlainMessage<DeploymentProcessResponse> | undefined, b: DeploymentProcessResponse | PlainMessage<DeploymentProcessResponse> | undefined): boolean {
    return proto3.util.equals(DeploymentProcessResponse, a, b);
  }
}

/**
 * @generated from message platform.DeploymentListRequest
 */
export class DeploymentListRequest extends Message<DeploymentListRequest> {
  /**
   * @generated from field: string ServerID = 1;
   */
  ServerID = "";

  /**
   * @generated from field: string ModuleID = 2;
   */
  ModuleID = "";

  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 3;
   */
  PaginationRequest?: PaginationRequest;

  constructor(data?: PartialMessage<DeploymentListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ModuleID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "PaginationRequest", kind: "message", T: PaginationRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentListRequest {
    return new DeploymentListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentListRequest {
    return new DeploymentListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentListRequest {
    return new DeploymentListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentListRequest | PlainMessage<DeploymentListRequest> | undefined, b: DeploymentListRequest | PlainMessage<DeploymentListRequest> | undefined): boolean {
    return proto3.util.equals(DeploymentListRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentListResponse
 */
export class DeploymentListResponse extends Message<DeploymentListResponse> {
  /**
   * @generated from field: repeated platform.DeploymentListItem Deployments = 1;
   */
  Deployments: DeploymentListItem[] = [];

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Pagination Pagination = 3;
   */
  Pagination?: Pagination;

  constructor(data?: PartialMessage<DeploymentListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Deployments", kind: "message", T: DeploymentListItem, repeated: true },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
    { no: 3, name: "Pagination", kind: "message", T: Pagination },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentListResponse {
    return new DeploymentListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentListResponse {
    return new DeploymentListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentListResponse {
    return new DeploymentListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentListResponse | PlainMessage<DeploymentListResponse> | undefined, b: DeploymentListResponse | PlainMessage<DeploymentListResponse> | undefined): boolean {
    return proto3.util.equals(DeploymentListResponse, a, b);
  }
}

/**
 * @generated from message platform.DeploymentListItem
 */
export class DeploymentListItem extends Message<DeploymentListItem> {
  /**
   * @generated from field: platform.Deployment Deployment = 1;
   */
  Deployment?: Deployment;

  /**
   * @generated from field: platform.ModuleVersion Version = 2;
   */
  Version?: ModuleVersion;

  /**
   * @generated from field: platform.Module Module = 3;
   */
  Module?: Module;

  /**
   * @generated from field: platform.Server Server = 4;
   */
  Server?: Server;

  /**
   * @generated from field: platform.Cluster Cluster = 5;
   */
  Cluster?: Cluster;

  /**
   * @generated from field: platform.AccessItem Access = 6;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<DeploymentListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Deployment", kind: "message", T: Deployment },
    { no: 2, name: "Version", kind: "message", T: ModuleVersion },
    { no: 3, name: "Module", kind: "message", T: Module },
    { no: 4, name: "Server", kind: "message", T: Server },
    { no: 5, name: "Cluster", kind: "message", T: Cluster },
    { no: 6, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentListItem {
    return new DeploymentListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentListItem {
    return new DeploymentListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentListItem {
    return new DeploymentListItem().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentListItem | PlainMessage<DeploymentListItem> | undefined, b: DeploymentListItem | PlainMessage<DeploymentListItem> | undefined): boolean {
    return proto3.util.equals(DeploymentListItem, a, b);
  }
}

/**
 * @generated from message platform.DeploymentUninstallRequest
 */
export class DeploymentUninstallRequest extends Message<DeploymentUninstallRequest> {
  /**
   * @generated from field: string ServerID = 1;
   */
  ServerID = "";

  /**
   * @generated from field: string ReleaseName = 2;
   */
  ReleaseName = "";

  constructor(data?: PartialMessage<DeploymentUninstallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentUninstallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ReleaseName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentUninstallRequest {
    return new DeploymentUninstallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentUninstallRequest {
    return new DeploymentUninstallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentUninstallRequest {
    return new DeploymentUninstallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentUninstallRequest | PlainMessage<DeploymentUninstallRequest> | undefined, b: DeploymentUninstallRequest | PlainMessage<DeploymentUninstallRequest> | undefined): boolean {
    return proto3.util.equals(DeploymentUninstallRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentScaleRequest
 */
export class DeploymentScaleRequest extends Message<DeploymentScaleRequest> {
  /**
   * UUID of deployment
   *
   * @generated from field: string DeploymentID = 1;
   */
  DeploymentID = "";

  /**
   * Target replica count (1-100)
   *
   * @generated from field: int32 Replicas = 2;
   */
  Replicas = 0;

  constructor(data?: PartialMessage<DeploymentScaleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentScaleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeploymentID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Replicas", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentScaleRequest {
    return new DeploymentScaleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentScaleRequest {
    return new DeploymentScaleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentScaleRequest {
    return new DeploymentScaleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentScaleRequest | PlainMessage<DeploymentScaleRequest> | undefined, b: DeploymentScaleRequest | PlainMessage<DeploymentScaleRequest> | undefined): boolean {
    return proto3.util.equals(DeploymentScaleRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentScaleResponse
 */
export class DeploymentScaleResponse extends Message<DeploymentScaleResponse> {
  /**
   * Background job ID
   *
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  constructor(data?: PartialMessage<DeploymentScaleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentScaleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentScaleResponse {
    return new DeploymentScaleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentScaleResponse {
    return new DeploymentScaleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentScaleResponse {
    return new DeploymentScaleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentScaleResponse | PlainMessage<DeploymentScaleResponse> | undefined, b: DeploymentScaleResponse | PlainMessage<DeploymentScaleResponse> | undefined): boolean {
    return proto3.util.equals(DeploymentScaleResponse, a, b);
  }
}

/**
 * @generated from message platform.DeploymentRestartRequest
 */
export class DeploymentRestartRequest extends Message<DeploymentRestartRequest> {
  /**
   * UUID of deployment
   *
   * @generated from field: string DeploymentID = 1;
   */
  DeploymentID = "";

  constructor(data?: PartialMessage<DeploymentRestartRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentRestartRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeploymentID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentRestartRequest {
    return new DeploymentRestartRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentRestartRequest {
    return new DeploymentRestartRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentRestartRequest {
    return new DeploymentRestartRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentRestartRequest | PlainMessage<DeploymentRestartRequest> | undefined, b: DeploymentRestartRequest | PlainMessage<DeploymentRestartRequest> | undefined): boolean {
    return proto3.util.equals(DeploymentRestartRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentUpdateResourcesRequest
 */
export class DeploymentUpdateResourcesRequest extends Message<DeploymentUpdateResourcesRequest> {
  /**
   * UUID of deployment
   *
   * @generated from field: string DeploymentID = 1;
   */
  DeploymentID = "";

  /**
   * millicores (e.g., 50 = 50m, 1000 = 1 core)
   *
   * @generated from field: int64 CPURequest = 2;
   */
  CPURequest = protoInt64.zero;

  /**
   * bytes
   *
   * @generated from field: int64 MemoryRequest = 3;
   */
  MemoryRequest = protoInt64.zero;

  /**
   * millicores
   *
   * @generated from field: int64 CPULimit = 4;
   */
  CPULimit = protoInt64.zero;

  /**
   * bytes
   *
   * @generated from field: int64 MemoryLimit = 5;
   */
  MemoryLimit = protoInt64.zero;

  constructor(data?: PartialMessage<DeploymentUpdateResourcesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentUpdateResourcesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeploymentID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "CPURequest", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "MemoryRequest", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "CPULimit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "MemoryLimit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentUpdateResourcesRequest {
    return new DeploymentUpdateResourcesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentUpdateResourcesRequest {
    return new DeploymentUpdateResourcesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentUpdateResourcesRequest {
    return new DeploymentUpdateResourcesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentUpdateResourcesRequest | PlainMessage<DeploymentUpdateResourcesRequest> | undefined, b: DeploymentUpdateResourcesRequest | PlainMessage<DeploymentUpdateResourcesRequest> | undefined): boolean {
    return proto3.util.equals(DeploymentUpdateResourcesRequest, a, b);
  }
}

/**
 * @generated from message platform.DeploymentUpdateResourcesResponse
 */
export class DeploymentUpdateResourcesResponse extends Message<DeploymentUpdateResourcesResponse> {
  /**
   * Background job ID
   *
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  constructor(data?: PartialMessage<DeploymentUpdateResourcesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentUpdateResourcesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentUpdateResourcesResponse {
    return new DeploymentUpdateResourcesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentUpdateResourcesResponse {
    return new DeploymentUpdateResourcesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentUpdateResourcesResponse {
    return new DeploymentUpdateResourcesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentUpdateResourcesResponse | PlainMessage<DeploymentUpdateResourcesResponse> | undefined, b: DeploymentUpdateResourcesResponse | PlainMessage<DeploymentUpdateResourcesResponse> | undefined): boolean {
    return proto3.util.equals(DeploymentUpdateResourcesResponse, a, b);
  }
}

/**
 * Install response (changed from streaming to unary)
 *
 * @generated from message platform.DeploymentInstallResponse
 */
export class DeploymentInstallResponse extends Message<DeploymentInstallResponse> {
  /**
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  constructor(data?: PartialMessage<DeploymentInstallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentInstallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentInstallResponse {
    return new DeploymentInstallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentInstallResponse {
    return new DeploymentInstallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentInstallResponse {
    return new DeploymentInstallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentInstallResponse | PlainMessage<DeploymentInstallResponse> | undefined, b: DeploymentInstallResponse | PlainMessage<DeploymentInstallResponse> | undefined): boolean {
    return proto3.util.equals(DeploymentInstallResponse, a, b);
  }
}

/**
 * Bulk install
 *
 * @generated from message platform.BulkInstallRequest
 */
export class BulkInstallRequest extends Message<BulkInstallRequest> {
  /**
   * @generated from field: string ServerID = 1;
   */
  ServerID = "";

  /**
   * @generated from field: repeated string ModuleVersionIDs = 2;
   */
  ModuleVersionIDs: string[] = [];

  constructor(data?: PartialMessage<BulkInstallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.BulkInstallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ModuleVersionIDs", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BulkInstallRequest {
    return new BulkInstallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BulkInstallRequest {
    return new BulkInstallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BulkInstallRequest {
    return new BulkInstallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BulkInstallRequest | PlainMessage<BulkInstallRequest> | undefined, b: BulkInstallRequest | PlainMessage<BulkInstallRequest> | undefined): boolean {
    return proto3.util.equals(BulkInstallRequest, a, b);
  }
}

/**
 * @generated from message platform.BulkInstallResponse
 */
export class BulkInstallResponse extends Message<BulkInstallResponse> {
  /**
   * @generated from field: repeated platform.BulkInstallItem Jobs = 1;
   */
  Jobs: BulkInstallItem[] = [];

  constructor(data?: PartialMessage<BulkInstallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.BulkInstallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Jobs", kind: "message", T: BulkInstallItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BulkInstallResponse {
    return new BulkInstallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BulkInstallResponse {
    return new BulkInstallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BulkInstallResponse {
    return new BulkInstallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BulkInstallResponse | PlainMessage<BulkInstallResponse> | undefined, b: BulkInstallResponse | PlainMessage<BulkInstallResponse> | undefined): boolean {
    return proto3.util.equals(BulkInstallResponse, a, b);
  }
}

/**
 * @generated from message platform.BulkInstallItem
 */
export class BulkInstallItem extends Message<BulkInstallItem> {
  /**
   * @generated from field: string ModuleVersionID = 1;
   */
  ModuleVersionID = "";

  /**
   * @generated from field: string JobID = 2;
   */
  JobID = "";

  /**
   * Error message if job creation failed
   *
   * @generated from field: string Error = 3;
   */
  Error = "";

  constructor(data?: PartialMessage<BulkInstallItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.BulkInstallItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ModuleVersionID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BulkInstallItem {
    return new BulkInstallItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BulkInstallItem {
    return new BulkInstallItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BulkInstallItem {
    return new BulkInstallItem().fromJsonString(jsonString, options);
  }

  static equals(a: BulkInstallItem | PlainMessage<BulkInstallItem> | undefined, b: BulkInstallItem | PlainMessage<BulkInstallItem> | undefined): boolean {
    return proto3.util.equals(BulkInstallItem, a, b);
  }
}

/**
 * Job management
 *
 * @generated from message platform.ListJobsRequest
 */
export class ListJobsRequest extends Message<ListJobsRequest> {
  /**
   * Filter by job types
   *
   * @generated from field: repeated string Types = 1;
   */
  Types: string[] = [];

  /**
   * Filter by status
   *
   * @generated from field: repeated string Status = 2;
   */
  Status: string[] = [];

  /**
   * @generated from field: int32 Limit = 3;
   */
  Limit = 0;

  /**
   * @generated from field: int32 Offset = 4;
   */
  Offset = 0;

  constructor(data?: PartialMessage<ListJobsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListJobsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "Limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "Offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListJobsRequest {
    return new ListJobsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListJobsRequest {
    return new ListJobsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListJobsRequest {
    return new ListJobsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListJobsRequest | PlainMessage<ListJobsRequest> | undefined, b: ListJobsRequest | PlainMessage<ListJobsRequest> | undefined): boolean {
    return proto3.util.equals(ListJobsRequest, a, b);
  }
}

/**
 * @generated from message platform.ListJobsResponse
 */
export class ListJobsResponse extends Message<ListJobsResponse> {
  /**
   * @generated from field: repeated platform.Job Jobs = 1;
   */
  Jobs: Job[] = [];

  /**
   * @generated from field: int32 Total = 2;
   */
  Total = 0;

  constructor(data?: PartialMessage<ListJobsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListJobsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Jobs", kind: "message", T: Job, repeated: true },
    { no: 2, name: "Total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListJobsResponse {
    return new ListJobsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListJobsResponse {
    return new ListJobsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListJobsResponse {
    return new ListJobsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListJobsResponse | PlainMessage<ListJobsResponse> | undefined, b: ListJobsResponse | PlainMessage<ListJobsResponse> | undefined): boolean {
    return proto3.util.equals(ListJobsResponse, a, b);
  }
}

/**
 * @generated from message platform.GetJobRequest
 */
export class GetJobRequest extends Message<GetJobRequest> {
  /**
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  constructor(data?: PartialMessage<GetJobRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetJobRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJobRequest {
    return new GetJobRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJobRequest {
    return new GetJobRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJobRequest {
    return new GetJobRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetJobRequest | PlainMessage<GetJobRequest> | undefined, b: GetJobRequest | PlainMessage<GetJobRequest> | undefined): boolean {
    return proto3.util.equals(GetJobRequest, a, b);
  }
}

/**
 * @generated from message platform.GetJobResponse
 */
export class GetJobResponse extends Message<GetJobResponse> {
  /**
   * @generated from field: platform.Job Job = 1;
   */
  Job?: Job;

  constructor(data?: PartialMessage<GetJobResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetJobResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Job", kind: "message", T: Job },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJobResponse {
    return new GetJobResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJobResponse {
    return new GetJobResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJobResponse {
    return new GetJobResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetJobResponse | PlainMessage<GetJobResponse> | undefined, b: GetJobResponse | PlainMessage<GetJobResponse> | undefined): boolean {
    return proto3.util.equals(GetJobResponse, a, b);
  }
}

/**
 * @generated from message platform.Job
 */
export class Job extends Message<Job> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Type = 2;
   */
  Type = "";

  /**
   * @generated from field: string Status = 3;
   */
  Status = "";

  /**
   * @generated from field: int64 CreatedAt = 4;
   */
  CreatedAt = protoInt64.zero;

  /**
   * @generated from field: int64 UpdatedAt = 5;
   */
  UpdatedAt = protoInt64.zero;

  /**
   * @generated from field: int64 CompletedAt = 6;
   */
  CompletedAt = protoInt64.zero;

  /**
   * @generated from field: map<string, string> Meta = 7;
   */
  Meta: { [key: string]: string } = {};

  /**
   * @generated from field: string Error = 8;
   */
  Error = "";

  constructor(data?: PartialMessage<Job>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Job";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "CreatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "UpdatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "CompletedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "Meta", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 8, name: "Error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Job {
    return new Job().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Job {
    return new Job().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Job {
    return new Job().fromJsonString(jsonString, options);
  }

  static equals(a: Job | PlainMessage<Job> | undefined, b: Job | PlainMessage<Job> | undefined): boolean {
    return proto3.util.equals(Job, a, b);
  }
}

/**
 * @generated from message platform.GetJobLogsRequest
 */
export class GetJobLogsRequest extends Message<GetJobLogsRequest> {
  /**
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  /**
   * Filter: "info", "warning", "error", "success"
   *
   * @generated from field: repeated string Types = 2;
   */
  Types: string[] = [];

  /**
   * @generated from field: int32 Limit = 3;
   */
  Limit = 0;

  /**
   * @generated from field: int32 Offset = 4;
   */
  Offset = 0;

  constructor(data?: PartialMessage<GetJobLogsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetJobLogsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "Limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "Offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJobLogsRequest {
    return new GetJobLogsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJobLogsRequest {
    return new GetJobLogsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJobLogsRequest {
    return new GetJobLogsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetJobLogsRequest | PlainMessage<GetJobLogsRequest> | undefined, b: GetJobLogsRequest | PlainMessage<GetJobLogsRequest> | undefined): boolean {
    return proto3.util.equals(GetJobLogsRequest, a, b);
  }
}

/**
 * @generated from message platform.GetJobLogsResponse
 */
export class GetJobLogsResponse extends Message<GetJobLogsResponse> {
  /**
   * @generated from field: repeated platform.JobLogEntry Logs = 1;
   */
  Logs: JobLogEntry[] = [];

  /**
   * @generated from field: int32 Total = 2;
   */
  Total = 0;

  constructor(data?: PartialMessage<GetJobLogsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetJobLogsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Logs", kind: "message", T: JobLogEntry, repeated: true },
    { no: 2, name: "Total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetJobLogsResponse {
    return new GetJobLogsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetJobLogsResponse {
    return new GetJobLogsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetJobLogsResponse {
    return new GetJobLogsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetJobLogsResponse | PlainMessage<GetJobLogsResponse> | undefined, b: GetJobLogsResponse | PlainMessage<GetJobLogsResponse> | undefined): boolean {
    return proto3.util.equals(GetJobLogsResponse, a, b);
  }
}

/**
 * @generated from message platform.JobLogEntry
 */
export class JobLogEntry extends Message<JobLogEntry> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: int64 Timestamp = 2;
   */
  Timestamp = protoInt64.zero;

  /**
   * @generated from field: string Type = 3;
   */
  Type = "";

  /**
   * @generated from field: string Message = 4;
   */
  Message = "";

  constructor(data?: PartialMessage<JobLogEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.JobLogEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "Type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JobLogEntry {
    return new JobLogEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JobLogEntry {
    return new JobLogEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JobLogEntry {
    return new JobLogEntry().fromJsonString(jsonString, options);
  }

  static equals(a: JobLogEntry | PlainMessage<JobLogEntry> | undefined, b: JobLogEntry | PlainMessage<JobLogEntry> | undefined): boolean {
    return proto3.util.equals(JobLogEntry, a, b);
  }
}

/**
 * Streaming job updates
 *
 * Empty - subscribes to all workspace job updates
 *
 * @generated from message platform.StreamJobUpdatesRequest
 */
export class StreamJobUpdatesRequest extends Message<StreamJobUpdatesRequest> {
  constructor(data?: PartialMessage<StreamJobUpdatesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StreamJobUpdatesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamJobUpdatesRequest {
    return new StreamJobUpdatesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamJobUpdatesRequest {
    return new StreamJobUpdatesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamJobUpdatesRequest {
    return new StreamJobUpdatesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamJobUpdatesRequest | PlainMessage<StreamJobUpdatesRequest> | undefined, b: StreamJobUpdatesRequest | PlainMessage<StreamJobUpdatesRequest> | undefined): boolean {
    return proto3.util.equals(StreamJobUpdatesRequest, a, b);
  }
}

/**
 * @generated from message platform.JobUpdate
 */
export class JobUpdate extends Message<JobUpdate> {
  /**
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  /**
   * "created", "status_changed", "log_added", "completed"
   *
   * @generated from field: string UpdateType = 2;
   */
  UpdateType = "";

  /**
   * Full job info (for created/status_changed/completed)
   *
   * @generated from field: platform.Job Job = 3;
   */
  Job?: Job;

  /**
   * Log entry (for log_added)
   *
   * @generated from field: platform.JobLogEntry Log = 4;
   */
  Log?: JobLogEntry;

  constructor(data?: PartialMessage<JobUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.JobUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "UpdateType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Job", kind: "message", T: Job },
    { no: 4, name: "Log", kind: "message", T: JobLogEntry },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JobUpdate {
    return new JobUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JobUpdate {
    return new JobUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JobUpdate {
    return new JobUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: JobUpdate | PlainMessage<JobUpdate> | undefined, b: JobUpdate | PlainMessage<JobUpdate> | undefined): boolean {
    return proto3.util.equals(JobUpdate, a, b);
  }
}

/**
 * @generated from message platform.CancelJobRequest
 */
export class CancelJobRequest extends Message<CancelJobRequest> {
  /**
   * @generated from field: string JobID = 1;
   */
  JobID = "";

  constructor(data?: PartialMessage<CancelJobRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CancelJobRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "JobID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelJobRequest {
    return new CancelJobRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelJobRequest {
    return new CancelJobRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelJobRequest {
    return new CancelJobRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelJobRequest | PlainMessage<CancelJobRequest> | undefined, b: CancelJobRequest | PlainMessage<CancelJobRequest> | undefined): boolean {
    return proto3.util.equals(CancelJobRequest, a, b);
  }
}

/**
 * @generated from message platform.CancelJobResponse
 */
export class CancelJobResponse extends Message<CancelJobResponse> {
  /**
   * @generated from field: bool Success = 1;
   */
  Success = false;

  constructor(data?: PartialMessage<CancelJobResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CancelJobResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelJobResponse {
    return new CancelJobResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelJobResponse {
    return new CancelJobResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelJobResponse {
    return new CancelJobResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelJobResponse | PlainMessage<CancelJobResponse> | undefined, b: CancelJobResponse | PlainMessage<CancelJobResponse> | undefined): boolean {
    return proto3.util.equals(CancelJobResponse, a, b);
  }
}

