// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file deployment.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Deployment
 */
export class Deployment extends Message<Deployment> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string ReleaseName = 2;
   */
  ReleaseName = "";

  /**
   * @generated from field: google.protobuf.Timestamp UpdatedAt = 3;
   */
  UpdatedAt?: Timestamp;

  /**
   * @generated from field: string ChartVersion = 4;
   */
  ChartVersion = "";

  /**
   * @generated from field: repeated platform.DeploymentPod Pods = 5;
   */
  Pods: DeploymentPod[] = [];

  /**
   * @generated from field: repeated platform.DeploymentEvent Events = 6;
   */
  Events: DeploymentEvent[] = [];

  /**
   * Resource requests and limits
   *
   * @generated from field: int64 MemoryRequest = 7;
   */
  MemoryRequest = protoInt64.zero;

  /**
   * @generated from field: int64 CPURequest = 8;
   */
  CPURequest = protoInt64.zero;

  /**
   * @generated from field: int64 MemoryLimit = 9;
   */
  MemoryLimit = protoInt64.zero;

  /**
   * @generated from field: int64 CPULimit = 10;
   */
  CPULimit = protoInt64.zero;

  /**
   * Replica count from Kubernetes
   *
   * @generated from field: int32 Replicas = 11;
   */
  Replicas = 0;

  /**
   * Module version string (e.g., "0.1.73")
   *
   * @generated from field: string ModuleVersion = 12;
   */
  ModuleVersion = "";

  /**
   * SDK version used to build this module
   *
   * @generated from field: string SDKVersion = 13;
   */
  SDKVersion = "";

  constructor(data?: PartialMessage<Deployment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Deployment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ReleaseName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "UpdatedAt", kind: "message", T: Timestamp },
    { no: 4, name: "ChartVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Pods", kind: "message", T: DeploymentPod, repeated: true },
    { no: 6, name: "Events", kind: "message", T: DeploymentEvent, repeated: true },
    { no: 7, name: "MemoryRequest", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "CPURequest", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "MemoryLimit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "CPULimit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "Replicas", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "ModuleVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "SDKVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Deployment {
    return new Deployment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Deployment {
    return new Deployment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Deployment {
    return new Deployment().fromJsonString(jsonString, options);
  }

  static equals(a: Deployment | PlainMessage<Deployment> | undefined, b: Deployment | PlainMessage<Deployment> | undefined): boolean {
    return proto3.util.equals(Deployment, a, b);
  }
}

/**
 * @generated from message platform.DeploymentPod
 */
export class DeploymentPod extends Message<DeploymentPod> {
  /**
   * @generated from field: string Name = 1;
   */
  Name = "";

  /**
   * @generated from field: string Status = 2;
   */
  Status = "";

  /**
   * @generated from field: int32 Restarts = 3;
   */
  Restarts = 0;

  /**
   * @generated from field: string Age = 4;
   */
  Age = "";

  constructor(data?: PartialMessage<DeploymentPod>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentPod";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Restarts", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "Age", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentPod {
    return new DeploymentPod().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentPod {
    return new DeploymentPod().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentPod {
    return new DeploymentPod().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentPod | PlainMessage<DeploymentPod> | undefined, b: DeploymentPod | PlainMessage<DeploymentPod> | undefined): boolean {
    return proto3.util.equals(DeploymentPod, a, b);
  }
}

/**
 * @generated from message platform.DeploymentEvent
 */
export class DeploymentEvent extends Message<DeploymentEvent> {
  /**
   * @generated from field: string EventType = 1;
   */
  EventType = "";

  /**
   * @generated from field: string Message = 2;
   */
  Message = "";

  /**
   * @generated from field: string Reason = 3;
   */
  Reason = "";

  /**
   * @generated from field: string Age = 4;
   */
  Age = "";

  constructor(data?: PartialMessage<DeploymentEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeploymentEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "EventType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Age", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentEvent {
    return new DeploymentEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentEvent {
    return new DeploymentEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentEvent {
    return new DeploymentEvent().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentEvent | PlainMessage<DeploymentEvent> | undefined, b: DeploymentEvent | PlainMessage<DeploymentEvent> | undefined): boolean {
    return proto3.util.equals(DeploymentEvent, a, b);
  }
}

