// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file developer.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Pagination, PaginationRequest } from "./pagination_pb.js";

/**
 * @generated from message platform.ListDeveloperKeysRequest
 */
export class ListDeveloperKeysRequest extends Message<ListDeveloperKeysRequest> {
  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 1;
   */
  PaginationRequest?: PaginationRequest;

  constructor(data?: PartialMessage<ListDeveloperKeysRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListDeveloperKeysRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PaginationRequest", kind: "message", T: PaginationRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeveloperKeysRequest {
    return new ListDeveloperKeysRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeveloperKeysRequest {
    return new ListDeveloperKeysRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeveloperKeysRequest {
    return new ListDeveloperKeysRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeveloperKeysRequest | PlainMessage<ListDeveloperKeysRequest> | undefined, b: ListDeveloperKeysRequest | PlainMessage<ListDeveloperKeysRequest> | undefined): boolean {
    return proto3.util.equals(ListDeveloperKeysRequest, a, b);
  }
}

/**
 * @generated from message platform.ListDeveloperKeysResponse
 */
export class ListDeveloperKeysResponse extends Message<ListDeveloperKeysResponse> {
  /**
   * @generated from field: repeated platform.DeveloperKey Keys = 1;
   */
  Keys: DeveloperKey[] = [];

  /**
   * @generated from field: platform.Pagination Pagination = 2;
   */
  Pagination?: Pagination;

  constructor(data?: PartialMessage<ListDeveloperKeysResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListDeveloperKeysResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Keys", kind: "message", T: DeveloperKey, repeated: true },
    { no: 2, name: "Pagination", kind: "message", T: Pagination },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeveloperKeysResponse {
    return new ListDeveloperKeysResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeveloperKeysResponse {
    return new ListDeveloperKeysResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeveloperKeysResponse {
    return new ListDeveloperKeysResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeveloperKeysResponse | PlainMessage<ListDeveloperKeysResponse> | undefined, b: ListDeveloperKeysResponse | PlainMessage<ListDeveloperKeysResponse> | undefined): boolean {
    return proto3.util.equals(ListDeveloperKeysResponse, a, b);
  }
}

/**
 * @generated from message platform.RevokeDeveloperKeyRequest
 */
export class RevokeDeveloperKeyRequest extends Message<RevokeDeveloperKeyRequest> {
  /**
   * @generated from field: string Key = 1;
   */
  Key = "";

  constructor(data?: PartialMessage<RevokeDeveloperKeyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RevokeDeveloperKeyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeDeveloperKeyRequest {
    return new RevokeDeveloperKeyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeDeveloperKeyRequest {
    return new RevokeDeveloperKeyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeDeveloperKeyRequest {
    return new RevokeDeveloperKeyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeDeveloperKeyRequest | PlainMessage<RevokeDeveloperKeyRequest> | undefined, b: RevokeDeveloperKeyRequest | PlainMessage<RevokeDeveloperKeyRequest> | undefined): boolean {
    return proto3.util.equals(RevokeDeveloperKeyRequest, a, b);
  }
}

/**
 * @generated from message platform.CreateDeveloperKeyRequest
 */
export class CreateDeveloperKeyRequest extends Message<CreateDeveloperKeyRequest> {
  /**
   * @generated from field: string Comment = 1;
   */
  Comment = "";

  /**
   * @generated from field: bool Personal = 2;
   */
  Personal = false;

  constructor(data?: PartialMessage<CreateDeveloperKeyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateDeveloperKeyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Personal", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateDeveloperKeyRequest {
    return new CreateDeveloperKeyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateDeveloperKeyRequest {
    return new CreateDeveloperKeyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateDeveloperKeyRequest {
    return new CreateDeveloperKeyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateDeveloperKeyRequest | PlainMessage<CreateDeveloperKeyRequest> | undefined, b: CreateDeveloperKeyRequest | PlainMessage<CreateDeveloperKeyRequest> | undefined): boolean {
    return proto3.util.equals(CreateDeveloperKeyRequest, a, b);
  }
}

/**
 * @generated from message platform.CreateDeveloperKeyResponse
 */
export class CreateDeveloperKeyResponse extends Message<CreateDeveloperKeyResponse> {
  /**
   * @generated from field: platform.DeveloperKey DeveloperKey = 1;
   */
  DeveloperKey?: DeveloperKey;

  constructor(data?: PartialMessage<CreateDeveloperKeyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateDeveloperKeyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeveloperKey", kind: "message", T: DeveloperKey },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateDeveloperKeyResponse {
    return new CreateDeveloperKeyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateDeveloperKeyResponse {
    return new CreateDeveloperKeyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateDeveloperKeyResponse {
    return new CreateDeveloperKeyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateDeveloperKeyResponse | PlainMessage<CreateDeveloperKeyResponse> | undefined, b: CreateDeveloperKeyResponse | PlainMessage<CreateDeveloperKeyResponse> | undefined): boolean {
    return proto3.util.equals(CreateDeveloperKeyResponse, a, b);
  }
}

/**
 * @generated from message platform.DeveloperKey
 */
export class DeveloperKey extends Message<DeveloperKey> {
  /**
   * @generated from field: string Key = 1;
   */
  Key = "";

  /**
   * @generated from field: string Comment = 2;
   */
  Comment = "";

  /**
   * @generated from field: google.protobuf.Timestamp CreatedAt = 3;
   */
  CreatedAt?: Timestamp;

  /**
   * @generated from field: int32 UserID = 4;
   */
  UserID = 0;

  /**
   * @generated from field: string UserName = 5;
   */
  UserName = "";

  constructor(data?: PartialMessage<DeveloperKey>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeveloperKey";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "CreatedAt", kind: "message", T: Timestamp },
    { no: 4, name: "UserID", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "UserName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeveloperKey {
    return new DeveloperKey().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeveloperKey {
    return new DeveloperKey().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeveloperKey {
    return new DeveloperKey().fromJsonString(jsonString, options);
  }

  static equals(a: DeveloperKey | PlainMessage<DeveloperKey> | undefined, b: DeveloperKey | PlainMessage<DeveloperKey> | undefined): boolean {
    return proto3.util.equals(DeveloperKey, a, b);
  }
}

/**
 * @generated from message platform.BuildInfoResponse
 */
export class BuildInfoResponse extends Message<BuildInfoResponse> {
  /**
   * @generated from field: string Version = 1;
   */
  Version = "";

  /**
   * @generated from field: string BuildDate = 2;
   */
  BuildDate = "";

  /**
   * @generated from field: string CommitSha = 3;
   */
  CommitSha = "";

  /**
   * @generated from field: string SdkVersion = 4;
   */
  SdkVersion = "";

  constructor(data?: PartialMessage<BuildInfoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.BuildInfoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "BuildDate", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "CommitSha", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "SdkVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BuildInfoResponse {
    return new BuildInfoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BuildInfoResponse {
    return new BuildInfoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BuildInfoResponse {
    return new BuildInfoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BuildInfoResponse | PlainMessage<BuildInfoResponse> | undefined, b: BuildInfoResponse | PlainMessage<BuildInfoResponse> | undefined): boolean {
    return proto3.util.equals(BuildInfoResponse, a, b);
  }
}

