// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file flow.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AcquireFlowLockRequest, AcquireFlowLockResponse, ApplyFlowRevisionRequest, CloseConversationRequest, CloseConversationResponse, CreateFlowRequest, CreateScenarioFromTraceRequest, CreateScenarioFromTraceResponse, DeleteScenarioRequest, ExportFlowRequest, ExportFlowResponse, GetComponentsRequest, GetComponentsResponse, GetConversationRequest, GetConversationResponse, GetFlowExecutionModeRequest, GetFlowExecutionModeResponse, GetFlowListRequest, GetFlowListResponse, GetFlowRequest, GetFlowResponse, GetFlowRevisionsRequest, GetFlowRevisionsResponse, GetFlowSetupRequest, GetFlowSetupResponse, GetFlowStreamRequest, GetFlowStreamResponse, InspectRequest, InspectResponse, ListConversationsRequest, ListConversationsResponse, ListScenariosRequest, ListScenariosResponse, PreviewEdgeMappingRequest, PreviewEdgeMappingResponse, PromptFlowRequest, PromptFlowResponse, ReleaseFlowLockRequest, RenameFlowRequest, RunActionRequest, RunExpressionRequest, RunExpressionResponse, SaveFlowMetaRequest, SaveFlowRequest, SaveFlowResponse, SetFlowExecutionModeRequest, SubmitFlowSetupRequest, SubmitFlowSetupResponse, TransferNodesRequest, UndeployFlowRequest } from "./flow.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Nil } from "./nil_pb.js";

/**
 * @generated from service platform.FlowService
 */
export const FlowService = {
  typeName: "platform.FlowService",
  methods: {
    /**
     * returns a list of all available components in the system
     *
     * @generated from rpc platform.FlowService.GetComponents
     */
    getComponents: {
      name: "GetComponents",
      I: GetComponentsRequest,
      O: GetComponentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * list of flows
     *
     * @generated from rpc platform.FlowService.GetFlowList
     */
    getFlowList: {
      name: "GetFlowList",
      I: GetFlowListRequest,
      O: GetFlowListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * get detailed flow data
     *
     * @generated from rpc platform.FlowService.GetFlow
     */
    getFlow: {
      name: "GetFlow",
      I: GetFlowRequest,
      O: GetFlowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.GetFlowStream
     */
    getFlowStream: {
      name: "GetFlowStream",
      I: GetFlowStreamRequest,
      O: GetFlowStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc platform.FlowService.SaveFlow
     */
    saveFlow: {
      name: "SaveFlow",
      I: SaveFlowRequest,
      O: SaveFlowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.RenameFlow
     */
    renameFlow: {
      name: "RenameFlow",
      I: RenameFlowRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * creates flow
     *
     * @generated from rpc platform.FlowService.CreateFlow
     */
    createFlow: {
      name: "CreateFlow",
      I: CreateFlowRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * undeploy flow
     *
     * @generated from rpc platform.FlowService.UndeployFlow
     */
    undeployFlow: {
      name: "UndeployFlow",
      I: UndeployFlowRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * discovery data on a node ports
     *
     * @generated from rpc platform.FlowService.InspectNode
     */
    inspectNode: {
      name: "InspectNode",
      I: InspectRequest,
      O: InspectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * run expression
     *
     * @generated from rpc platform.FlowService.RunExpression
     */
    runExpression: {
      name: "RunExpression",
      I: RunExpressionRequest,
      O: RunExpressionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * preview edge mapping
     *
     * @generated from rpc platform.FlowService.PreviewEdgeMapping
     */
    previewEdgeMapping: {
      name: "PreviewEdgeMapping",
      I: PreviewEdgeMappingRequest,
      O: PreviewEdgeMappingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.RunAction
     */
    runAction: {
      name: "RunAction",
      I: RunActionRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.SaveMeta
     */
    saveMeta: {
      name: "SaveMeta",
      I: SaveFlowMetaRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * Toggle durable execution for a flow: writes the execution-mode
     * annotation on the TinyFlow CR and re-stamps the flow's existing nodes
     * so the mode applies immediately.
     *
     * @generated from rpc platform.FlowService.SetFlowExecutionMode
     */
    setFlowExecutionMode: {
      name: "SetFlowExecutionMode",
      I: SetFlowExecutionModeRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * "Needs setup": credential fields (schema format=password) that are still
     * empty across the flow's nodes. Submit stores values as a K8s Secret,
     * writes [[secret:...]] placeholders into node settings, and can start
     * the flow once nothing is missing.
     *
     * @generated from rpc platform.FlowService.GetFlowSetup
     */
    getFlowSetup: {
      name: "GetFlowSetup",
      I: GetFlowSetupRequest,
      O: GetFlowSetupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.SubmitFlowSetup
     */
    submitFlowSetup: {
      name: "SubmitFlowSetup",
      I: SubmitFlowSetupRequest,
      O: SubmitFlowSetupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.GetFlowExecutionMode
     */
    getFlowExecutionMode: {
      name: "GetFlowExecutionMode",
      I: GetFlowExecutionModeRequest,
      O: GetFlowExecutionModeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.TransferNodes
     */
    transferNodes: {
      name: "TransferNodes",
      I: TransferNodesRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.GetFlowRevisions
     */
    getFlowRevisions: {
      name: "GetFlowRevisions",
      I: GetFlowRevisionsRequest,
      O: GetFlowRevisionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.ApplyFlowRevision
     */
    applyFlowRevision: {
      name: "ApplyFlowRevision",
      I: ApplyFlowRevisionRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.Prompt
     */
    prompt: {
      name: "Prompt",
      I: PromptFlowRequest,
      O: PromptFlowResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc platform.FlowService.Export
     */
    export: {
      name: "Export",
      I: ExportFlowRequest,
      O: ExportFlowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Conversation management
     *
     * @generated from rpc platform.FlowService.ListConversations
     */
    listConversations: {
      name: "ListConversations",
      I: ListConversationsRequest,
      O: ListConversationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.GetConversation
     */
    getConversation: {
      name: "GetConversation",
      I: GetConversationRequest,
      O: GetConversationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.CloseConversation
     */
    closeConversation: {
      name: "CloseConversation",
      I: CloseConversationRequest,
      O: CloseConversationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Flow editing locks
     *
     * @generated from rpc platform.FlowService.AcquireFlowLock
     */
    acquireFlowLock: {
      name: "AcquireFlowLock",
      I: AcquireFlowLockRequest,
      O: AcquireFlowLockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.ReleaseFlowLock
     */
    releaseFlowLock: {
      name: "ReleaseFlowLock",
      I: ReleaseFlowLockRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.GetFlowLockInfo
     */
    getFlowLockInfo: {
      name: "GetFlowLockInfo",
      I: AcquireFlowLockRequest,
      O: AcquireFlowLockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Scenarios — stored per-port sample data for edge validation
     *
     * @generated from rpc platform.FlowService.ListScenarios
     */
    listScenarios: {
      name: "ListScenarios",
      I: ListScenariosRequest,
      O: ListScenariosResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.CreateScenarioFromTrace
     */
    createScenarioFromTrace: {
      name: "CreateScenarioFromTrace",
      I: CreateScenarioFromTraceRequest,
      O: CreateScenarioFromTraceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.FlowService.DeleteScenario
     */
    deleteScenario: {
      name: "DeleteScenario",
      I: DeleteScenarioRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
  }
} as const;

