// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file flow.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Struct } from "@bufbuild/protobuf";
import { AccessItem } from "./access-item_pb.js";

/**
 * @generated from message platform.Flow
 */
export class Flow extends Message<Flow> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * for the frontend only (graph representation of all elements)
   *
   * @generated from field: int64 CreatedAt = 7;
   */
  CreatedAt = protoInt64.zero;

  /**
   * @generated from field: int64 Revision = 8;
   */
  Revision = protoInt64.zero;

  /**
   * @generated from field: int64 UpdatedAt = 9;
   */
  UpdatedAt = protoInt64.zero;

  /**
   * tmp
   *
   * @generated from field: string WorkspaceID = 11;
   */
  WorkspaceID = "";

  /**
   * @generated from field: string RevisionComment = 12;
   */
  RevisionComment = "";

  /**
   * @generated from field: string ProjectID = 13;
   */
  ProjectID = "";

  /**
   * @generated from field: bytes Graph = 14;
   */
  Graph = new Uint8Array(0);

  /**
   * @generated from field: google.protobuf.Struct Meta = 15;
   */
  Meta?: Struct;

  /**
   * @generated from field: int64 RevisionCreatedAt = 16;
   */
  RevisionCreatedAt = protoInt64.zero;

  /**
   * @generated from field: string ResourceName = 17;
   */
  ResourceName = "";

  constructor(data?: PartialMessage<Flow>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Flow";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "CreatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "Revision", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "UpdatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "WorkspaceID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "RevisionComment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "ProjectID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "Graph", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 15, name: "Meta", kind: "message", T: Struct },
    { no: 16, name: "RevisionCreatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 17, name: "ResourceName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Flow {
    return new Flow().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Flow {
    return new Flow().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Flow {
    return new Flow().fromJsonString(jsonString, options);
  }

  static equals(a: Flow | PlainMessage<Flow> | undefined, b: Flow | PlainMessage<Flow> | undefined): boolean {
    return proto3.util.equals(Flow, a, b);
  }
}

/**
 * @generated from message platform.FlowListItem
 */
export class FlowListItem extends Message<FlowListItem> {
  /**
   * @generated from field: platform.Flow Flow = 1;
   */
  Flow?: Flow;

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<FlowListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.FlowListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Flow", kind: "message", T: Flow },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FlowListItem {
    return new FlowListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FlowListItem {
    return new FlowListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FlowListItem {
    return new FlowListItem().fromJsonString(jsonString, options);
  }

  static equals(a: FlowListItem | PlainMessage<FlowListItem> | undefined, b: FlowListItem | PlainMessage<FlowListItem> | undefined): boolean {
    return proto3.util.equals(FlowListItem, a, b);
  }
}

