// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file message.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum platform.MessageType
 */
export enum MessageType {
  /**
   * @generated from enum value: Info = 0;
   */
  Info = 0,

  /**
   * @generated from enum value: Success = 1;
   */
  Success = 1,

  /**
   * @generated from enum value: Warning = 2;
   */
  Warning = 2,

  /**
   * @generated from enum value: Error = 3;
   */
  Error = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(MessageType)
proto3.util.setEnumType(MessageType, "platform.MessageType", [
  { no: 0, name: "Info" },
  { no: 1, name: "Success" },
  { no: 2, name: "Warning" },
  { no: 3, name: "Error" },
]);

