// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file module.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Pagination, PaginationRequest } from "./pagination_pb.js";
import { HelmInstallConfig, Module, ModuleVersion } from "./module_pb.js";
import { Server } from "./server_pb.js";
import { Deployment } from "./deployment_pb.js";
import { AccessItem } from "./access-item_pb.js";
import { Workspace } from "./workspace_pb.js";
import { Configuration } from "./configuration_pb.js";

/**
 * @generated from message platform.ModuleListRequest
 */
export class ModuleListRequest extends Message<ModuleListRequest> {
  /**
   * @generated from field: bool DeployedOnly = 1;
   */
  DeployedOnly = false;

  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 2;
   */
  PaginationRequest?: PaginationRequest;

  /**
   * Filter by server (optional, empty = all servers)
   *
   * @generated from field: string ServerID = 3;
   */
  ServerID = "";

  constructor(data?: PartialMessage<ModuleListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ModuleListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeployedOnly", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "PaginationRequest", kind: "message", T: PaginationRequest },
    { no: 3, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModuleListRequest {
    return new ModuleListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModuleListRequest {
    return new ModuleListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModuleListRequest {
    return new ModuleListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ModuleListRequest | PlainMessage<ModuleListRequest> | undefined, b: ModuleListRequest | PlainMessage<ModuleListRequest> | undefined): boolean {
    return proto3.util.equals(ModuleListRequest, a, b);
  }
}

/**
 * @generated from message platform.ModuleListItem
 */
export class ModuleListItem extends Message<ModuleListItem> {
  /**
   * @generated from field: platform.Module Module = 1;
   */
  Module?: Module;

  /**
   * Optional - installed version on selected server
   *
   * @generated from field: platform.ModuleVersion InstalledVersion = 2;
   */
  InstalledVersion?: ModuleVersion;

  /**
   * server where module installed. Optional
   *
   * @generated from field: platform.Server Server = 3;
   */
  Server?: Server;

  /**
   * module installation object, Optional
   *
   * @generated from field: platform.Deployment Deployment = 4;
   */
  Deployment?: Deployment;

  /**
   * @generated from field: platform.AccessItem Access = 5;
   */
  Access?: AccessItem;

  /**
   * Per-server update status (only set when ServerID is provided)
   *
   * @generated from field: bool UpdateAvailable = 6;
   */
  UpdateAvailable = false;

  constructor(data?: PartialMessage<ModuleListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ModuleListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Module", kind: "message", T: Module },
    { no: 2, name: "InstalledVersion", kind: "message", T: ModuleVersion },
    { no: 3, name: "Server", kind: "message", T: Server },
    { no: 4, name: "Deployment", kind: "message", T: Deployment },
    { no: 5, name: "Access", kind: "message", T: AccessItem },
    { no: 6, name: "UpdateAvailable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModuleListItem {
    return new ModuleListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModuleListItem {
    return new ModuleListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModuleListItem {
    return new ModuleListItem().fromJsonString(jsonString, options);
  }

  static equals(a: ModuleListItem | PlainMessage<ModuleListItem> | undefined, b: ModuleListItem | PlainMessage<ModuleListItem> | undefined): boolean {
    return proto3.util.equals(ModuleListItem, a, b);
  }
}

/**
 * @generated from message platform.ModuleListResponse
 */
export class ModuleListResponse extends Message<ModuleListResponse> {
  /**
   * @generated from field: repeated platform.ModuleListItem Modules = 1;
   */
  Modules: ModuleListItem[] = [];

  /**
   * @generated from field: platform.Pagination Pagination = 2;
   */
  Pagination?: Pagination;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  /**
   * Backend-recommended default server for initial selection
   *
   * @generated from field: string DefaultServerID = 4;
   */
  DefaultServerID = "";

  constructor(data?: PartialMessage<ModuleListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ModuleListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Modules", kind: "message", T: ModuleListItem, repeated: true },
    { no: 2, name: "Pagination", kind: "message", T: Pagination },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
    { no: 4, name: "DefaultServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModuleListResponse {
    return new ModuleListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModuleListResponse {
    return new ModuleListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModuleListResponse {
    return new ModuleListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ModuleListResponse | PlainMessage<ModuleListResponse> | undefined, b: ModuleListResponse | PlainMessage<ModuleListResponse> | undefined): boolean {
    return proto3.util.equals(ModuleListResponse, a, b);
  }
}

/**
 * @generated from message platform.GetModuleRequest
 */
export class GetModuleRequest extends Message<GetModuleRequest> {
  /**
   * @generated from field: string Name = 1;
   */
  Name = "";

  /**
   * @generated from field: string ID = 2;
   */
  ID = "";

  constructor(data?: PartialMessage<GetModuleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetModuleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetModuleRequest {
    return new GetModuleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetModuleRequest {
    return new GetModuleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetModuleRequest {
    return new GetModuleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetModuleRequest | PlainMessage<GetModuleRequest> | undefined, b: GetModuleRequest | PlainMessage<GetModuleRequest> | undefined): boolean {
    return proto3.util.equals(GetModuleRequest, a, b);
  }
}

/**
 * @generated from message platform.GetModuleResponse
 */
export class GetModuleResponse extends Message<GetModuleResponse> {
  /**
   * @generated from field: platform.Module Module = 1;
   */
  Module?: Module;

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Workspace Workspace = 3;
   */
  Workspace?: Workspace;

  /**
   * @generated from field: platform.Configuration PublishForm = 4;
   */
  PublishForm?: Configuration;

  /**
   * @generated from field: platform.Configuration ResourcesForm = 5;
   */
  ResourcesForm?: Configuration;

  /**
   * Desktop Helm installation instructions
   *
   * @generated from field: platform.HelmInstallConfig HelmInstall = 6;
   */
  HelmInstall?: HelmInstallConfig;

  constructor(data?: PartialMessage<GetModuleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetModuleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Module", kind: "message", T: Module },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
    { no: 3, name: "Workspace", kind: "message", T: Workspace },
    { no: 4, name: "PublishForm", kind: "message", T: Configuration },
    { no: 5, name: "ResourcesForm", kind: "message", T: Configuration },
    { no: 6, name: "HelmInstall", kind: "message", T: HelmInstallConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetModuleResponse {
    return new GetModuleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetModuleResponse {
    return new GetModuleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetModuleResponse {
    return new GetModuleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetModuleResponse | PlainMessage<GetModuleResponse> | undefined, b: GetModuleResponse | PlainMessage<GetModuleResponse> | undefined): boolean {
    return proto3.util.equals(GetModuleResponse, a, b);
  }
}

/**
 * @generated from message platform.UpdateModuleSettingsRequest
 */
export class UpdateModuleSettingsRequest extends Message<UpdateModuleSettingsRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: platform.Configuration ConfigurationForm = 2;
   */
  ConfigurationForm?: Configuration;

  constructor(data?: PartialMessage<UpdateModuleSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.UpdateModuleSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ConfigurationForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateModuleSettingsRequest {
    return new UpdateModuleSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateModuleSettingsRequest {
    return new UpdateModuleSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateModuleSettingsRequest {
    return new UpdateModuleSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateModuleSettingsRequest | PlainMessage<UpdateModuleSettingsRequest> | undefined, b: UpdateModuleSettingsRequest | PlainMessage<UpdateModuleSettingsRequest> | undefined): boolean {
    return proto3.util.equals(UpdateModuleSettingsRequest, a, b);
  }
}

