// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file nil.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Nil
 */
export class Nil extends Message<Nil> {
  constructor(data?: PartialMessage<Nil>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Nil";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Nil {
    return new Nil().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Nil {
    return new Nil().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Nil {
    return new Nil().fromJsonString(jsonString, options);
  }

  static equals(a: Nil | PlainMessage<Nil> | undefined, b: Nil | PlainMessage<Nil> | undefined): boolean {
    return proto3.util.equals(Nil, a, b);
  }
}

