// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file notification.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUnreadCountRequest, GetUnreadCountResponse, ListNotificationsRequest, ListNotificationsResponse, MarkAllNotificationsReadRequest, MarkAllNotificationsReadResponse, MarkNotificationReadRequest, MarkNotificationReadResponse } from "./notification.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.NotificationService
 */
export const NotificationService = {
  typeName: "platform.NotificationService",
  methods: {
    /**
     * @generated from rpc platform.NotificationService.ListNotifications
     */
    listNotifications: {
      name: "ListNotifications",
      I: ListNotificationsRequest,
      O: ListNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.NotificationService.MarkNotificationRead
     */
    markNotificationRead: {
      name: "MarkNotificationRead",
      I: MarkNotificationReadRequest,
      O: MarkNotificationReadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.NotificationService.MarkAllNotificationsRead
     */
    markAllNotificationsRead: {
      name: "MarkAllNotificationsRead",
      I: MarkAllNotificationsReadRequest,
      O: MarkAllNotificationsReadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.NotificationService.GetUnreadCount
     */
    getUnreadCount: {
      name: "GetUnreadCount",
      I: GetUnreadCountRequest,
      O: GetUnreadCountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

