// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file portforward.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePortForwardStreamRequest, CreatePortForwardStreamResponse } from "./portforward.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.PortForwardService
 */
export const PortForwardService = {
  typeName: "platform.PortForwardService",
  methods: {
    /**
     * @generated from rpc platform.PortForwardService.Create
     */
    create: {
      name: "Create",
      I: CreatePortForwardStreamRequest,
      O: CreatePortForwardStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

