// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file portforward.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.CreatePortForwardStreamRequest
 */
export class CreatePortForwardStreamRequest extends Message<CreatePortForwardStreamRequest> {
  /**
   * @generated from field: string KubeConfig = 1;
   */
  KubeConfig = "";

  /**
   * @generated from field: string Namespace = 2;
   */
  Namespace = "";

  /**
   * @generated from field: repeated string Args = 3;
   */
  Args: string[] = [];

  /**
   * @generated from field: string AliasKey = 4;
   */
  AliasKey = "";

  constructor(data?: PartialMessage<CreatePortForwardStreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreatePortForwardStreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "KubeConfig", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Args", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "AliasKey", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePortForwardStreamRequest {
    return new CreatePortForwardStreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePortForwardStreamRequest {
    return new CreatePortForwardStreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePortForwardStreamRequest {
    return new CreatePortForwardStreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePortForwardStreamRequest | PlainMessage<CreatePortForwardStreamRequest> | undefined, b: CreatePortForwardStreamRequest | PlainMessage<CreatePortForwardStreamRequest> | undefined): boolean {
    return proto3.util.equals(CreatePortForwardStreamRequest, a, b);
  }
}

/**
 * @generated from message platform.PortForwarderInfo
 */
export class PortForwarderInfo extends Message<PortForwarderInfo> {
  /**
   * @generated from field: string Hostname = 1;
   */
  Hostname = "";

  /**
   * @generated from field: int64 Port = 2;
   */
  Port = protoInt64.zero;

  constructor(data?: PartialMessage<PortForwarderInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PortForwarderInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Hostname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Port", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PortForwarderInfo {
    return new PortForwarderInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PortForwarderInfo {
    return new PortForwarderInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PortForwarderInfo {
    return new PortForwarderInfo().fromJsonString(jsonString, options);
  }

  static equals(a: PortForwarderInfo | PlainMessage<PortForwarderInfo> | undefined, b: PortForwarderInfo | PlainMessage<PortForwarderInfo> | undefined): boolean {
    return proto3.util.equals(PortForwarderInfo, a, b);
  }
}

/**
 * @generated from message platform.CreatePortForwardStreamResponse
 */
export class CreatePortForwardStreamResponse extends Message<CreatePortForwardStreamResponse> {
  /**
   * @generated from field: platform.PortForwarderInfo PortForwarderInfo = 1;
   */
  PortForwarderInfo?: PortForwarderInfo;

  constructor(data?: PartialMessage<CreatePortForwardStreamResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreatePortForwardStreamResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PortForwarderInfo", kind: "message", T: PortForwarderInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePortForwardStreamResponse {
    return new CreatePortForwardStreamResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePortForwardStreamResponse {
    return new CreatePortForwardStreamResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePortForwardStreamResponse {
    return new CreatePortForwardStreamResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePortForwardStreamResponse | PlainMessage<CreatePortForwardStreamResponse> | undefined, b: CreatePortForwardStreamResponse | PlainMessage<CreatePortForwardStreamResponse> | undefined): boolean {
    return proto3.util.equals(CreatePortForwardStreamResponse, a, b);
  }
}

