// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file presence.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PresenceHeartbeatRequest, PresenceHeartbeatResponse, PresenceNotification, PresenceSubscribeRequest } from "./presence.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.PresenceService
 */
export const PresenceService = {
  typeName: "platform.PresenceService",
  methods: {
    /**
     * @generated from rpc platform.PresenceService.Heartbeat
     */
    heartbeat: {
      name: "Heartbeat",
      I: PresenceHeartbeatRequest,
      O: PresenceHeartbeatResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.PresenceService.Subscribe
     */
    subscribe: {
      name: "Subscribe",
      I: PresenceSubscribeRequest,
      O: PresenceNotification,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

