// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file presence.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.OnlineUser
 */
export class OnlineUser extends Message<OnlineUser> {
  /**
   * @generated from field: int32 user_id = 1;
   */
  userId = 0;

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string first_name = 3;
   */
  firstName = "";

  /**
   * @generated from field: string last_name = 4;
   */
  lastName = "";

  /**
   * @generated from field: string workspace_name = 5;
   */
  workspaceName = "";

  /**
   * @generated from field: string current_path = 6;
   */
  currentPath = "";

  /**
   * @generated from field: string last_seen = 7;
   */
  lastSeen = "";

  /**
   * @generated from field: bool is_guest = 8;
   */
  isGuest = false;

  /**
   * @generated from field: string user_agent = 9;
   */
  userAgent = "";

  /**
   * @generated from field: string session_id = 10;
   */
  sessionId = "";

  constructor(data?: PartialMessage<OnlineUser>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.OnlineUser";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "workspace_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "current_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "last_seen", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "is_guest", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "user_agent", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OnlineUser {
    return new OnlineUser().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OnlineUser {
    return new OnlineUser().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OnlineUser {
    return new OnlineUser().fromJsonString(jsonString, options);
  }

  static equals(a: OnlineUser | PlainMessage<OnlineUser> | undefined, b: OnlineUser | PlainMessage<OnlineUser> | undefined): boolean {
    return proto3.util.equals(OnlineUser, a, b);
  }
}

/**
 * @generated from message platform.PresenceHeartbeatRequest
 */
export class PresenceHeartbeatRequest extends Message<PresenceHeartbeatRequest> {
  /**
   * @generated from field: string current_path = 1;
   */
  currentPath = "";

  constructor(data?: PartialMessage<PresenceHeartbeatRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PresenceHeartbeatRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "current_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceHeartbeatRequest {
    return new PresenceHeartbeatRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceHeartbeatRequest {
    return new PresenceHeartbeatRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceHeartbeatRequest {
    return new PresenceHeartbeatRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PresenceHeartbeatRequest | PlainMessage<PresenceHeartbeatRequest> | undefined, b: PresenceHeartbeatRequest | PlainMessage<PresenceHeartbeatRequest> | undefined): boolean {
    return proto3.util.equals(PresenceHeartbeatRequest, a, b);
  }
}

/**
 * @generated from message platform.PresenceHeartbeatResponse
 */
export class PresenceHeartbeatResponse extends Message<PresenceHeartbeatResponse> {
  /**
   * @generated from field: string pending_conversation_uuid = 1;
   */
  pendingConversationUuid = "";

  /**
   * @generated from field: string pending_conversation_url = 2;
   */
  pendingConversationUrl = "";

  /**
   * @generated from field: string pending_conversations_url = 3;
   */
  pendingConversationsUrl = "";

  constructor(data?: PartialMessage<PresenceHeartbeatResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PresenceHeartbeatResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pending_conversation_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pending_conversation_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pending_conversations_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceHeartbeatResponse {
    return new PresenceHeartbeatResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceHeartbeatResponse {
    return new PresenceHeartbeatResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceHeartbeatResponse {
    return new PresenceHeartbeatResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PresenceHeartbeatResponse | PlainMessage<PresenceHeartbeatResponse> | undefined, b: PresenceHeartbeatResponse | PlainMessage<PresenceHeartbeatResponse> | undefined): boolean {
    return proto3.util.equals(PresenceHeartbeatResponse, a, b);
  }
}

/**
 * @generated from message platform.StreamOnlineUsersRequest
 */
export class StreamOnlineUsersRequest extends Message<StreamOnlineUsersRequest> {
  constructor(data?: PartialMessage<StreamOnlineUsersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StreamOnlineUsersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamOnlineUsersRequest {
    return new StreamOnlineUsersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamOnlineUsersRequest {
    return new StreamOnlineUsersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamOnlineUsersRequest {
    return new StreamOnlineUsersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamOnlineUsersRequest | PlainMessage<StreamOnlineUsersRequest> | undefined, b: StreamOnlineUsersRequest | PlainMessage<StreamOnlineUsersRequest> | undefined): boolean {
    return proto3.util.equals(StreamOnlineUsersRequest, a, b);
  }
}

/**
 * @generated from message platform.PresenceEvent
 */
export class PresenceEvent extends Message<PresenceEvent> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: repeated platform.OnlineUser users = 2;
   */
  users: OnlineUser[] = [];

  constructor(data?: PartialMessage<PresenceEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PresenceEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "users", kind: "message", T: OnlineUser, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceEvent {
    return new PresenceEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceEvent {
    return new PresenceEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceEvent {
    return new PresenceEvent().fromJsonString(jsonString, options);
  }

  static equals(a: PresenceEvent | PlainMessage<PresenceEvent> | undefined, b: PresenceEvent | PlainMessage<PresenceEvent> | undefined): boolean {
    return proto3.util.equals(PresenceEvent, a, b);
  }
}

/**
 * @generated from message platform.GetOnlineUsersRequest
 */
export class GetOnlineUsersRequest extends Message<GetOnlineUsersRequest> {
  constructor(data?: PartialMessage<GetOnlineUsersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetOnlineUsersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOnlineUsersRequest {
    return new GetOnlineUsersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOnlineUsersRequest {
    return new GetOnlineUsersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOnlineUsersRequest {
    return new GetOnlineUsersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetOnlineUsersRequest | PlainMessage<GetOnlineUsersRequest> | undefined, b: GetOnlineUsersRequest | PlainMessage<GetOnlineUsersRequest> | undefined): boolean {
    return proto3.util.equals(GetOnlineUsersRequest, a, b);
  }
}

/**
 * @generated from message platform.GetOnlineUsersResponse
 */
export class GetOnlineUsersResponse extends Message<GetOnlineUsersResponse> {
  /**
   * @generated from field: repeated platform.OnlineUser users = 1;
   */
  users: OnlineUser[] = [];

  constructor(data?: PartialMessage<GetOnlineUsersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetOnlineUsersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: OnlineUser, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOnlineUsersResponse {
    return new GetOnlineUsersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOnlineUsersResponse {
    return new GetOnlineUsersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOnlineUsersResponse {
    return new GetOnlineUsersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetOnlineUsersResponse | PlainMessage<GetOnlineUsersResponse> | undefined, b: GetOnlineUsersResponse | PlainMessage<GetOnlineUsersResponse> | undefined): boolean {
    return proto3.util.equals(GetOnlineUsersResponse, a, b);
  }
}

/**
 * @generated from message platform.PresenceSubscribeRequest
 */
export class PresenceSubscribeRequest extends Message<PresenceSubscribeRequest> {
  constructor(data?: PartialMessage<PresenceSubscribeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PresenceSubscribeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceSubscribeRequest {
    return new PresenceSubscribeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceSubscribeRequest {
    return new PresenceSubscribeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceSubscribeRequest {
    return new PresenceSubscribeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PresenceSubscribeRequest | PlainMessage<PresenceSubscribeRequest> | undefined, b: PresenceSubscribeRequest | PlainMessage<PresenceSubscribeRequest> | undefined): boolean {
    return proto3.util.equals(PresenceSubscribeRequest, a, b);
  }
}

/**
 * @generated from message platform.PresenceNotification
 */
export class PresenceNotification extends Message<PresenceNotification> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string pending_conversation_uuid = 2;
   */
  pendingConversationUuid = "";

  /**
   * @generated from field: string pending_conversation_url = 3;
   */
  pendingConversationUrl = "";

  /**
   * @generated from field: string pending_conversations_url = 4;
   */
  pendingConversationsUrl = "";

  constructor(data?: PartialMessage<PresenceNotification>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PresenceNotification";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pending_conversation_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pending_conversation_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "pending_conversations_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceNotification {
    return new PresenceNotification().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceNotification {
    return new PresenceNotification().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceNotification {
    return new PresenceNotification().fromJsonString(jsonString, options);
  }

  static equals(a: PresenceNotification | PlainMessage<PresenceNotification> | undefined, b: PresenceNotification | PlainMessage<PresenceNotification> | undefined): boolean {
    return proto3.util.equals(PresenceNotification, a, b);
  }
}

