// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file project.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Project
 */
export class Project extends Message<Project> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: string ResourceName = 4;
   */
  ResourceName = "";

  /**
   * @generated from field: int64 PlaygroundExpiresAtUnix = 5;
   */
  PlaygroundExpiresAtUnix = protoInt64.zero;

  constructor(data?: PartialMessage<Project>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Project";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "ResourceName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "PlaygroundExpiresAtUnix", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Project {
    return new Project().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Project {
    return new Project().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Project {
    return new Project().fromJsonString(jsonString, options);
  }

  static equals(a: Project | PlainMessage<Project> | undefined, b: Project | PlainMessage<Project> | undefined): boolean {
    return proto3.util.equals(Project, a, b);
  }
}

/**
 * @generated from message platform.ProjectStat
 */
export class ProjectStat extends Message<ProjectStat> {
  /**
   * @generated from field: int32 FlowsAmount = 1;
   */
  FlowsAmount = 0;

  /**
   * @generated from field: int32 NodesAmount = 2;
   */
  NodesAmount = 0;

  constructor(data?: PartialMessage<ProjectStat>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ProjectStat";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "FlowsAmount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "NodesAmount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectStat {
    return new ProjectStat().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectStat {
    return new ProjectStat().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectStat {
    return new ProjectStat().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectStat | PlainMessage<ProjectStat> | undefined, b: ProjectStat | PlainMessage<ProjectStat> | undefined): boolean {
    return proto3.util.equals(ProjectStat, a, b);
  }
}

