// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file project-page.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.ProjectDashboardPage
 */
export class ProjectDashboardPage extends Message<ProjectDashboardPage> {
  /**
   * @generated from field: string Name = 1;
   */
  Name = "";

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: int32 SortIdx = 3;
   */
  SortIdx = 0;

  constructor(data?: PartialMessage<ProjectDashboardPage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ProjectDashboardPage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "SortIdx", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectDashboardPage {
    return new ProjectDashboardPage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectDashboardPage {
    return new ProjectDashboardPage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectDashboardPage {
    return new ProjectDashboardPage().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectDashboardPage | PlainMessage<ProjectDashboardPage> | undefined, b: ProjectDashboardPage | PlainMessage<ProjectDashboardPage> | undefined): boolean {
    return proto3.util.equals(ProjectDashboardPage, a, b);
  }
}

