// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file project.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Struct } from "@bufbuild/protobuf";
import { Pagination, PaginationRequest } from "./pagination_pb.js";
import { AccessItem } from "./access-item_pb.js";
import { Configuration } from "./configuration_pb.js";
import { Project, ProjectStat } from "./project_pb.js";
import { Server } from "./server_pb.js";
import { Grid, Widget } from "./widget_pb.js";
import { ProjectDashboardPage } from "./project-page_pb.js";
import { FlowListItem } from "./flow_pb.js";
import { Solution } from "./solution_pb.js";
import { MessageType } from "./message_pb.js";

/**
 * @generated from enum platform.RecoveryPhase
 */
export enum RecoveryPhase {
  /**
   * @generated from enum value: RECOVERY_PHASE_UNSPECIFIED = 0;
   */
  RECOVERY_PHASE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: RECOVERY_LOAD_PROJECT = 1;
   */
  RECOVERY_LOAD_PROJECT = 1,

  /**
   * @generated from enum value: RECOVERY_LOAD_FLOWS = 2;
   */
  RECOVERY_LOAD_FLOWS = 2,

  /**
   * @generated from enum value: RECOVERY_LOAD_NODES = 3;
   */
  RECOVERY_LOAD_NODES = 3,

  /**
   * @generated from enum value: RECOVERY_LOAD_PAGES = 4;
   */
  RECOVERY_LOAD_PAGES = 4,

  /**
   * @generated from enum value: RECOVERY_APPLY_PROJECT = 10;
   */
  RECOVERY_APPLY_PROJECT = 10,

  /**
   * @generated from enum value: RECOVERY_APPLY_FLOWS = 11;
   */
  RECOVERY_APPLY_FLOWS = 11,

  /**
   * @generated from enum value: RECOVERY_APPLY_NODES = 12;
   */
  RECOVERY_APPLY_NODES = 12,

  /**
   * @generated from enum value: RECOVERY_APPLY_PAGES = 13;
   */
  RECOVERY_APPLY_PAGES = 13,

  /**
   * RECOVERY_REREGISTER_MODULES bounces the module deployments when
   * their TinyModule CRs are missing. TinyModule rows are recreated by
   * each module pod on startup; without them, cross-module signal
   * routing fails silently with "module address unknown" transient
   * retries. This phase is skipped when modules are already registered.
   *
   * @generated from enum value: RECOVERY_REREGISTER_MODULES = 14;
   */
  RECOVERY_REREGISTER_MODULES = 14,

  /**
   * @generated from enum value: RECOVERY_DONE = 20;
   */
  RECOVERY_DONE = 20,

  /**
   * @generated from enum value: RECOVERY_ERROR = 99;
   */
  RECOVERY_ERROR = 99,
}
// Retrieve enum metadata with: proto3.getEnumType(RecoveryPhase)
proto3.util.setEnumType(RecoveryPhase, "platform.RecoveryPhase", [
  { no: 0, name: "RECOVERY_PHASE_UNSPECIFIED" },
  { no: 1, name: "RECOVERY_LOAD_PROJECT" },
  { no: 2, name: "RECOVERY_LOAD_FLOWS" },
  { no: 3, name: "RECOVERY_LOAD_NODES" },
  { no: 4, name: "RECOVERY_LOAD_PAGES" },
  { no: 10, name: "RECOVERY_APPLY_PROJECT" },
  { no: 11, name: "RECOVERY_APPLY_FLOWS" },
  { no: 12, name: "RECOVERY_APPLY_NODES" },
  { no: 13, name: "RECOVERY_APPLY_PAGES" },
  { no: 14, name: "RECOVERY_REREGISTER_MODULES" },
  { no: 20, name: "RECOVERY_DONE" },
  { no: 99, name: "RECOVERY_ERROR" },
]);

/**
 * @generated from message platform.ProjectListRequest
 */
export class ProjectListRequest extends Message<ProjectListRequest> {
  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 1;
   */
  PaginationRequest?: PaginationRequest;

  /**
   * @generated from field: bool PinnedOnly = 2;
   */
  PinnedOnly = false;

  /**
   * filtered bu serverID
   *
   * @generated from field: string ServerID = 3;
   */
  ServerID = "";

  constructor(data?: PartialMessage<ProjectListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ProjectListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PaginationRequest", kind: "message", T: PaginationRequest },
    { no: 2, name: "PinnedOnly", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectListRequest {
    return new ProjectListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectListRequest {
    return new ProjectListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectListRequest {
    return new ProjectListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectListRequest | PlainMessage<ProjectListRequest> | undefined, b: ProjectListRequest | PlainMessage<ProjectListRequest> | undefined): boolean {
    return proto3.util.equals(ProjectListRequest, a, b);
  }
}

/**
 * @generated from message platform.ProjectListResponse
 */
export class ProjectListResponse extends Message<ProjectListResponse> {
  /**
   * @generated from field: repeated platform.ProjectListItem Projects = 1;
   */
  Projects: ProjectListItem[] = [];

  /**
   * @generated from field: platform.Pagination Pagination = 2;
   */
  Pagination?: Pagination;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Configuration NewProjectForm = 4;
   */
  NewProjectForm?: Configuration;

  constructor(data?: PartialMessage<ProjectListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ProjectListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Projects", kind: "message", T: ProjectListItem, repeated: true },
    { no: 2, name: "Pagination", kind: "message", T: Pagination },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
    { no: 4, name: "NewProjectForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectListResponse {
    return new ProjectListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectListResponse {
    return new ProjectListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectListResponse {
    return new ProjectListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectListResponse | PlainMessage<ProjectListResponse> | undefined, b: ProjectListResponse | PlainMessage<ProjectListResponse> | undefined): boolean {
    return proto3.util.equals(ProjectListResponse, a, b);
  }
}

/**
 * @generated from message platform.ProjectListItem
 */
export class ProjectListItem extends Message<ProjectListItem> {
  /**
   * @generated from field: platform.Project Project = 1;
   */
  Project?: Project;

  /**
   * @generated from field: platform.Server Server = 2;
   */
  Server?: Server;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  /**
   * @generated from field: bool Pinned = 4;
   */
  Pinned = false;

  /**
   * @generated from field: platform.ProjectStat Stat = 5;
   */
  Stat?: ProjectStat;

  constructor(data?: PartialMessage<ProjectListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ProjectListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Project", kind: "message", T: Project },
    { no: 2, name: "Server", kind: "message", T: Server },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
    { no: 4, name: "Pinned", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "Stat", kind: "message", T: ProjectStat },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectListItem {
    return new ProjectListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectListItem {
    return new ProjectListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectListItem {
    return new ProjectListItem().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectListItem | PlainMessage<ProjectListItem> | undefined, b: ProjectListItem | PlainMessage<ProjectListItem> | undefined): boolean {
    return proto3.util.equals(ProjectListItem, a, b);
  }
}

/**
 * @generated from message platform.CreateProjectRequest
 */
export class CreateProjectRequest extends Message<CreateProjectRequest> {
  /**
   * @generated from field: platform.Configuration NewProjectForm = 1;
   */
  NewProjectForm?: Configuration;

  constructor(data?: PartialMessage<CreateProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "NewProjectForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateProjectRequest {
    return new CreateProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateProjectRequest {
    return new CreateProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateProjectRequest {
    return new CreateProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateProjectRequest | PlainMessage<CreateProjectRequest> | undefined, b: CreateProjectRequest | PlainMessage<CreateProjectRequest> | undefined): boolean {
    return proto3.util.equals(CreateProjectRequest, a, b);
  }
}

/**
 * @generated from message platform.GetProjectStreamRequest
 */
export class GetProjectStreamRequest extends Message<GetProjectStreamRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string PageName = 2;
   */
  PageName = "";

  constructor(data?: PartialMessage<GetProjectStreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetProjectStreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "PageName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProjectStreamRequest {
    return new GetProjectStreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProjectStreamRequest {
    return new GetProjectStreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProjectStreamRequest {
    return new GetProjectStreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetProjectStreamRequest | PlainMessage<GetProjectStreamRequest> | undefined, b: GetProjectStreamRequest | PlainMessage<GetProjectStreamRequest> | undefined): boolean {
    return proto3.util.equals(GetProjectStreamRequest, a, b);
  }
}

/**
 * @generated from message platform.DashboardEvent
 */
export class DashboardEvent extends Message<DashboardEvent> {
  /**
   * @generated from field: string Type = 2;
   */
  Type = "";

  /**
   * @generated from field: string Message = 3;
   */
  Message = "";

  /**
   * @generated from field: platform.Widget Widget = 5;
   */
  Widget?: Widget;

  /**
   * @generated from field: google.protobuf.Struct Stats = 6;
   */
  Stats?: Struct;

  constructor(data?: PartialMessage<DashboardEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DashboardEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "Type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Widget", kind: "message", T: Widget },
    { no: 6, name: "Stats", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DashboardEvent {
    return new DashboardEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DashboardEvent {
    return new DashboardEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DashboardEvent {
    return new DashboardEvent().fromJsonString(jsonString, options);
  }

  static equals(a: DashboardEvent | PlainMessage<DashboardEvent> | undefined, b: DashboardEvent | PlainMessage<DashboardEvent> | undefined): boolean {
    return proto3.util.equals(DashboardEvent, a, b);
  }
}

/**
 * @generated from message platform.GetProjectStreamEvent
 */
export class GetProjectStreamEvent extends Message<GetProjectStreamEvent> {
  /**
   * @generated from field: string Id = 1;
   */
  Id = "";

  /**
   * @generated from field: string Type = 2;
   */
  Type = "";

  /**
   * @generated from field: string Message = 3;
   */
  Message = "";

  /**
   * additional data
   *
   * @generated from field: platform.ProjectClusterInfo ClusterInfo = 4;
   */
  ClusterInfo?: ProjectClusterInfo;

  /**
   * @generated from field: repeated platform.DashboardEvent DashboardEvent = 5;
   */
  DashboardEvent: DashboardEvent[] = [];

  /**
   * @generated from field: platform.GetProjectConfigurationResponse Configuration = 6;
   */
  Configuration?: GetProjectConfigurationResponse;

  constructor(data?: PartialMessage<GetProjectStreamEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetProjectStreamEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "ClusterInfo", kind: "message", T: ProjectClusterInfo },
    { no: 5, name: "DashboardEvent", kind: "message", T: DashboardEvent, repeated: true },
    { no: 6, name: "Configuration", kind: "message", T: GetProjectConfigurationResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProjectStreamEvent {
    return new GetProjectStreamEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProjectStreamEvent {
    return new GetProjectStreamEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProjectStreamEvent {
    return new GetProjectStreamEvent().fromJsonString(jsonString, options);
  }

  static equals(a: GetProjectStreamEvent | PlainMessage<GetProjectStreamEvent> | undefined, b: GetProjectStreamEvent | PlainMessage<GetProjectStreamEvent> | undefined): boolean {
    return proto3.util.equals(GetProjectStreamEvent, a, b);
  }
}

/**
 * all in one we need to load entire project
 *
 * @generated from message platform.ProjectClusterInfo
 */
export class ProjectClusterInfo extends Message<ProjectClusterInfo> {
  /**
   * @generated from field: platform.ProjectStat Stat = 1;
   */
  Stat?: ProjectStat;

  /**
   * @generated from field: repeated platform.ProjectDashboardPage Pages = 8;
   */
  Pages: ProjectDashboardPage[] = [];

  /**
   * @generated from field: repeated platform.FlowListItem Flows = 9;
   */
  Flows: FlowListItem[] = [];

  constructor(data?: PartialMessage<ProjectClusterInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ProjectClusterInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Stat", kind: "message", T: ProjectStat },
    { no: 8, name: "Pages", kind: "message", T: ProjectDashboardPage, repeated: true },
    { no: 9, name: "Flows", kind: "message", T: FlowListItem, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProjectClusterInfo {
    return new ProjectClusterInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProjectClusterInfo {
    return new ProjectClusterInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProjectClusterInfo {
    return new ProjectClusterInfo().fromJsonString(jsonString, options);
  }

  static equals(a: ProjectClusterInfo | PlainMessage<ProjectClusterInfo> | undefined, b: ProjectClusterInfo | PlainMessage<ProjectClusterInfo> | undefined): boolean {
    return proto3.util.equals(ProjectClusterInfo, a, b);
  }
}

/**
 * @generated from message platform.GetProjectConfigurationResponse
 */
export class GetProjectConfigurationResponse extends Message<GetProjectConfigurationResponse> {
  /**
   * @generated from field: platform.Project Project = 1;
   */
  Project?: Project;

  /**
   * @generated from field: platform.Server Server = 2;
   */
  Server?: Server;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  /**
   * @generated from field: platform.Solution Solution = 5;
   */
  Solution?: Solution;

  /**
   * @generated from field: platform.Configuration CreateDashboardPageForm = 6;
   */
  CreateDashboardPageForm?: Configuration;

  /**
   * @generated from field: platform.Configuration MigrateForm = 7;
   */
  MigrateForm?: Configuration;

  /**
   * @generated from field: platform.Configuration MainForm = 8;
   */
  MainForm?: Configuration;

  constructor(data?: PartialMessage<GetProjectConfigurationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetProjectConfigurationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Project", kind: "message", T: Project },
    { no: 2, name: "Server", kind: "message", T: Server },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
    { no: 5, name: "Solution", kind: "message", T: Solution },
    { no: 6, name: "CreateDashboardPageForm", kind: "message", T: Configuration },
    { no: 7, name: "MigrateForm", kind: "message", T: Configuration },
    { no: 8, name: "MainForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProjectConfigurationResponse {
    return new GetProjectConfigurationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProjectConfigurationResponse {
    return new GetProjectConfigurationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProjectConfigurationResponse {
    return new GetProjectConfigurationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetProjectConfigurationResponse | PlainMessage<GetProjectConfigurationResponse> | undefined, b: GetProjectConfigurationResponse | PlainMessage<GetProjectConfigurationResponse> | undefined): boolean {
    return proto3.util.equals(GetProjectConfigurationResponse, a, b);
  }
}

/**
 * @generated from message platform.GetProjectConfigurationRequest
 */
export class GetProjectConfigurationRequest extends Message<GetProjectConfigurationRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<GetProjectConfigurationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetProjectConfigurationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProjectConfigurationRequest {
    return new GetProjectConfigurationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProjectConfigurationRequest {
    return new GetProjectConfigurationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProjectConfigurationRequest {
    return new GetProjectConfigurationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetProjectConfigurationRequest | PlainMessage<GetProjectConfigurationRequest> | undefined, b: GetProjectConfigurationRequest | PlainMessage<GetProjectConfigurationRequest> | undefined): boolean {
    return proto3.util.equals(GetProjectConfigurationRequest, a, b);
  }
}

/**
 * @generated from message platform.SaveProjectMainConfigurationRequest
 */
export class SaveProjectMainConfigurationRequest extends Message<SaveProjectMainConfigurationRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: platform.Configuration ConfigurationForm = 2;
   */
  ConfigurationForm?: Configuration;

  constructor(data?: PartialMessage<SaveProjectMainConfigurationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SaveProjectMainConfigurationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ConfigurationForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveProjectMainConfigurationRequest {
    return new SaveProjectMainConfigurationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveProjectMainConfigurationRequest {
    return new SaveProjectMainConfigurationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveProjectMainConfigurationRequest {
    return new SaveProjectMainConfigurationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SaveProjectMainConfigurationRequest | PlainMessage<SaveProjectMainConfigurationRequest> | undefined, b: SaveProjectMainConfigurationRequest | PlainMessage<SaveProjectMainConfigurationRequest> | undefined): boolean {
    return proto3.util.equals(SaveProjectMainConfigurationRequest, a, b);
  }
}

/**
 * @generated from message platform.DeleteProjectRequest
 */
export class DeleteProjectRequest extends Message<DeleteProjectRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<DeleteProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeleteProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteProjectRequest {
    return new DeleteProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteProjectRequest {
    return new DeleteProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteProjectRequest {
    return new DeleteProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteProjectRequest | PlainMessage<DeleteProjectRequest> | undefined, b: DeleteProjectRequest | PlainMessage<DeleteProjectRequest> | undefined): boolean {
    return proto3.util.equals(DeleteProjectRequest, a, b);
  }
}

/**
 * @generated from message platform.SaveWidgetsRequest
 */
export class SaveWidgetsRequest extends Message<SaveWidgetsRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string PageName = 2;
   */
  PageName = "";

  /**
   * @generated from field: repeated platform.SaveWidget Widgets = 5;
   */
  Widgets: SaveWidget[] = [];

  constructor(data?: PartialMessage<SaveWidgetsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SaveWidgetsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "PageName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Widgets", kind: "message", T: SaveWidget, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveWidgetsRequest {
    return new SaveWidgetsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveWidgetsRequest {
    return new SaveWidgetsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveWidgetsRequest {
    return new SaveWidgetsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SaveWidgetsRequest | PlainMessage<SaveWidgetsRequest> | undefined, b: SaveWidgetsRequest | PlainMessage<SaveWidgetsRequest> | undefined): boolean {
    return proto3.util.equals(SaveWidgetsRequest, a, b);
  }
}

/**
 * @generated from message platform.SaveWidget
 */
export class SaveWidget extends Message<SaveWidget> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Title = 3;
   */
  Title = "";

  /**
   * @generated from field: platform.Grid Grid = 4;
   */
  Grid?: Grid;

  /**
   * @generated from field: bytes Schema = 5;
   */
  Schema = new Uint8Array(0);

  /**
   * @generated from field: repeated string Pages = 6;
   */
  Pages: string[] = [];

  /**
   * @generated from field: bytes DefaultSchema = 7;
   */
  DefaultSchema = new Uint8Array(0);

  /**
   * @generated from field: string ContentType = 8;
   */
  ContentType = "";

  /**
   * @generated from field: bytes Data = 9;
   */
  Data = new Uint8Array(0);

  constructor(data?: PartialMessage<SaveWidget>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SaveWidget";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Grid", kind: "message", T: Grid },
    { no: 5, name: "Schema", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "Pages", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "DefaultSchema", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 8, name: "ContentType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "Data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveWidget {
    return new SaveWidget().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveWidget {
    return new SaveWidget().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveWidget {
    return new SaveWidget().fromJsonString(jsonString, options);
  }

  static equals(a: SaveWidget | PlainMessage<SaveWidget> | undefined, b: SaveWidget | PlainMessage<SaveWidget> | undefined): boolean {
    return proto3.util.equals(SaveWidget, a, b);
  }
}

/**
 * @generated from message platform.CreateProjectDashboardPage
 */
export class CreateProjectDashboardPage extends Message<CreateProjectDashboardPage> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: platform.Configuration CreatePageForm = 2;
   */
  CreatePageForm?: Configuration;

  constructor(data?: PartialMessage<CreateProjectDashboardPage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateProjectDashboardPage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "CreatePageForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateProjectDashboardPage {
    return new CreateProjectDashboardPage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateProjectDashboardPage {
    return new CreateProjectDashboardPage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateProjectDashboardPage {
    return new CreateProjectDashboardPage().fromJsonString(jsonString, options);
  }

  static equals(a: CreateProjectDashboardPage | PlainMessage<CreateProjectDashboardPage> | undefined, b: CreateProjectDashboardPage | PlainMessage<CreateProjectDashboardPage> | undefined): boolean {
    return proto3.util.equals(CreateProjectDashboardPage, a, b);
  }
}

/**
 * @generated from message platform.DeleteProjectDashboardPage
 */
export class DeleteProjectDashboardPage extends Message<DeleteProjectDashboardPage> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string PageName = 2;
   */
  PageName = "";

  constructor(data?: PartialMessage<DeleteProjectDashboardPage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeleteProjectDashboardPage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "PageName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteProjectDashboardPage {
    return new DeleteProjectDashboardPage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteProjectDashboardPage {
    return new DeleteProjectDashboardPage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteProjectDashboardPage {
    return new DeleteProjectDashboardPage().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteProjectDashboardPage | PlainMessage<DeleteProjectDashboardPage> | undefined, b: DeleteProjectDashboardPage | PlainMessage<DeleteProjectDashboardPage> | undefined): boolean {
    return proto3.util.equals(DeleteProjectDashboardPage, a, b);
  }
}

/**
 * @generated from message platform.PinProjectRequest
 */
export class PinProjectRequest extends Message<PinProjectRequest> {
  /**
   * @generated from field: string ProjectId = 1;
   */
  ProjectId = "";

  constructor(data?: PartialMessage<PinProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.PinProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PinProjectRequest {
    return new PinProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PinProjectRequest {
    return new PinProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PinProjectRequest {
    return new PinProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PinProjectRequest | PlainMessage<PinProjectRequest> | undefined, b: PinProjectRequest | PlainMessage<PinProjectRequest> | undefined): boolean {
    return proto3.util.equals(PinProjectRequest, a, b);
  }
}

/**
 * @generated from message platform.UnPinProjectRequest
 */
export class UnPinProjectRequest extends Message<UnPinProjectRequest> {
  /**
   * @generated from field: string ProjectId = 1;
   */
  ProjectId = "";

  constructor(data?: PartialMessage<UnPinProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.UnPinProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnPinProjectRequest {
    return new UnPinProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnPinProjectRequest {
    return new UnPinProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnPinProjectRequest {
    return new UnPinProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnPinProjectRequest | PlainMessage<UnPinProjectRequest> | undefined, b: UnPinProjectRequest | PlainMessage<UnPinProjectRequest> | undefined): boolean {
    return proto3.util.equals(UnPinProjectRequest, a, b);
  }
}

/**
 * @generated from message platform.ExportProjectRequest
 */
export class ExportProjectRequest extends Message<ExportProjectRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<ExportProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ExportProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportProjectRequest {
    return new ExportProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportProjectRequest {
    return new ExportProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportProjectRequest {
    return new ExportProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ExportProjectRequest | PlainMessage<ExportProjectRequest> | undefined, b: ExportProjectRequest | PlainMessage<ExportProjectRequest> | undefined): boolean {
    return proto3.util.equals(ExportProjectRequest, a, b);
  }
}

/**
 * @generated from message platform.ExportProjectResponse
 */
export class ExportProjectResponse extends Message<ExportProjectResponse> {
  /**
   * @generated from field: string Export = 1;
   */
  Export = "";

  constructor(data?: PartialMessage<ExportProjectResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ExportProjectResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Export", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportProjectResponse {
    return new ExportProjectResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportProjectResponse {
    return new ExportProjectResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportProjectResponse {
    return new ExportProjectResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExportProjectResponse | PlainMessage<ExportProjectResponse> | undefined, b: ExportProjectResponse | PlainMessage<ExportProjectResponse> | undefined): boolean {
    return proto3.util.equals(ExportProjectResponse, a, b);
  }
}

/**
 * @generated from message platform.ImportProjectRequest
 */
export class ImportProjectRequest extends Message<ImportProjectRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string Data = 2;
   */
  Data = "";

  constructor(data?: PartialMessage<ImportProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ImportProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportProjectRequest {
    return new ImportProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportProjectRequest {
    return new ImportProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportProjectRequest {
    return new ImportProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ImportProjectRequest | PlainMessage<ImportProjectRequest> | undefined, b: ImportProjectRequest | PlainMessage<ImportProjectRequest> | undefined): boolean {
    return proto3.util.equals(ImportProjectRequest, a, b);
  }
}

/**
 * @generated from message platform.ImportProjectResponse
 */
export class ImportProjectResponse extends Message<ImportProjectResponse> {
  /**
   * @generated from field: string Message = 1;
   */
  Message = "";

  /**
   * @generated from field: platform.MessageType Type = 2;
   */
  Type = MessageType.Info;

  constructor(data?: PartialMessage<ImportProjectResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ImportProjectResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "enum", T: proto3.getEnumType(MessageType) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportProjectResponse {
    return new ImportProjectResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportProjectResponse {
    return new ImportProjectResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportProjectResponse {
    return new ImportProjectResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ImportProjectResponse | PlainMessage<ImportProjectResponse> | undefined, b: ImportProjectResponse | PlainMessage<ImportProjectResponse> | undefined): boolean {
    return proto3.util.equals(ImportProjectResponse, a, b);
  }
}

/**
 * @generated from message platform.RecoverProjectRequest
 */
export class RecoverProjectRequest extends Message<RecoverProjectRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<RecoverProjectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RecoverProjectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecoverProjectRequest {
    return new RecoverProjectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecoverProjectRequest {
    return new RecoverProjectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecoverProjectRequest {
    return new RecoverProjectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RecoverProjectRequest | PlainMessage<RecoverProjectRequest> | undefined, b: RecoverProjectRequest | PlainMessage<RecoverProjectRequest> | undefined): boolean {
    return proto3.util.equals(RecoverProjectRequest, a, b);
  }
}

/**
 * RecoverProjectEvent is streamed back to the client as the manager rebuilds
 * the project's CRs in the cluster from the platform DB. The frontend renders
 * each event as a line in the recovery modal and uses Current/Total to drive
 * the per-phase progress bar.
 *
 * @generated from message platform.RecoverProjectEvent
 */
export class RecoverProjectEvent extends Message<RecoverProjectEvent> {
  /**
   * @generated from field: platform.RecoveryPhase Phase = 1;
   */
  Phase = RecoveryPhase.RECOVERY_PHASE_UNSPECIFIED;

  /**
   * @generated from field: string Message = 2;
   */
  Message = "";

  /**
   * @generated from field: uint32 Current = 3;
   */
  Current = 0;

  /**
   * @generated from field: uint32 Total = 4;
   */
  Total = 0;

  /**
   * @generated from field: string Error = 5;
   */
  Error = "";

  constructor(data?: PartialMessage<RecoverProjectEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RecoverProjectEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Phase", kind: "enum", T: proto3.getEnumType(RecoveryPhase) },
    { no: 2, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Current", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "Total", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "Error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RecoverProjectEvent {
    return new RecoverProjectEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RecoverProjectEvent {
    return new RecoverProjectEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RecoverProjectEvent {
    return new RecoverProjectEvent().fromJsonString(jsonString, options);
  }

  static equals(a: RecoverProjectEvent | PlainMessage<RecoverProjectEvent> | undefined, b: RecoverProjectEvent | PlainMessage<RecoverProjectEvent> | undefined): boolean {
    return proto3.util.equals(RecoverProjectEvent, a, b);
  }
}

