// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file project.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProjectDashboardPage, CreateProjectRequest, DeleteProjectDashboardPage, DeleteProjectRequest, ExportProjectRequest, ExportProjectResponse, GetProjectConfigurationRequest, GetProjectConfigurationResponse, GetProjectStreamEvent, GetProjectStreamRequest, ImportProjectRequest, ImportProjectResponse, PinProjectRequest, ProjectListRequest, ProjectListResponse, RecoverProjectEvent, RecoverProjectRequest, SaveProjectMainConfigurationRequest, SaveWidgetsRequest, UnPinProjectRequest } from "./project.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Nil } from "./nil_pb.js";

/**
 * @generated from service platform.ProjectService
 */
export const ProjectService = {
  typeName: "platform.ProjectService",
  methods: {
    /**
     * list of projects
     *
     * @generated from rpc platform.ProjectService.List
     */
    list: {
      name: "List",
      I: ProjectListRequest,
      O: ProjectListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.Create
     */
    create: {
      name: "Create",
      I: CreateProjectRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.CreateDashboardPage
     */
    createDashboardPage: {
      name: "CreateDashboardPage",
      I: CreateProjectDashboardPage,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.DeleteDashboardPage
     */
    deleteDashboardPage: {
      name: "DeleteDashboardPage",
      I: DeleteProjectDashboardPage,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.GetStream
     */
    getStream: {
      name: "GetStream",
      I: GetProjectStreamRequest,
      O: GetProjectStreamEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc platform.ProjectService.GetConfiguration
     */
    getConfiguration: {
      name: "GetConfiguration",
      I: GetProjectConfigurationRequest,
      O: GetProjectConfigurationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.SaveMainConfiguration
     */
    saveMainConfiguration: {
      name: "SaveMainConfiguration",
      I: SaveProjectMainConfigurationRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteProjectRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.SaveWidgets
     */
    saveWidgets: {
      name: "SaveWidgets",
      I: SaveWidgetsRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.Pin
     */
    pin: {
      name: "Pin",
      I: PinProjectRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.UnPin
     */
    unPin: {
      name: "UnPin",
      I: UnPinProjectRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.Export
     */
    export: {
      name: "Export",
      I: ExportProjectRequest,
      O: ExportProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.ProjectService.Import
     */
    import: {
      name: "Import",
      I: ImportProjectRequest,
      O: ImportProjectResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc platform.ProjectService.Recover
     */
    recover: {
      name: "Recover",
      I: RecoverProjectRequest,
      O: RecoverProjectEvent,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

