// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file runs.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.RunStep
 */
export class RunStep extends Message<RunStep> {
  /**
   * @generated from field: string StepKey = 1;
   */
  StepKey = "";

  /**
   * Node is the TinyNode that executed the step (flowPrefix.module.node).
   *
   * @generated from field: string Node = 2;
   */
  Node = "";

  /**
   * done | failed
   *
   * @generated from field: string Status = 3;
   */
  Status = "";

  /**
   * @generated from field: string Error = 4;
   */
  Error = "";

  /**
   * RFC3339
   *
   * @generated from field: string CompletedAt = 5;
   */
  CompletedAt = "";

  /**
   * StepKeys of the hops this step emitted (children in the run graph).
   *
   * @generated from field: repeated string EmitStepKeys = 6;
   */
  EmitStepKeys: string[] = [];

  /**
   * Timing enrichment (from the self-describing step ledger).
   *
   * @generated from field: string StartedAt = 7;
   */
  StartedAt = "";

  /**
   * @generated from field: int64 DurationMs = 8;
   */
  DurationMs = protoInt64.zero;

  /**
   * InputPreview is a capped, human-readable snippet of the payload this
   * step received (the parent hop's data) — for inline debugging.
   *
   * @generated from field: string InputPreview = 9;
   */
  InputPreview = "";

  /**
   * InputBytes is the full payload size before capping.
   *
   * @generated from field: int64 InputBytes = 10;
   */
  InputBytes = protoInt64.zero;

  constructor(data?: PartialMessage<RunStep>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RunStep";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "StepKey", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Node", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "CompletedAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "EmitStepKeys", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "StartedAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "DurationMs", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "InputPreview", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "InputBytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RunStep {
    return new RunStep().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RunStep {
    return new RunStep().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RunStep {
    return new RunStep().fromJsonString(jsonString, options);
  }

  static equals(a: RunStep | PlainMessage<RunStep> | undefined, b: RunStep | PlainMessage<RunStep> | undefined): boolean {
    return proto3.util.equals(RunStep, a, b);
  }
}

/**
 * @generated from message platform.Run
 */
export class Run extends Message<Run> {
  /**
   * @generated from field: string RunID = 1;
   */
  RunID = "";

  /**
   * Flow resource name when it could be resolved from the node prefix.
   *
   * @generated from field: string FlowName = 2;
   */
  FlowName = "";

  /**
   * running | complete | failed
   *
   * @generated from field: string Status = 3;
   */
  Status = "";

  /**
   * Hops emitted but not yet completed.
   *
   * @generated from field: int32 PendingSteps = 4;
   */
  PendingSteps = 0;

  /**
   * @generated from field: int32 StepCount = 5;
   */
  StepCount = 0;

  /**
   * RFC3339 — earliest / latest step completion seen.
   *
   * @generated from field: string StartedAt = 6;
   */
  StartedAt = "";

  /**
   * @generated from field: string LastActivityAt = 7;
   */
  LastActivityAt = "";

  constructor(data?: PartialMessage<Run>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Run";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "RunID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "FlowName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "PendingSteps", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "StepCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "StartedAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "LastActivityAt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Run {
    return new Run().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Run {
    return new Run().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Run {
    return new Run().fromJsonString(jsonString, options);
  }

  static equals(a: Run | PlainMessage<Run> | undefined, b: Run | PlainMessage<Run> | undefined): boolean {
    return proto3.util.equals(Run, a, b);
  }
}

/**
 * @generated from message platform.ListRunsRequest
 */
export class ListRunsRequest extends Message<ListRunsRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * Optional: only runs whose steps belong to this flow.
   *
   * @generated from field: string FlowName = 2;
   */
  FlowName = "";

  constructor(data?: PartialMessage<ListRunsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListRunsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "FlowName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRunsRequest {
    return new ListRunsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRunsRequest {
    return new ListRunsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRunsRequest {
    return new ListRunsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRunsRequest | PlainMessage<ListRunsRequest> | undefined, b: ListRunsRequest | PlainMessage<ListRunsRequest> | undefined): boolean {
    return proto3.util.equals(ListRunsRequest, a, b);
  }
}

/**
 * @generated from message platform.ListRunsResponse
 */
export class ListRunsResponse extends Message<ListRunsResponse> {
  /**
   * @generated from field: repeated platform.Run Runs = 1;
   */
  Runs: Run[] = [];

  constructor(data?: PartialMessage<ListRunsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListRunsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Runs", kind: "message", T: Run, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRunsResponse {
    return new ListRunsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRunsResponse {
    return new ListRunsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRunsResponse {
    return new ListRunsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListRunsResponse | PlainMessage<ListRunsResponse> | undefined, b: ListRunsResponse | PlainMessage<ListRunsResponse> | undefined): boolean {
    return proto3.util.equals(ListRunsResponse, a, b);
  }
}

/**
 * @generated from message platform.GetRunRequest
 */
export class GetRunRequest extends Message<GetRunRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string RunID = 2;
   */
  RunID = "";

  constructor(data?: PartialMessage<GetRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "RunID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRunRequest {
    return new GetRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRunRequest {
    return new GetRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRunRequest {
    return new GetRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRunRequest | PlainMessage<GetRunRequest> | undefined, b: GetRunRequest | PlainMessage<GetRunRequest> | undefined): boolean {
    return proto3.util.equals(GetRunRequest, a, b);
  }
}

/**
 * @generated from message platform.GetRunResponse
 */
export class GetRunResponse extends Message<GetRunResponse> {
  /**
   * @generated from field: platform.Run Run = 1;
   */
  Run?: Run;

  /**
   * @generated from field: repeated platform.RunStep Steps = 2;
   */
  Steps: RunStep[] = [];

  constructor(data?: PartialMessage<GetRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Run", kind: "message", T: Run },
    { no: 2, name: "Steps", kind: "message", T: RunStep, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRunResponse {
    return new GetRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRunResponse {
    return new GetRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRunResponse {
    return new GetRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRunResponse | PlainMessage<GetRunResponse> | undefined, b: GetRunResponse | PlainMessage<GetRunResponse> | undefined): boolean {
    return proto3.util.equals(GetRunResponse, a, b);
  }
}

/**
 * @generated from message platform.RerunRunRequest
 */
export class RerunRunRequest extends Message<RerunRunRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string RunID = 2;
   */
  RunID = "";

  constructor(data?: PartialMessage<RerunRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RerunRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "RunID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RerunRunRequest {
    return new RerunRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RerunRunRequest {
    return new RerunRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RerunRunRequest {
    return new RerunRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RerunRunRequest | PlainMessage<RerunRunRequest> | undefined, b: RerunRunRequest | PlainMessage<RerunRunRequest> | undefined): boolean {
    return proto3.util.equals(RerunRunRequest, a, b);
  }
}

/**
 * @generated from message platform.RerunRunResponse
 */
export class RerunRunResponse extends Message<RerunRunResponse> {
  /**
   * @generated from field: string NewRunID = 1;
   */
  NewRunID = "";

  /**
   * @generated from field: int32 Republished = 2;
   */
  Republished = 0;

  constructor(data?: PartialMessage<RerunRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RerunRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "NewRunID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Republished", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RerunRunResponse {
    return new RerunRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RerunRunResponse {
    return new RerunRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RerunRunResponse {
    return new RerunRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RerunRunResponse | PlainMessage<RerunRunResponse> | undefined, b: RerunRunResponse | PlainMessage<RerunRunResponse> | undefined): boolean {
    return proto3.util.equals(RerunRunResponse, a, b);
  }
}

/**
 * @generated from message platform.RetryRunRequest
 */
export class RetryRunRequest extends Message<RetryRunRequest> {
  /**
   * @generated from field: string ProjectName = 1;
   */
  ProjectName = "";

  /**
   * @generated from field: string RunID = 2;
   */
  RunID = "";

  constructor(data?: PartialMessage<RetryRunRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RetryRunRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "RunID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RetryRunRequest {
    return new RetryRunRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RetryRunRequest {
    return new RetryRunRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RetryRunRequest {
    return new RetryRunRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RetryRunRequest | PlainMessage<RetryRunRequest> | undefined, b: RetryRunRequest | PlainMessage<RetryRunRequest> | undefined): boolean {
    return proto3.util.equals(RetryRunRequest, a, b);
  }
}

/**
 * @generated from message platform.RetryRunResponse
 */
export class RetryRunResponse extends Message<RetryRunResponse> {
  /**
   * @generated from field: platform.Run Run = 1;
   */
  Run?: Run;

  /**
   * How many stalled/failed hops were re-published.
   *
   * @generated from field: int32 Redriven = 2;
   */
  Redriven = 0;

  constructor(data?: PartialMessage<RetryRunResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.RetryRunResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Run", kind: "message", T: Run },
    { no: 2, name: "Redriven", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RetryRunResponse {
    return new RetryRunResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RetryRunResponse {
    return new RetryRunResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RetryRunResponse {
    return new RetryRunResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RetryRunResponse | PlainMessage<RetryRunResponse> | undefined, b: RetryRunResponse | PlainMessage<RetryRunResponse> | undefined): boolean {
    return proto3.util.equals(RetryRunResponse, a, b);
  }
}

