// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file server.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Server
 */
export class Server extends Message<Server> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Key = 2;
   */
  Key = "";

  /**
   * @generated from field: string Info = 3;
   */
  Info = "";

  /**
   * @generated from field: bool Online = 4;
   */
  Online = false;

  /**
   * @generated from field: string CpuLimit = 6;
   */
  CpuLimit = "";

  /**
   * @generated from field: string MemoryLimit = 7;
   */
  MemoryLimit = "";

  /**
   * @generated from field: string CpuUsage = 8;
   */
  CpuUsage = "";

  /**
   * @generated from field: string MemoryUsage = 9;
   */
  MemoryUsage = "";

  /**
   * @generated from field: bool Dev = 10;
   */
  Dev = false;

  /**
   * @generated from field: string Namespace = 11;
   */
  Namespace = "";

  /**
   * @generated from field: int32 DeploymentsCount = 12;
   */
  DeploymentsCount = 0;

  constructor(data?: PartialMessage<Server>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Server";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Info", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Online", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "CpuLimit", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "MemoryLimit", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "CpuUsage", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "MemoryUsage", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "Dev", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "Namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "DeploymentsCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Server {
    return new Server().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Server {
    return new Server().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Server {
    return new Server().fromJsonString(jsonString, options);
  }

  static equals(a: Server | PlainMessage<Server> | undefined, b: Server | PlainMessage<Server> | undefined): boolean {
    return proto3.util.equals(Server, a, b);
  }
}

