// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file solution.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Solution
 */
export class Solution extends Message<Solution> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string Slug = 2;
   */
  Slug = "";

  /**
   * @generated from field: string Title = 3;
   */
  Title = "";

  /**
   * @generated from field: string Description = 4;
   */
  Description = "";

  /**
   * @generated from field: repeated string Tags = 5;
   */
  Tags: string[] = [];

  /**
   * @generated from field: int32 Revision = 6;
   */
  Revision = 0;

  /**
   * @generated from field: bool IsPublic = 7;
   */
  IsPublic = false;

  /**
   * @generated from field: int32 NodesCount = 8;
   */
  NodesCount = 0;

  /**
   * @generated from field: int32 FlowsCount = 9;
   */
  FlowsCount = 0;

  /**
   * @generated from field: int32 ModulesCount = 10;
   */
  ModulesCount = 0;

  /**
   * @generated from field: int32 PagesCount = 11;
   */
  PagesCount = 0;

  /**
   * @generated from field: int32 WidgetsCount = 12;
   */
  WidgetsCount = 0;

  /**
   * @generated from field: bool Verified = 13;
   */
  Verified = false;

  /**
   * @generated from field: string ImageURL = 14;
   */
  ImageURL = "";

  constructor(data?: PartialMessage<Solution>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Solution";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "Tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "Revision", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "IsPublic", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "NodesCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "FlowsCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "ModulesCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "PagesCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "WidgetsCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "Verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "ImageURL", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Solution {
    return new Solution().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Solution {
    return new Solution().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Solution {
    return new Solution().fromJsonString(jsonString, options);
  }

  static equals(a: Solution | PlainMessage<Solution> | undefined, b: Solution | PlainMessage<Solution> | undefined): boolean {
    return proto3.util.equals(Solution, a, b);
  }
}

