// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file solution.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Solution } from "./solution_pb.js";
import { Pagination, PaginationRequest } from "./pagination_pb.js";

/**
 * @generated from message platform.CreateExportTokenRequest
 */
export class CreateExportTokenRequest extends Message<CreateExportTokenRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  constructor(data?: PartialMessage<CreateExportTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateExportTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateExportTokenRequest {
    return new CreateExportTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateExportTokenRequest {
    return new CreateExportTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateExportTokenRequest {
    return new CreateExportTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateExportTokenRequest | PlainMessage<CreateExportTokenRequest> | undefined, b: CreateExportTokenRequest | PlainMessage<CreateExportTokenRequest> | undefined): boolean {
    return proto3.util.equals(CreateExportTokenRequest, a, b);
  }
}

/**
 * @generated from message platform.CreateExportTokenResponse
 */
export class CreateExportTokenResponse extends Message<CreateExportTokenResponse> {
  /**
   * @generated from field: string Token = 1;
   */
  Token = "";

  constructor(data?: PartialMessage<CreateExportTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateExportTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateExportTokenResponse {
    return new CreateExportTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateExportTokenResponse {
    return new CreateExportTokenResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateExportTokenResponse {
    return new CreateExportTokenResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateExportTokenResponse | PlainMessage<CreateExportTokenResponse> | undefined, b: CreateExportTokenResponse | PlainMessage<CreateExportTokenResponse> | undefined): boolean {
    return proto3.util.equals(CreateExportTokenResponse, a, b);
  }
}
import { Workspace } from "./workspace_pb.js";
import { AccessItem } from "./access-item_pb.js";
import { Flow } from "./flow_pb.js";
import { Configuration } from "./configuration_pb.js";
import { ProjectDashboardPage } from "./project-page_pb.js";
import { Widget } from "./widget_pb.js";
import { MessageType } from "./message_pb.js";

/**
 * @generated from message platform.CreateSolutionRequest
 */
export class CreateSolutionRequest extends Message<CreateSolutionRequest> {
  /**
   * @generated from field: string ProjectID = 1;
   */
  ProjectID = "";

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: string Description = 3;
   */
  Description = "";

  /**
   * @generated from field: repeated string Tags = 4;
   */
  Tags: string[] = [];

  constructor(data?: PartialMessage<CreateSolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateSolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ProjectID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSolutionRequest {
    return new CreateSolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSolutionRequest {
    return new CreateSolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSolutionRequest {
    return new CreateSolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateSolutionRequest | PlainMessage<CreateSolutionRequest> | undefined, b: CreateSolutionRequest | PlainMessage<CreateSolutionRequest> | undefined): boolean {
    return proto3.util.equals(CreateSolutionRequest, a, b);
  }
}

/**
 * @generated from message platform.CreateSolutionResponse
 */
export class CreateSolutionResponse extends Message<CreateSolutionResponse> {
  /**
   * @generated from field: platform.Solution Solution = 1;
   */
  Solution?: Solution;

  constructor(data?: PartialMessage<CreateSolutionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CreateSolutionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Solution", kind: "message", T: Solution },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSolutionResponse {
    return new CreateSolutionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSolutionResponse {
    return new CreateSolutionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSolutionResponse {
    return new CreateSolutionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateSolutionResponse | PlainMessage<CreateSolutionResponse> | undefined, b: CreateSolutionResponse | PlainMessage<CreateSolutionResponse> | undefined): boolean {
    return proto3.util.equals(CreateSolutionResponse, a, b);
  }
}

/**
 * @generated from message platform.ListSolutionsRequest
 */
export class ListSolutionsRequest extends Message<ListSolutionsRequest> {
  /**
   * @generated from field: string Search = 1;
   */
  Search = "";

  /**
   * @generated from field: platform.PaginationRequest PaginationRequest = 2;
   */
  PaginationRequest?: PaginationRequest;

  constructor(data?: PartialMessage<ListSolutionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListSolutionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Search", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "PaginationRequest", kind: "message", T: PaginationRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSolutionsRequest {
    return new ListSolutionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSolutionsRequest {
    return new ListSolutionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSolutionsRequest {
    return new ListSolutionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListSolutionsRequest | PlainMessage<ListSolutionsRequest> | undefined, b: ListSolutionsRequest | PlainMessage<ListSolutionsRequest> | undefined): boolean {
    return proto3.util.equals(ListSolutionsRequest, a, b);
  }
}

/**
 * @generated from message platform.SolutionListItem
 */
export class SolutionListItem extends Message<SolutionListItem> {
  /**
   * @generated from field: platform.Solution Solution = 1;
   */
  Solution?: Solution;

  /**
   * @generated from field: platform.Workspace Workspace = 2;
   */
  Workspace?: Workspace;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<SolutionListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SolutionListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Solution", kind: "message", T: Solution },
    { no: 2, name: "Workspace", kind: "message", T: Workspace },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SolutionListItem {
    return new SolutionListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SolutionListItem {
    return new SolutionListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SolutionListItem {
    return new SolutionListItem().fromJsonString(jsonString, options);
  }

  static equals(a: SolutionListItem | PlainMessage<SolutionListItem> | undefined, b: SolutionListItem | PlainMessage<SolutionListItem> | undefined): boolean {
    return proto3.util.equals(SolutionListItem, a, b);
  }
}

/**
 * @generated from message platform.ListSolutionsResponse
 */
export class ListSolutionsResponse extends Message<ListSolutionsResponse> {
  /**
   * @generated from field: repeated platform.SolutionListItem Solutions = 1;
   */
  Solutions: SolutionListItem[] = [];

  /**
   * @generated from field: platform.Pagination Pagination = 2;
   */
  Pagination?: Pagination;

  /**
   * @generated from field: platform.AccessItem Access = 3;
   */
  Access?: AccessItem;

  constructor(data?: PartialMessage<ListSolutionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ListSolutionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Solutions", kind: "message", T: SolutionListItem, repeated: true },
    { no: 2, name: "Pagination", kind: "message", T: Pagination },
    { no: 3, name: "Access", kind: "message", T: AccessItem },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSolutionsResponse {
    return new ListSolutionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSolutionsResponse {
    return new ListSolutionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSolutionsResponse {
    return new ListSolutionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListSolutionsResponse | PlainMessage<ListSolutionsResponse> | undefined, b: ListSolutionsResponse | PlainMessage<ListSolutionsResponse> | undefined): boolean {
    return proto3.util.equals(ListSolutionsResponse, a, b);
  }
}

/**
 * @generated from message platform.GetSolutionRequest
 */
export class GetSolutionRequest extends Message<GetSolutionRequest> {
  /**
   * @generated from field: string Slug = 1;
   */
  Slug = "";

  constructor(data?: PartialMessage<GetSolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetSolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSolutionRequest {
    return new GetSolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSolutionRequest {
    return new GetSolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSolutionRequest {
    return new GetSolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSolutionRequest | PlainMessage<GetSolutionRequest> | undefined, b: GetSolutionRequest | PlainMessage<GetSolutionRequest> | undefined): boolean {
    return proto3.util.equals(GetSolutionRequest, a, b);
  }
}

/**
 * @generated from message platform.GetSolutionResponse
 */
export class GetSolutionResponse extends Message<GetSolutionResponse> {
  /**
   * @generated from field: platform.Solution Solution = 1;
   */
  Solution?: Solution;

  /**
   * @generated from field: platform.AccessItem Access = 2;
   */
  Access?: AccessItem;

  /**
   * @generated from field: repeated platform.Flow Flows = 3;
   */
  Flows: Flow[] = [];

  /**
   * @generated from field: platform.Configuration PublishForm = 4;
   */
  PublishForm?: Configuration;

  /**
   * @generated from field: platform.Configuration DescriptionsForm = 5;
   */
  DescriptionsForm?: Configuration;

  /**
   * @generated from field: platform.Workspace Workspace = 6;
   */
  Workspace?: Workspace;

  /**
   * @generated from field: repeated platform.ProjectDashboardPage Pages = 7;
   */
  Pages: ProjectDashboardPage[] = [];

  /**
   * @generated from field: repeated platform.Widget Widgets = 8;
   */
  Widgets: Widget[] = [];

  /**
   * @generated from field: repeated string ModuleNames = 9;
   */
  ModuleNames: string[] = [];

  /**
   * @generated from field: int32 InstallCount = 10;
   */
  InstallCount = 0;

  constructor(data?: PartialMessage<GetSolutionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.GetSolutionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Solution", kind: "message", T: Solution },
    { no: 2, name: "Access", kind: "message", T: AccessItem },
    { no: 3, name: "Flows", kind: "message", T: Flow, repeated: true },
    { no: 4, name: "PublishForm", kind: "message", T: Configuration },
    { no: 5, name: "DescriptionsForm", kind: "message", T: Configuration },
    { no: 6, name: "Workspace", kind: "message", T: Workspace },
    { no: 7, name: "Pages", kind: "message", T: ProjectDashboardPage, repeated: true },
    { no: 8, name: "Widgets", kind: "message", T: Widget, repeated: true },
    { no: 9, name: "ModuleNames", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "InstallCount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSolutionResponse {
    return new GetSolutionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSolutionResponse {
    return new GetSolutionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSolutionResponse {
    return new GetSolutionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSolutionResponse | PlainMessage<GetSolutionResponse> | undefined, b: GetSolutionResponse | PlainMessage<GetSolutionResponse> | undefined): boolean {
    return proto3.util.equals(GetSolutionResponse, a, b);
  }
}

/**
 * @generated from message platform.UpdateSolutionSettingsRequest
 */
export class UpdateSolutionSettingsRequest extends Message<UpdateSolutionSettingsRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: platform.Configuration ConfigurationForm = 2;
   */
  ConfigurationForm?: Configuration;

  constructor(data?: PartialMessage<UpdateSolutionSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.UpdateSolutionSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ConfigurationForm", kind: "message", T: Configuration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSolutionSettingsRequest {
    return new UpdateSolutionSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSolutionSettingsRequest {
    return new UpdateSolutionSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSolutionSettingsRequest {
    return new UpdateSolutionSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateSolutionSettingsRequest | PlainMessage<UpdateSolutionSettingsRequest> | undefined, b: UpdateSolutionSettingsRequest | PlainMessage<UpdateSolutionSettingsRequest> | undefined): boolean {
    return proto3.util.equals(UpdateSolutionSettingsRequest, a, b);
  }
}

/**
 * @generated from message platform.InstallSolutionRequest
 */
export class InstallSolutionRequest extends Message<InstallSolutionRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string ServerID = 2;
   */
  ServerID = "";

  constructor(data?: PartialMessage<InstallSolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.InstallSolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InstallSolutionRequest {
    return new InstallSolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InstallSolutionRequest {
    return new InstallSolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InstallSolutionRequest {
    return new InstallSolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: InstallSolutionRequest | PlainMessage<InstallSolutionRequest> | undefined, b: InstallSolutionRequest | PlainMessage<InstallSolutionRequest> | undefined): boolean {
    return proto3.util.equals(InstallSolutionRequest, a, b);
  }
}

/**
 * @generated from message platform.InstallSolutionResponse
 */
export class InstallSolutionResponse extends Message<InstallSolutionResponse> {
  /**
   * @generated from field: string Message = 1;
   */
  Message = "";

  /**
   * @generated from field: platform.MessageType Type = 2;
   */
  Type = MessageType.Info;

  /**
   * @generated from field: string ProjectID = 3;
   */
  ProjectID = "";

  constructor(data?: PartialMessage<InstallSolutionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.InstallSolutionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Type", kind: "enum", T: proto3.getEnumType(MessageType) },
    { no: 3, name: "ProjectID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InstallSolutionResponse {
    return new InstallSolutionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InstallSolutionResponse {
    return new InstallSolutionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InstallSolutionResponse {
    return new InstallSolutionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: InstallSolutionResponse | PlainMessage<InstallSolutionResponse> | undefined, b: InstallSolutionResponse | PlainMessage<InstallSolutionResponse> | undefined): boolean {
    return proto3.util.equals(InstallSolutionResponse, a, b);
  }
}

/**
 * @generated from message platform.CheckSolutionInstallRequest
 */
export class CheckSolutionInstallRequest extends Message<CheckSolutionInstallRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: string ServerID = 2;
   */
  ServerID = "";

  constructor(data?: PartialMessage<CheckSolutionInstallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CheckSolutionInstallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ServerID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CheckSolutionInstallRequest {
    return new CheckSolutionInstallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CheckSolutionInstallRequest {
    return new CheckSolutionInstallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CheckSolutionInstallRequest {
    return new CheckSolutionInstallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CheckSolutionInstallRequest | PlainMessage<CheckSolutionInstallRequest> | undefined, b: CheckSolutionInstallRequest | PlainMessage<CheckSolutionInstallRequest> | undefined): boolean {
    return proto3.util.equals(CheckSolutionInstallRequest, a, b);
  }
}

/**
 * @generated from message platform.CheckSolutionInstallResponse
 */
export class CheckSolutionInstallResponse extends Message<CheckSolutionInstallResponse> {
  /**
   * @generated from field: bool Installed = 1;
   */
  Installed = false;

  /**
   * @generated from field: bool UpdateAvailable = 2;
   */
  UpdateAvailable = false;

  constructor(data?: PartialMessage<CheckSolutionInstallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.CheckSolutionInstallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Installed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "UpdateAvailable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CheckSolutionInstallResponse {
    return new CheckSolutionInstallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CheckSolutionInstallResponse {
    return new CheckSolutionInstallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CheckSolutionInstallResponse {
    return new CheckSolutionInstallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CheckSolutionInstallResponse | PlainMessage<CheckSolutionInstallResponse> | undefined, b: CheckSolutionInstallResponse | PlainMessage<CheckSolutionInstallResponse> | undefined): boolean {
    return proto3.util.equals(CheckSolutionInstallResponse, a, b);
  }
}

/**
 * @generated from message platform.ExportSolutionJSONRequest
 */
export class ExportSolutionJSONRequest extends Message<ExportSolutionJSONRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  constructor(data?: PartialMessage<ExportSolutionJSONRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ExportSolutionJSONRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportSolutionJSONRequest {
    return new ExportSolutionJSONRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportSolutionJSONRequest {
    return new ExportSolutionJSONRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportSolutionJSONRequest {
    return new ExportSolutionJSONRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ExportSolutionJSONRequest | PlainMessage<ExportSolutionJSONRequest> | undefined, b: ExportSolutionJSONRequest | PlainMessage<ExportSolutionJSONRequest> | undefined): boolean {
    return proto3.util.equals(ExportSolutionJSONRequest, a, b);
  }
}

/**
 * @generated from message platform.ExportSolutionJSONResponse
 */
export class ExportSolutionJSONResponse extends Message<ExportSolutionJSONResponse> {
  /**
   * @generated from field: string Export = 1;
   */
  Export = "";

  constructor(data?: PartialMessage<ExportSolutionJSONResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ExportSolutionJSONResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Export", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportSolutionJSONResponse {
    return new ExportSolutionJSONResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportSolutionJSONResponse {
    return new ExportSolutionJSONResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportSolutionJSONResponse {
    return new ExportSolutionJSONResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExportSolutionJSONResponse | PlainMessage<ExportSolutionJSONResponse> | undefined, b: ExportSolutionJSONResponse | PlainMessage<ExportSolutionJSONResponse> | undefined): boolean {
    return proto3.util.equals(ExportSolutionJSONResponse, a, b);
  }
}

/**
 * @generated from message platform.ImportSolutionJSONRequest
 */
export class ImportSolutionJSONRequest extends Message<ImportSolutionJSONRequest> {
  /**
   * @generated from field: string Data = 1;
   */
  Data = "";

  constructor(data?: PartialMessage<ImportSolutionJSONRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ImportSolutionJSONRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportSolutionJSONRequest {
    return new ImportSolutionJSONRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportSolutionJSONRequest {
    return new ImportSolutionJSONRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportSolutionJSONRequest {
    return new ImportSolutionJSONRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ImportSolutionJSONRequest | PlainMessage<ImportSolutionJSONRequest> | undefined, b: ImportSolutionJSONRequest | PlainMessage<ImportSolutionJSONRequest> | undefined): boolean {
    return proto3.util.equals(ImportSolutionJSONRequest, a, b);
  }
}

/**
 * @generated from message platform.ImportSolutionJSONResponse
 */
export class ImportSolutionJSONResponse extends Message<ImportSolutionJSONResponse> {
  /**
   * @generated from field: platform.Solution Solution = 1;
   */
  Solution?: Solution;

  constructor(data?: PartialMessage<ImportSolutionJSONResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.ImportSolutionJSONResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Solution", kind: "message", T: Solution },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportSolutionJSONResponse {
    return new ImportSolutionJSONResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportSolutionJSONResponse {
    return new ImportSolutionJSONResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportSolutionJSONResponse {
    return new ImportSolutionJSONResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ImportSolutionJSONResponse | PlainMessage<ImportSolutionJSONResponse> | undefined, b: ImportSolutionJSONResponse | PlainMessage<ImportSolutionJSONResponse> | undefined): boolean {
    return proto3.util.equals(ImportSolutionJSONResponse, a, b);
  }
}

/**
 * @generated from message platform.DeleteSolutionRequest
 */
export class DeleteSolutionRequest extends Message<DeleteSolutionRequest> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  constructor(data?: PartialMessage<DeleteSolutionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.DeleteSolutionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSolutionRequest {
    return new DeleteSolutionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSolutionRequest {
    return new DeleteSolutionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSolutionRequest {
    return new DeleteSolutionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteSolutionRequest | PlainMessage<DeleteSolutionRequest> | undefined, b: DeleteSolutionRequest | PlainMessage<DeleteSolutionRequest> | undefined): boolean {
    return proto3.util.equals(DeleteSolutionRequest, a, b);
  }
}

