// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file solution.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckSolutionInstallRequest, CreateExportTokenRequest, CreateExportTokenResponse, CreateSolutionRequest, CreateSolutionResponse, DeleteSolutionRequest, ExportSolutionJSONRequest, ExportSolutionJSONResponse, GetSolutionRequest, GetSolutionResponse, ImportSolutionJSONRequest, ImportSolutionJSONResponse, InstallSolutionRequest, InstallSolutionResponse, ListSolutionsRequest, ListSolutionsResponse, UpdateSolutionSettingsRequest } from "./solution.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Nil } from "./nil_pb.js";

/**
 * @generated from service platform.SolutionService
 */
export const SolutionService = {
  typeName: "platform.SolutionService",
  methods: {
    /**
     * @generated from rpc platform.SolutionService.Create
     */
    create: {
      name: "Create",
      I: CreateSolutionRequest,
      O: CreateSolutionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.List
     */
    list: {
      name: "List",
      I: ListSolutionsRequest,
      O: ListSolutionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.Get
     */
    get: {
      name: "Get",
      I: GetSolutionRequest,
      O: GetSolutionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.UpdateShareSettings
     */
    updateShareSettings: {
      name: "UpdateShareSettings",
      I: UpdateSolutionSettingsRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.UpdateDescriptions
     */
    updateDescriptions: {
      name: "UpdateDescriptions",
      I: UpdateSolutionSettingsRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.Install
     */
    install: {
      name: "Install",
      I: InstallSolutionRequest,
      O: InstallSolutionResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc platform.SolutionService.CheckInstall
     */
    checkInstall: {
      name: "CheckInstall",
      I: CheckSolutionInstallRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.ExportJSON
     */
    exportJSON: {
      name: "ExportJSON",
      I: ExportSolutionJSONRequest,
      O: ExportSolutionJSONResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.ImportJSON
     */
    importJSON: {
      name: "ImportJSON",
      I: ImportSolutionJSONRequest,
      O: ImportSolutionJSONResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteSolutionRequest,
      O: Nil,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SolutionService.CreateExportToken
     */
    createExportToken: {
      name: "CreateExportToken",
      I: CreateExportTokenRequest,
      O: CreateExportTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

