// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file statistics.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { StatisticsGetTraceByIDRequest, StatisticsGetTraceByIDResponse, StatisticsGetTracesRequest, StatisticsGetTracesResponse, StatisticsStreamRequest, StatisticsStreamResponse } from "./statistics.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.StatisticsService
 */
export const StatisticsService = {
  typeName: "platform.StatisticsService",
  methods: {
    /**
     * @generated from rpc platform.StatisticsService.GetStream
     */
    getStream: {
      name: "GetStream",
      I: StatisticsStreamRequest,
      O: StatisticsStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc platform.StatisticsService.GetTraces
     */
    getTraces: {
      name: "GetTraces",
      I: StatisticsGetTracesRequest,
      O: StatisticsGetTracesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.StatisticsService.GetTraceByID
     */
    getTraceByID: {
      name: "GetTraceByID",
      I: StatisticsGetTraceByIDRequest,
      O: StatisticsGetTraceByIDResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

