// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file statistics.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { TraceStat } from "./trace-stat_pb.js";

/**
 * @generated from message platform.StatisticsStreamRequest
 */
export class StatisticsStreamRequest extends Message<StatisticsStreamRequest> {
  /**
   * @generated from field: string FlowName = 1;
   */
  FlowName = "";

  /**
   * @generated from field: string ProjectName = 2;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<StatisticsStreamRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatisticsStreamRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "FlowName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatisticsStreamRequest {
    return new StatisticsStreamRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatisticsStreamRequest {
    return new StatisticsStreamRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatisticsStreamRequest {
    return new StatisticsStreamRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StatisticsStreamRequest | PlainMessage<StatisticsStreamRequest> | undefined, b: StatisticsStreamRequest | PlainMessage<StatisticsStreamRequest> | undefined): boolean {
    return proto3.util.equals(StatisticsStreamRequest, a, b);
  }
}

/**
 * @generated from message platform.StatisticsStreamResponse
 */
export class StatisticsStreamResponse extends Message<StatisticsStreamResponse> {
  /**
   * @generated from field: repeated platform.StatsEvent Events = 1;
   */
  Events: StatsEvent[] = [];

  constructor(data?: PartialMessage<StatisticsStreamResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatisticsStreamResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Events", kind: "message", T: StatsEvent, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatisticsStreamResponse {
    return new StatisticsStreamResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatisticsStreamResponse {
    return new StatisticsStreamResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatisticsStreamResponse {
    return new StatisticsStreamResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StatisticsStreamResponse | PlainMessage<StatisticsStreamResponse> | undefined, b: StatisticsStreamResponse | PlainMessage<StatisticsStreamResponse> | undefined): boolean {
    return proto3.util.equals(StatisticsStreamResponse, a, b);
  }
}

/**
 * @generated from message platform.StatisticsGetTracesRequest
 */
export class StatisticsGetTracesRequest extends Message<StatisticsGetTracesRequest> {
  /**
   * @generated from field: string FlowName = 1;
   */
  FlowName = "";

  /**
   * @generated from field: int64 Start = 2;
   */
  Start = protoInt64.zero;

  /**
   * @generated from field: int64 End = 3;
   */
  End = protoInt64.zero;

  /**
   * @generated from field: int64 Offset = 4;
   */
  Offset = protoInt64.zero;

  /**
   * @generated from field: string ProjectName = 5;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<StatisticsGetTracesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatisticsGetTracesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "FlowName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Start", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "End", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "Offset", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatisticsGetTracesRequest {
    return new StatisticsGetTracesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatisticsGetTracesRequest {
    return new StatisticsGetTracesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatisticsGetTracesRequest {
    return new StatisticsGetTracesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StatisticsGetTracesRequest | PlainMessage<StatisticsGetTracesRequest> | undefined, b: StatisticsGetTracesRequest | PlainMessage<StatisticsGetTracesRequest> | undefined): boolean {
    return proto3.util.equals(StatisticsGetTracesRequest, a, b);
  }
}

/**
 * @generated from message platform.StatisticsGetTracesResponse
 */
export class StatisticsGetTracesResponse extends Message<StatisticsGetTracesResponse> {
  /**
   * @generated from field: repeated platform.TraceStat Traces = 1;
   */
  Traces: TraceStat[] = [];

  /**
   * @generated from field: int64 Total = 2;
   */
  Total = protoInt64.zero;

  /**
   * @generated from field: int64 Offset = 3;
   */
  Offset = protoInt64.zero;

  constructor(data?: PartialMessage<StatisticsGetTracesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatisticsGetTracesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Traces", kind: "message", T: TraceStat, repeated: true },
    { no: 2, name: "Total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "Offset", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatisticsGetTracesResponse {
    return new StatisticsGetTracesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatisticsGetTracesResponse {
    return new StatisticsGetTracesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatisticsGetTracesResponse {
    return new StatisticsGetTracesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StatisticsGetTracesResponse | PlainMessage<StatisticsGetTracesResponse> | undefined, b: StatisticsGetTracesResponse | PlainMessage<StatisticsGetTracesResponse> | undefined): boolean {
    return proto3.util.equals(StatisticsGetTracesResponse, a, b);
  }
}

/**
 * @generated from message platform.StatsEvent
 */
export class StatsEvent extends Message<StatsEvent> {
  /**
   * @generated from field: string Metric = 1;
   */
  Metric = "";

  /**
   * @generated from field: double Value = 2;
   */
  Value = 0;

  /**
   * @generated from field: int64 Datetime = 3;
   */
  Datetime = protoInt64.zero;

  constructor(data?: PartialMessage<StatsEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatsEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Metric", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Value", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "Datetime", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatsEvent {
    return new StatsEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatsEvent {
    return new StatsEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatsEvent {
    return new StatsEvent().fromJsonString(jsonString, options);
  }

  static equals(a: StatsEvent | PlainMessage<StatsEvent> | undefined, b: StatsEvent | PlainMessage<StatsEvent> | undefined): boolean {
    return proto3.util.equals(StatsEvent, a, b);
  }
}

/**
 * @generated from message platform.Dataset
 */
export class Dataset extends Message<Dataset> {
  /**
   * @generated from field: string Label = 1;
   */
  Label = "";

  /**
   * @generated from field: string BackgroundColor = 2;
   */
  BackgroundColor = "";

  /**
   * @generated from field: string BorderColor = 3;
   */
  BorderColor = "";

  constructor(data?: PartialMessage<Dataset>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Dataset";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "BackgroundColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "BorderColor", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Dataset {
    return new Dataset().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Dataset {
    return new Dataset().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Dataset {
    return new Dataset().fromJsonString(jsonString, options);
  }

  static equals(a: Dataset | PlainMessage<Dataset> | undefined, b: Dataset | PlainMessage<Dataset> | undefined): boolean {
    return proto3.util.equals(Dataset, a, b);
  }
}

/**
 * @generated from message platform.StatisticsGetTraceByIDRequest
 */
export class StatisticsGetTraceByIDRequest extends Message<StatisticsGetTraceByIDRequest> {
  /**
   * @generated from field: string TraceID = 1;
   */
  TraceID = "";

  /**
   * @generated from field: string ProjectName = 2;
   */
  ProjectName = "";

  constructor(data?: PartialMessage<StatisticsGetTraceByIDRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatisticsGetTraceByIDRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "TraceID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ProjectName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatisticsGetTraceByIDRequest {
    return new StatisticsGetTraceByIDRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatisticsGetTraceByIDRequest {
    return new StatisticsGetTraceByIDRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatisticsGetTraceByIDRequest {
    return new StatisticsGetTraceByIDRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StatisticsGetTraceByIDRequest | PlainMessage<StatisticsGetTraceByIDRequest> | undefined, b: StatisticsGetTraceByIDRequest | PlainMessage<StatisticsGetTraceByIDRequest> | undefined): boolean {
    return proto3.util.equals(StatisticsGetTraceByIDRequest, a, b);
  }
}

/**
 * @generated from message platform.StatisticsGetTraceByIDResponse
 */
export class StatisticsGetTraceByIDResponse extends Message<StatisticsGetTraceByIDResponse> {
  /**
   * @generated from field: string TraceID = 1;
   */
  TraceID = "";

  /**
   * @generated from field: repeated platform.TraceSpan Spans = 2;
   */
  Spans: TraceSpan[] = [];

  constructor(data?: PartialMessage<StatisticsGetTraceByIDResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StatisticsGetTraceByIDResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "TraceID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Spans", kind: "message", T: TraceSpan, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatisticsGetTraceByIDResponse {
    return new StatisticsGetTraceByIDResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatisticsGetTraceByIDResponse {
    return new StatisticsGetTraceByIDResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatisticsGetTraceByIDResponse {
    return new StatisticsGetTraceByIDResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StatisticsGetTraceByIDResponse | PlainMessage<StatisticsGetTraceByIDResponse> | undefined, b: StatisticsGetTraceByIDResponse | PlainMessage<StatisticsGetTraceByIDResponse> | undefined): boolean {
    return proto3.util.equals(StatisticsGetTraceByIDResponse, a, b);
  }
}

/**
 * @generated from message platform.TraceSpan
 */
export class TraceSpan extends Message<TraceSpan> {
  /**
   * @generated from field: string SpanID = 1;
   */
  SpanID = "";

  /**
   * @generated from field: string ParentSpanID = 2;
   */
  ParentSpanID = "";

  /**
   * @generated from field: string Name = 3;
   */
  Name = "";

  /**
   * @generated from field: int64 StartTimeUnixNano = 4;
   */
  StartTimeUnixNano = protoInt64.zero;

  /**
   * @generated from field: int64 EndTimeUnixNano = 5;
   */
  EndTimeUnixNano = protoInt64.zero;

  /**
   * @generated from field: repeated platform.TraceSpanAttribute Attributes = 6;
   */
  Attributes: TraceSpanAttribute[] = [];

  /**
   * @generated from field: repeated platform.TraceSpanEvent Events = 7;
   */
  Events: TraceSpanEvent[] = [];

  /**
   * @generated from field: string Status = 8;
   */
  Status = "";

  constructor(data?: PartialMessage<TraceSpan>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.TraceSpan";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "SpanID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ParentSpanID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "StartTimeUnixNano", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "EndTimeUnixNano", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "Attributes", kind: "message", T: TraceSpanAttribute, repeated: true },
    { no: 7, name: "Events", kind: "message", T: TraceSpanEvent, repeated: true },
    { no: 8, name: "Status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TraceSpan {
    return new TraceSpan().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TraceSpan {
    return new TraceSpan().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TraceSpan {
    return new TraceSpan().fromJsonString(jsonString, options);
  }

  static equals(a: TraceSpan | PlainMessage<TraceSpan> | undefined, b: TraceSpan | PlainMessage<TraceSpan> | undefined): boolean {
    return proto3.util.equals(TraceSpan, a, b);
  }
}

/**
 * @generated from message platform.TraceSpanAttribute
 */
export class TraceSpanAttribute extends Message<TraceSpanAttribute> {
  /**
   * @generated from field: string Key = 1;
   */
  Key = "";

  /**
   * @generated from field: string Value = 2;
   */
  Value = "";

  constructor(data?: PartialMessage<TraceSpanAttribute>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.TraceSpanAttribute";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TraceSpanAttribute {
    return new TraceSpanAttribute().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TraceSpanAttribute {
    return new TraceSpanAttribute().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TraceSpanAttribute {
    return new TraceSpanAttribute().fromJsonString(jsonString, options);
  }

  static equals(a: TraceSpanAttribute | PlainMessage<TraceSpanAttribute> | undefined, b: TraceSpanAttribute | PlainMessage<TraceSpanAttribute> | undefined): boolean {
    return proto3.util.equals(TraceSpanAttribute, a, b);
  }
}

/**
 * @generated from message platform.TraceSpanEvent
 */
export class TraceSpanEvent extends Message<TraceSpanEvent> {
  /**
   * @generated from field: string Name = 1;
   */
  Name = "";

  /**
   * @generated from field: int64 TimeUnixNano = 2;
   */
  TimeUnixNano = protoInt64.zero;

  /**
   * @generated from field: repeated platform.TraceSpanAttribute Attributes = 3;
   */
  Attributes: TraceSpanAttribute[] = [];

  constructor(data?: PartialMessage<TraceSpanEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.TraceSpanEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "TimeUnixNano", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "Attributes", kind: "message", T: TraceSpanAttribute, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TraceSpanEvent {
    return new TraceSpanEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TraceSpanEvent {
    return new TraceSpanEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TraceSpanEvent {
    return new TraceSpanEvent().fromJsonString(jsonString, options);
  }

  static equals(a: TraceSpanEvent | PlainMessage<TraceSpanEvent> | undefined, b: TraceSpanEvent | PlainMessage<TraceSpanEvent> | undefined): boolean {
    return proto3.util.equals(TraceSpanEvent, a, b);
  }
}

