// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file support.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SupportAddMessageRequest, SupportAddMessageResponse, SupportConversationEvent, SupportCreateConversationRequest, SupportCreateConversationResponse, SupportGetConversationRequest, SupportGetConversationResponse, SupportListConversationsRequest, SupportListConversationsResponse, SupportResolveConversationRequest, SupportResolveConversationResponse, SupportStreamConversationRequest } from "./support.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.SupportService
 */
export const SupportService = {
  typeName: "platform.SupportService",
  methods: {
    /**
     * @generated from rpc platform.SupportService.CreateConversation
     */
    createConversation: {
      name: "CreateConversation",
      I: SupportCreateConversationRequest,
      O: SupportCreateConversationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SupportService.ListConversations
     */
    listConversations: {
      name: "ListConversations",
      I: SupportListConversationsRequest,
      O: SupportListConversationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SupportService.GetConversation
     */
    getConversation: {
      name: "GetConversation",
      I: SupportGetConversationRequest,
      O: SupportGetConversationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SupportService.AddMessage
     */
    addMessage: {
      name: "AddMessage",
      I: SupportAddMessageRequest,
      O: SupportAddMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SupportService.ResolveConversation
     */
    resolveConversation: {
      name: "ResolveConversation",
      I: SupportResolveConversationRequest,
      O: SupportResolveConversationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.SupportService.StreamConversation
     */
    streamConversation: {
      name: "StreamConversation",
      I: SupportStreamConversationRequest,
      O: SupportConversationEvent,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

