// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file support.messages.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.SupportConversation
 */
export class SupportConversation extends Message<SupportConversation> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid = "";

  /**
   * @generated from field: string subject = 2;
   */
  subject = "";

  /**
   * open, waiting_user, resolved, closed
   *
   * @generated from field: string status = 3;
   */
  status = "";

  /**
   * low, normal, high, urgent
   *
   * @generated from field: string priority = 4;
   */
  priority = "";

  /**
   * @generated from field: string author_email = 5;
   */
  authorEmail = "";

  /**
   * @generated from field: string author_name = 6;
   */
  authorName = "";

  /**
   * @generated from field: repeated string tags = 7;
   */
  tags: string[] = [];

  /**
   * @generated from field: string created_at = 8;
   */
  createdAt = "";

  /**
   * @generated from field: string updated_at = 9;
   */
  updatedAt = "";

  /**
   * @generated from field: string closed_at = 10;
   */
  closedAt = "";

  /**
   * @generated from field: string escalated_at = 11;
   */
  escalatedAt = "";

  constructor(data?: PartialMessage<SupportConversation>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportConversation";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "priority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "author_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "author_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "updated_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "closed_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "escalated_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportConversation {
    return new SupportConversation().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportConversation {
    return new SupportConversation().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportConversation {
    return new SupportConversation().fromJsonString(jsonString, options);
  }

  static equals(a: SupportConversation | PlainMessage<SupportConversation> | undefined, b: SupportConversation | PlainMessage<SupportConversation> | undefined): boolean {
    return proto3.util.equals(SupportConversation, a, b);
  }
}

/**
 * @generated from message platform.SupportConversationMessage
 */
export class SupportConversationMessage extends Message<SupportConversationMessage> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid = "";

  /**
   * guest, user, agent, ai
   *
   * @generated from field: string author_type = 2;
   */
  authorType = "";

  /**
   * @generated from field: string author_name = 3;
   */
  authorName = "";

  /**
   * @generated from field: string content = 4;
   */
  content = "";

  /**
   * JSON string
   *
   * @generated from field: string metadata = 5;
   */
  metadata = "";

  /**
   * @generated from field: string created_at = 6;
   */
  createdAt = "";

  constructor(data?: PartialMessage<SupportConversationMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportConversationMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "author_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "metadata", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportConversationMessage {
    return new SupportConversationMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportConversationMessage {
    return new SupportConversationMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportConversationMessage {
    return new SupportConversationMessage().fromJsonString(jsonString, options);
  }

  static equals(a: SupportConversationMessage | PlainMessage<SupportConversationMessage> | undefined, b: SupportConversationMessage | PlainMessage<SupportConversationMessage> | undefined): boolean {
    return proto3.util.equals(SupportConversationMessage, a, b);
  }
}

/**
 * @generated from message platform.SupportCreateConversationRequest
 */
export class SupportCreateConversationRequest extends Message<SupportCreateConversationRequest> {
  /**
   * @generated from field: string email = 1;
   */
  email = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string subject = 3;
   */
  subject = "";

  /**
   * @generated from field: string message = 4;
   */
  message = "";

  constructor(data?: PartialMessage<SupportCreateConversationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportCreateConversationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportCreateConversationRequest {
    return new SupportCreateConversationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportCreateConversationRequest {
    return new SupportCreateConversationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportCreateConversationRequest {
    return new SupportCreateConversationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SupportCreateConversationRequest | PlainMessage<SupportCreateConversationRequest> | undefined, b: SupportCreateConversationRequest | PlainMessage<SupportCreateConversationRequest> | undefined): boolean {
    return proto3.util.equals(SupportCreateConversationRequest, a, b);
  }
}

/**
 * @generated from message platform.SupportCreateConversationResponse
 */
export class SupportCreateConversationResponse extends Message<SupportCreateConversationResponse> {
  /**
   * @generated from field: platform.SupportConversation conversation = 1;
   */
  conversation?: SupportConversation;

  /**
   * @generated from field: string conversation_url = 2;
   */
  conversationUrl = "";

  /**
   * @generated from field: string conversations_url = 3;
   */
  conversationsUrl = "";

  constructor(data?: PartialMessage<SupportCreateConversationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportCreateConversationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation", kind: "message", T: SupportConversation },
    { no: 2, name: "conversation_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "conversations_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportCreateConversationResponse {
    return new SupportCreateConversationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportCreateConversationResponse {
    return new SupportCreateConversationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportCreateConversationResponse {
    return new SupportCreateConversationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SupportCreateConversationResponse | PlainMessage<SupportCreateConversationResponse> | undefined, b: SupportCreateConversationResponse | PlainMessage<SupportCreateConversationResponse> | undefined): boolean {
    return proto3.util.equals(SupportCreateConversationResponse, a, b);
  }
}

/**
 * @generated from message platform.SupportListConversationsRequest
 */
export class SupportListConversationsRequest extends Message<SupportListConversationsRequest> {
  /**
   * @generated from field: string email = 1;
   */
  email = "";

  /**
   * @generated from field: string expires = 2;
   */
  expires = "";

  /**
   * @generated from field: string sig = 3;
   */
  sig = "";

  /**
   * @generated from field: int32 limit = 4;
   */
  limit = 0;

  /**
   * @generated from field: int32 offset = 5;
   */
  offset = 0;

  constructor(data?: PartialMessage<SupportListConversationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportListConversationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expires", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sig", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportListConversationsRequest {
    return new SupportListConversationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportListConversationsRequest {
    return new SupportListConversationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportListConversationsRequest {
    return new SupportListConversationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SupportListConversationsRequest | PlainMessage<SupportListConversationsRequest> | undefined, b: SupportListConversationsRequest | PlainMessage<SupportListConversationsRequest> | undefined): boolean {
    return proto3.util.equals(SupportListConversationsRequest, a, b);
  }
}

/**
 * @generated from message platform.SupportListConversationsResponse
 */
export class SupportListConversationsResponse extends Message<SupportListConversationsResponse> {
  /**
   * @generated from field: repeated platform.SupportConversation conversations = 1;
   */
  conversations: SupportConversation[] = [];

  /**
   * @generated from field: int32 total = 2;
   */
  total = 0;

  constructor(data?: PartialMessage<SupportListConversationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportListConversationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversations", kind: "message", T: SupportConversation, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportListConversationsResponse {
    return new SupportListConversationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportListConversationsResponse {
    return new SupportListConversationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportListConversationsResponse {
    return new SupportListConversationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SupportListConversationsResponse | PlainMessage<SupportListConversationsResponse> | undefined, b: SupportListConversationsResponse | PlainMessage<SupportListConversationsResponse> | undefined): boolean {
    return proto3.util.equals(SupportListConversationsResponse, a, b);
  }
}

/**
 * @generated from message platform.SupportGetConversationRequest
 */
export class SupportGetConversationRequest extends Message<SupportGetConversationRequest> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string expires = 3;
   */
  expires = "";

  /**
   * @generated from field: string sig = 4;
   */
  sig = "";

  constructor(data?: PartialMessage<SupportGetConversationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportGetConversationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sig", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportGetConversationRequest {
    return new SupportGetConversationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportGetConversationRequest {
    return new SupportGetConversationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportGetConversationRequest {
    return new SupportGetConversationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SupportGetConversationRequest | PlainMessage<SupportGetConversationRequest> | undefined, b: SupportGetConversationRequest | PlainMessage<SupportGetConversationRequest> | undefined): boolean {
    return proto3.util.equals(SupportGetConversationRequest, a, b);
  }
}

/**
 * @generated from message platform.SupportGetConversationResponse
 */
export class SupportGetConversationResponse extends Message<SupportGetConversationResponse> {
  /**
   * @generated from field: platform.SupportConversation conversation = 1;
   */
  conversation?: SupportConversation;

  /**
   * @generated from field: repeated platform.SupportConversationMessage messages = 2;
   */
  messages: SupportConversationMessage[] = [];

  constructor(data?: PartialMessage<SupportGetConversationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportGetConversationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation", kind: "message", T: SupportConversation },
    { no: 2, name: "messages", kind: "message", T: SupportConversationMessage, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportGetConversationResponse {
    return new SupportGetConversationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportGetConversationResponse {
    return new SupportGetConversationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportGetConversationResponse {
    return new SupportGetConversationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SupportGetConversationResponse | PlainMessage<SupportGetConversationResponse> | undefined, b: SupportGetConversationResponse | PlainMessage<SupportGetConversationResponse> | undefined): boolean {
    return proto3.util.equals(SupportGetConversationResponse, a, b);
  }
}

/**
 * @generated from message platform.SupportAddMessageRequest
 */
export class SupportAddMessageRequest extends Message<SupportAddMessageRequest> {
  /**
   * @generated from field: string conversation_uuid = 1;
   */
  conversationUuid = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string expires = 3;
   */
  expires = "";

  /**
   * @generated from field: string sig = 4;
   */
  sig = "";

  /**
   * @generated from field: string content = 5;
   */
  content = "";

  constructor(data?: PartialMessage<SupportAddMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportAddMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sig", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportAddMessageRequest {
    return new SupportAddMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportAddMessageRequest {
    return new SupportAddMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportAddMessageRequest {
    return new SupportAddMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SupportAddMessageRequest | PlainMessage<SupportAddMessageRequest> | undefined, b: SupportAddMessageRequest | PlainMessage<SupportAddMessageRequest> | undefined): boolean {
    return proto3.util.equals(SupportAddMessageRequest, a, b);
  }
}

/**
 * @generated from message platform.SupportAddMessageResponse
 */
export class SupportAddMessageResponse extends Message<SupportAddMessageResponse> {
  /**
   * @generated from field: platform.SupportConversationMessage message = 1;
   */
  message?: SupportConversationMessage;

  constructor(data?: PartialMessage<SupportAddMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportAddMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: SupportConversationMessage },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportAddMessageResponse {
    return new SupportAddMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportAddMessageResponse {
    return new SupportAddMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportAddMessageResponse {
    return new SupportAddMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SupportAddMessageResponse | PlainMessage<SupportAddMessageResponse> | undefined, b: SupportAddMessageResponse | PlainMessage<SupportAddMessageResponse> | undefined): boolean {
    return proto3.util.equals(SupportAddMessageResponse, a, b);
  }
}

/**
 * @generated from message platform.SupportResolveConversationRequest
 */
export class SupportResolveConversationRequest extends Message<SupportResolveConversationRequest> {
  /**
   * @generated from field: string conversation_uuid = 1;
   */
  conversationUuid = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string expires = 3;
   */
  expires = "";

  /**
   * @generated from field: string sig = 4;
   */
  sig = "";

  constructor(data?: PartialMessage<SupportResolveConversationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportResolveConversationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sig", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportResolveConversationRequest {
    return new SupportResolveConversationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportResolveConversationRequest {
    return new SupportResolveConversationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportResolveConversationRequest {
    return new SupportResolveConversationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SupportResolveConversationRequest | PlainMessage<SupportResolveConversationRequest> | undefined, b: SupportResolveConversationRequest | PlainMessage<SupportResolveConversationRequest> | undefined): boolean {
    return proto3.util.equals(SupportResolveConversationRequest, a, b);
  }
}

/**
 * @generated from message platform.SupportResolveConversationResponse
 */
export class SupportResolveConversationResponse extends Message<SupportResolveConversationResponse> {
  constructor(data?: PartialMessage<SupportResolveConversationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportResolveConversationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportResolveConversationResponse {
    return new SupportResolveConversationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportResolveConversationResponse {
    return new SupportResolveConversationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportResolveConversationResponse {
    return new SupportResolveConversationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SupportResolveConversationResponse | PlainMessage<SupportResolveConversationResponse> | undefined, b: SupportResolveConversationResponse | PlainMessage<SupportResolveConversationResponse> | undefined): boolean {
    return proto3.util.equals(SupportResolveConversationResponse, a, b);
  }
}

/**
 * Streaming
 *
 * @generated from message platform.SupportStreamConversationRequest
 */
export class SupportStreamConversationRequest extends Message<SupportStreamConversationRequest> {
  /**
   * @generated from field: string conversation_uuid = 1;
   */
  conversationUuid = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string expires = 3;
   */
  expires = "";

  /**
   * @generated from field: string sig = 4;
   */
  sig = "";

  constructor(data?: PartialMessage<SupportStreamConversationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportStreamConversationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "conversation_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sig", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportStreamConversationRequest {
    return new SupportStreamConversationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportStreamConversationRequest {
    return new SupportStreamConversationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportStreamConversationRequest {
    return new SupportStreamConversationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SupportStreamConversationRequest | PlainMessage<SupportStreamConversationRequest> | undefined, b: SupportStreamConversationRequest | PlainMessage<SupportStreamConversationRequest> | undefined): boolean {
    return proto3.util.equals(SupportStreamConversationRequest, a, b);
  }
}

/**
 * @generated from message platform.SupportConversationEvent
 */
export class SupportConversationEvent extends Message<SupportConversationEvent> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: string conversation_uuid = 2;
   */
  conversationUuid = "";

  /**
   * @generated from field: string data = 3;
   */
  data = "";

  constructor(data?: PartialMessage<SupportConversationEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.SupportConversationEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "conversation_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SupportConversationEvent {
    return new SupportConversationEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SupportConversationEvent {
    return new SupportConversationEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SupportConversationEvent {
    return new SupportConversationEvent().fromJsonString(jsonString, options);
  }

  static equals(a: SupportConversationEvent | PlainMessage<SupportConversationEvent> | undefined, b: SupportConversationEvent | PlainMessage<SupportConversationEvent> | undefined): boolean {
    return proto3.util.equals(SupportConversationEvent, a, b);
  }
}

