// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file trace-stat.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.TraceStat
 */
export class TraceStat extends Message<TraceStat> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @generated from field: int64 Spans = 2;
   */
  Spans = protoInt64.zero;

  /**
   * @generated from field: int64 Errors = 3;
   */
  Errors = protoInt64.zero;

  /**
   * @generated from field: int64 Data = 4;
   */
  Data = protoInt64.zero;

  /**
   * @generated from field: int64 Length = 5;
   */
  Length = protoInt64.zero;

  /**
   * @generated from field: int64 Duration = 6;
   */
  Duration = protoInt64.zero;

  /**
   * @generated from field: int64 Start = 7;
   */
  Start = protoInt64.zero;

  /**
   * @generated from field: int64 End = 8;
   */
  End = protoInt64.zero;

  constructor(data?: PartialMessage<TraceStat>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.TraceStat";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Spans", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "Errors", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "Data", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "Length", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "Duration", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "Start", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "End", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TraceStat {
    return new TraceStat().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TraceStat {
    return new TraceStat().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TraceStat {
    return new TraceStat().fromJsonString(jsonString, options);
  }

  static equals(a: TraceStat | PlainMessage<TraceStat> | undefined, b: TraceStat | PlainMessage<TraceStat> | undefined): boolean {
    return proto3.util.equals(TraceStat, a, b);
  }
}

