// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file widget.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.Widget
 */
export class Widget extends Message<Widget> {
  /**
   * @generated from field: string Node = 1;
   */
  Node = "";

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: bytes DefaultSchema = 3;
   */
  DefaultSchema = new Uint8Array(0);

  /**
   * @generated from field: bytes Schema = 4;
   */
  Schema = new Uint8Array(0);

  /**
   * @generated from field: bytes Data = 5;
   */
  Data = new Uint8Array(0);

  /**
   * @generated from field: string Port = 6;
   */
  Port = "";

  /**
   * @generated from field: platform.Grid Grid = 7;
   */
  Grid?: Grid;

  /**
   * @generated from field: string ID = 8;
   */
  ID = "";

  /**
   * @generated from field: repeated string Pages = 9;
   */
  Pages: string[] = [];

  /**
   * @generated from field: string ContentType = 10;
   */
  ContentType = "";

  constructor(data?: PartialMessage<Widget>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Widget";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Node", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "DefaultSchema", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "Schema", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "Data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "Port", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "Grid", kind: "message", T: Grid },
    { no: 8, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "Pages", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "ContentType", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Widget {
    return new Widget().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Widget {
    return new Widget().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Widget {
    return new Widget().fromJsonString(jsonString, options);
  }

  static equals(a: Widget | PlainMessage<Widget> | undefined, b: Widget | PlainMessage<Widget> | undefined): boolean {
    return proto3.util.equals(Widget, a, b);
  }
}

/**
 * @generated from message platform.Grid
 */
export class Grid extends Message<Grid> {
  /**
   * @generated from field: int32 X = 4;
   */
  X = 0;

  /**
   * @generated from field: int32 Y = 5;
   */
  Y = 0;

  /**
   * @generated from field: int32 W = 6;
   */
  W = 0;

  /**
   * @generated from field: int32 H = 7;
   */
  H = 0;

  constructor(data?: PartialMessage<Grid>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Grid";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 4, name: "X", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "Y", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "W", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "H", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Grid {
    return new Grid().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Grid {
    return new Grid().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Grid {
    return new Grid().fromJsonString(jsonString, options);
  }

  static equals(a: Grid | PlainMessage<Grid> | undefined, b: Grid | PlainMessage<Grid> | undefined): boolean {
    return proto3.util.equals(Grid, a, b);
  }
}

