// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file workspace-events.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { StreamWorkspaceEventsRequest, WorkspaceEvent } from "./workspace-events_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * WorkspaceEventService provides real-time workspace-level events
 *
 * @generated from service platform.WorkspaceEventService
 */
export const WorkspaceEventService = {
  typeName: "platform.WorkspaceEventService",
  methods: {
    /**
     * StreamEvents streams all workspace-level events (jobs, notifications, etc.)
     *
     * @generated from rpc platform.WorkspaceEventService.StreamEvents
     */
    streamEvents: {
      name: "StreamEvents",
      I: StreamWorkspaceEventsRequest,
      O: WorkspaceEvent,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

