// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file workspace.service.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWorkspaceRequest, CreateWorkspaceResponse, GetInvitationsRequest, GetInvitationsResponse, GetLLMSettingsRequest, GetLLMSettingsResponse, GetWorkspaceInfoRequest, GetWorkspaceInfoResponse, GetWorkspaceUsersRequest, GetWorkspaceUsersResponse, InviteUserRequest, InviteUserResponse, PreviewWorkspaceNameRequest, PreviewWorkspaceNameResponse, RemoveInvitationRequest, RemoveInvitationResponse, SaveLLMSettingsRequest, SaveLLMSettingsResponse, UpdateWorkspaceRequest, UpdateWorkspaceResponse } from "./workspace.messages_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.WorkspaceService
 */
export const WorkspaceService = {
  typeName: "platform.WorkspaceService",
  methods: {
    /**
     * @generated from rpc platform.WorkspaceService.CreateWorkspace
     */
    createWorkspace: {
      name: "CreateWorkspace",
      I: CreateWorkspaceRequest,
      O: CreateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.PreviewWorkspaceName
     */
    previewWorkspaceName: {
      name: "PreviewWorkspaceName",
      I: PreviewWorkspaceNameRequest,
      O: PreviewWorkspaceNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.GetInfo
     */
    getInfo: {
      name: "GetInfo",
      I: GetWorkspaceInfoRequest,
      O: GetWorkspaceInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.UpdateWorkspace
     */
    updateWorkspace: {
      name: "UpdateWorkspace",
      I: UpdateWorkspaceRequest,
      O: UpdateWorkspaceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.GetUsers
     */
    getUsers: {
      name: "GetUsers",
      I: GetWorkspaceUsersRequest,
      O: GetWorkspaceUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Invitation management
     *
     * @generated from rpc platform.WorkspaceService.InviteUser
     */
    inviteUser: {
      name: "InviteUser",
      I: InviteUserRequest,
      O: InviteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.GetInvitations
     */
    getInvitations: {
      name: "GetInvitations",
      I: GetInvitationsRequest,
      O: GetInvitationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.RemoveInvitation
     */
    removeInvitation: {
      name: "RemoveInvitation",
      I: RemoveInvitationRequest,
      O: RemoveInvitationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * LLM settings (BYOK)
     *
     * @generated from rpc platform.WorkspaceService.SaveLLMSettings
     */
    saveLLMSettings: {
      name: "SaveLLMSettings",
      I: SaveLLMSettingsRequest,
      O: SaveLLMSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.WorkspaceService.GetLLMSettings
     */
    getLLMSettings: {
      name: "GetLLMSettings",
      I: GetLLMSettingsRequest,
      O: GetLLMSettingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

