// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file workspace.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message platform.WorkspaceRole
 */
export class WorkspaceRole extends Message<WorkspaceRole> {
  /**
   * @generated from field: platform.Workspace Workspace = 1;
   */
  Workspace?: Workspace;

  /**
   * @generated from field: repeated string Role = 2;
   */
  Role: string[] = [];

  constructor(data?: PartialMessage<WorkspaceRole>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.WorkspaceRole";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Workspace", kind: "message", T: Workspace },
    { no: 2, name: "Role", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkspaceRole {
    return new WorkspaceRole().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkspaceRole {
    return new WorkspaceRole().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkspaceRole {
    return new WorkspaceRole().fromJsonString(jsonString, options);
  }

  static equals(a: WorkspaceRole | PlainMessage<WorkspaceRole> | undefined, b: WorkspaceRole | PlainMessage<WorkspaceRole> | undefined): boolean {
    return proto3.util.equals(WorkspaceRole, a, b);
  }
}

/**
 * @generated from message platform.Workspace
 */
export class Workspace extends Message<Workspace> {
  /**
   * @generated from field: string ID = 1;
   */
  ID = "";

  /**
   * @todo rename to NameUnique
   *
   * @generated from field: string SlugUniq = 2;
   */
  SlugUniq = "";

  /**
   * @todo rename to Name
   *
   * @generated from field: string Slug = 3;
   */
  Slug = "";

  /**
   * @generated from field: string DisplayName = 4;
   */
  DisplayName = "";

  constructor(data?: PartialMessage<Workspace>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.Workspace";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "SlugUniq", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "DisplayName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Workspace {
    return new Workspace().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Workspace {
    return new Workspace().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Workspace {
    return new Workspace().fromJsonString(jsonString, options);
  }

  static equals(a: Workspace | PlainMessage<Workspace> | undefined, b: Workspace | PlainMessage<Workspace> | undefined): boolean {
    return proto3.util.equals(Workspace, a, b);
  }
}

