// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file workspace-events.proto (package platform, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Struct } from "@bufbuild/protobuf";

/**
 * @generated from message platform.StreamWorkspaceEventsRequest
 */
export class StreamWorkspaceEventsRequest extends Message<StreamWorkspaceEventsRequest> {
  /**
   * Optional: filter by event types (empty = all events)
   *
   * @generated from field: repeated string event_types = 1;
   */
  eventTypes: string[] = [];

  constructor(data?: PartialMessage<StreamWorkspaceEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.StreamWorkspaceEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamWorkspaceEventsRequest {
    return new StreamWorkspaceEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamWorkspaceEventsRequest {
    return new StreamWorkspaceEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamWorkspaceEventsRequest {
    return new StreamWorkspaceEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamWorkspaceEventsRequest | PlainMessage<StreamWorkspaceEventsRequest> | undefined, b: StreamWorkspaceEventsRequest | PlainMessage<StreamWorkspaceEventsRequest> | undefined): boolean {
    return proto3.util.equals(StreamWorkspaceEventsRequest, a, b);
  }
}

/**
 * @generated from message platform.WorkspaceEvent
 */
export class WorkspaceEvent extends Message<WorkspaceEvent> {
  /**
   * Event type: "job.created", "job.progress", "job.completed", "notification", etc.
   *
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * Resource identifier (job ID, deployment ID, etc.)
   *
   * @generated from field: string resource_id = 2;
   */
  resourceId = "";

  /**
   * Event payload - structure depends on event type
   *
   * @generated from field: google.protobuf.Struct payload = 3;
   */
  payload?: Struct;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 timestamp = 4;
   */
  timestamp = protoInt64.zero;

  constructor(data?: PartialMessage<WorkspaceEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "platform.WorkspaceEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "resource_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "payload", kind: "message", T: Struct },
    { no: 4, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkspaceEvent {
    return new WorkspaceEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkspaceEvent {
    return new WorkspaceEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkspaceEvent {
    return new WorkspaceEvent().fromJsonString(jsonString, options);
  }

  static equals(a: WorkspaceEvent | PlainMessage<WorkspaceEvent> | undefined, b: WorkspaceEvent | PlainMessage<WorkspaceEvent> | undefined): boolean {
    return proto3.util.equals(WorkspaceEvent, a, b);
  }
}

