// MCPService — public gRPC for machine clients (mcp-server, future SDKs,
// agent runtimes). See docs/design/mcp-service.md for the rationale and
// the full operation surface description.
//
// Versioned at v1 from day one. Breaking changes ship as v2.proto in a
// new package; existing v1 clients keep working.
//
// Served on grpc-api.tinysystems.io:443 alongside the dashboard's
// gRPC. Bearer-token auth via the shared auth interceptor.

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file mcp/v1/mcp_service.proto (package platform.mcp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ApplyFlowOperationsRequest, ApplyFlowOperationsResponse, CreateFlowRequest, CreateProjectRequest, CreateScenarioRequest, DeleteFlowRequest, DeleteProjectRequest, DeleteScenarioRequest, Empty, Flow, GetModuleRequest, GetProjectRequest, GetProjectResponse, GetScenarioRequest, GetTraceRequest, InspectPortRequest, InspectPortResponse, InstallModuleEvent, InstallModuleRequest, ListModulesRequest, ListModulesResponse, ListProjectsRequest, ListProjectsResponse, ListScenariosRequest, ListScenariosResponse, ListTracesRequest, ListTracesResponse, LogEvent, ModuleDetails, Project, Scenario, SendSignalRequest, SendSignalResponse, StreamLogsRequest, Trace, UninstallModuleRequest, UninstallModuleResponse, UpdateScenarioPortRequest, WatchFlowRequest, WatchFlowResponse, WatchTracesRequest, WatchWorkspaceActivityRequest, WorkspaceActivityEvent } from "./mcp_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service platform.mcp.v1.MCPService
 */
export const MCPService = {
  typeName: "platform.mcp.v1.MCPService",
  methods: {
    /**
     * Projects
     *
     * @generated from rpc platform.mcp.v1.MCPService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: GetProjectRequest,
      O: GetProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: Project,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.DeleteProject
     */
    deleteProject: {
      name: "DeleteProject",
      I: DeleteProjectRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Flows
     *
     * @generated from rpc platform.mcp.v1.MCPService.CreateFlow
     */
    createFlow: {
      name: "CreateFlow",
      I: CreateFlowRequest,
      O: Flow,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.DeleteFlow
     */
    deleteFlow: {
      name: "DeleteFlow",
      I: DeleteFlowRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * ApplyFlowOperations is fine-grained: callers submit a list of
     * ADD / UPDATE / DELETE ops on flow elements (nodes + edges). Server
     * returns per-op success/failure. Maps 1:1 to mcp-server's edit_flow
     * and build_flow tools.
     *
     * @generated from rpc platform.mcp.v1.MCPService.ApplyFlowOperations
     */
    applyFlowOperations: {
      name: "ApplyFlowOperations",
      I: ApplyFlowOperationsRequest,
      O: ApplyFlowOperationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Modules + capabilities. GetModule returns full component + port
     * details — the data MCP needs to wire edges. ListModules returns
     * summaries only (names + version + counts) for catalog browsing.
     *
     * @generated from rpc platform.mcp.v1.MCPService.ListModules
     */
    listModules: {
      name: "ListModules",
      I: ListModulesRequest,
      O: ListModulesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.GetModule
     */
    getModule: {
      name: "GetModule",
      I: GetModuleRequest,
      O: ModuleDetails,
      kind: MethodKind.Unary,
    },
    /**
     * InstallModule installs a module into the workspace's cluster.
     * Backed by the same taskq job the dashboard uses — the gRPC
     * stream tails the job tracker and emits one event per state /
     * log change. Terminates on completed or failed.
     *
     * @generated from rpc platform.mcp.v1.MCPService.InstallModule
     */
    installModule: {
      name: "InstallModule",
      I: InstallModuleRequest,
      O: InstallModuleEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * UninstallModule tears down a deployed module via Helm. Refuses
     * when any TinyNode in the workspace still uses one of the
     * module's components — caller should delete those nodes first.
     *
     * @generated from rpc platform.mcp.v1.MCPService.UninstallModule
     */
    uninstallModule: {
      name: "UninstallModule",
      I: UninstallModuleRequest,
      O: UninstallModuleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Execution
     * SendSignal fires a TinySignal CR and returns the resulting trace
     * ID. Caller pulls span detail via GetTrace.
     *
     * @generated from rpc platform.mcp.v1.MCPService.SendSignal
     */
    sendSignal: {
      name: "SendSignal",
      I: SendSignalRequest,
      O: SendSignalResponse,
      kind: MethodKind.Unary,
    },
    /**
     * InspectPort returns the actual schema and simulated/real data
     * for a node port. Uses recursive simulation through the flow
     * graph, not static schema lookup. If trace_id is provided, the
     * result uses real trace data instead of mocks (has_real_data is
     * set accordingly). Mirrors the dashboard's port preview path.
     *
     * @generated from rpc platform.mcp.v1.MCPService.InspectPort
     */
    inspectPort: {
      name: "InspectPort",
      I: InspectPortRequest,
      O: InspectPortResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Trace observability
     *
     * @generated from rpc platform.mcp.v1.MCPService.ListTraces
     */
    listTraces: {
      name: "ListTraces",
      I: ListTracesRequest,
      O: ListTracesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.GetTrace
     */
    getTrace: {
      name: "GetTrace",
      I: GetTraceRequest,
      O: Trace,
      kind: MethodKind.Unary,
    },
    /**
     * WatchTraces server-streams traces as they complete, filtered by
     * project + optional flow. Useful for agent UIs that render live
     * execution; equivalent to the dashboard's traces panel.
     *
     * @generated from rpc platform.mcp.v1.MCPService.WatchTraces
     */
    watchTraces: {
      name: "WatchTraces",
      I: WatchTracesRequest,
      O: Trace,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Scenarios — sample-data snapshots for compile-time edge
     * validation. Backed by TinyScenario CRDs.
     *
     * @generated from rpc platform.mcp.v1.MCPService.ListScenarios
     */
    listScenarios: {
      name: "ListScenarios",
      I: ListScenariosRequest,
      O: ListScenariosResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.GetScenario
     */
    getScenario: {
      name: "GetScenario",
      I: GetScenarioRequest,
      O: Scenario,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.CreateScenario
     */
    createScenario: {
      name: "CreateScenario",
      I: CreateScenarioRequest,
      O: Scenario,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.UpdateScenarioPort
     */
    updateScenarioPort: {
      name: "UpdateScenarioPort",
      I: UpdateScenarioPortRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc platform.mcp.v1.MCPService.DeleteScenario
     */
    deleteScenario: {
      name: "DeleteScenario",
      I: DeleteScenarioRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Live observability
     * StreamLogs streams pod logs filtered by namespace + labels.
     * Server emits LogEvent per log line. Backpressure: if the client
     * can't keep up, server sends a 'truncated' control event and
     * resumes from now.
     *
     * @generated from rpc platform.mcp.v1.MCPService.StreamLogs
     */
    streamLogs: {
      name: "StreamLogs",
      I: StreamLogsRequest,
      O: LogEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * WatchFlow streams flow element changes. Server emits the current
     * flow state as a batch of ADD events at stream start (no separate
     * GetFlow needed), then streams further ADD/UPDATE/DELETE events
     * as the flow mutates on the cluster. Mirrors the convention
     * established by FlowService.GetFlowStream — batch of element
     * events per response, no oneof.
     *
     * @generated from rpc platform.mcp.v1.MCPService.WatchFlow
     */
    watchFlow: {
      name: "WatchFlow",
      I: WatchFlowRequest,
      O: WatchFlowResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

/**
 * @generated from service platform.mcp.v1.WorkspaceActivityService
 */
export const WorkspaceActivityService = {
  typeName: "platform.mcp.v1.WorkspaceActivityService",
  methods: {
    /**
     * Watch streams events for the caller's current workspace
     * (resolved from auth context). Closes when the client
     * disconnects or the context times out.
     *
     * @generated from rpc platform.mcp.v1.WorkspaceActivityService.Watch
     */
    watch: {
      name: "Watch",
      I: WatchWorkspaceActivityRequest,
      O: WorkspaceActivityEvent,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

